"use client";
import { useMemo, useState } from "react";
import { CalculatorTrust, ReportCalculatorIssue, numberValue, useSavedState } from "./CalculatorCommon";
import { COMBAT_JOBS, MATERIA_GRADES, OVERMELD_RATES, RELIC_SERIES, SUBMARINE_PARTS } from "./CalculatorData";

const stats = ["Physical","Mental","Tactical"] as const;
type Recruit={id:string;name:string;className:string;level:number;affinity:string;values:[number,number,number];included:boolean};
const initialRecruits:Recruit[]=["Alka Zolka","Cecily","Hastaloeya","Khorchi"].map((name,index)=>({id:`starter-${index}`,name,className:["Marauder","Conjurer","Gladiator","Archer"][index],level:60,affinity:"None",values:[[320,280,250],[250,360,260],[280,250,370],[350,300,230]][index] as [number,number,number],included:true}));

export function SquadronCalculator(){
  const [roster,setRoster]=useSavedState<Recruit[]>("squadron-roster",initialRecruits);
  const [mission,setMission]=useSavedState("squadron-mission",{name:"Next mission",required:[1000,1000,1000] as [number,number,number],board:[0,0,0] as [number,number,number],allowPartial:true});
  const results=useMemo(()=>{const pool=roster.filter(item=>item.included&&item.name.trim()),output:{team:Recruit[];totals:number[];deficits:number[];score:number}[]=[];for(let a=0;a<pool.length;a++)for(let b=a+1;b<pool.length;b++)for(let c=b+1;c<pool.length;c++)for(let d=c+1;d<pool.length;d++){const team=[pool[a],pool[b],pool[c],pool[d]],totals=stats.map((_,index)=>team.reduce((sum,item)=>sum+item.values[index],mission.board[index])),deficits=totals.map((value,index)=>Math.max(0,mission.required[index]-value)),score=deficits.reduce((sum,value)=>sum+value,0);if(!score||mission.allowPartial)output.push({team,totals,deficits,score});}return output.sort((a,b)=>a.score-b.score||b.totals.reduce((x,y)=>x+y,0)-a.totals.reduce((x,y)=>x+y,0)).slice(0,8)},[roster,mission]);
  const update=(id:string,patch:Partial<Recruit>)=>setRoster(value=>value.map(item=>item.id===id?{...item,...patch}:item));
  return <article className="calculator-panel"><header className="calculator-heading"><div><span className="tag">Saved roster</span><h3>Squadron mission optimizer</h3><p>Keep the roster once, then compare four-recruit teams against a mission.</p></div></header>
    <CalculatorTrust confidence="Planning aid" updated="September 14, 2026" sources={[{label:"Adventurer Squadron reference",url:"https://ffxiv.consolegameswiki.com/wiki/Adventurer_Squadrons"}]}>Enter the values shown in game. Affinity is recorded for planning but is not automatically added to the three attribute totals.</CalculatorTrust>
    <section className="calculator-section"><div className="calculator-section-title"><h4>My roster</h4><button type="button" className="button secondary" onClick={()=>setRoster(value=>[...value,{id:crypto.randomUUID(),name:"",className:"Gladiator",level:1,affinity:"None",values:[0,0,0],included:true}])}>Add recruit</button></div>
      <div className="calculator-roster">{roster.map(item=><div className="calculator-roster-row" key={item.id}><label className="calculator-inline-check"><input type="checkbox" checked={item.included} onChange={event=>update(item.id,{included:event.target.checked})}/> Search</label><label>Name<input value={item.name} onChange={event=>update(item.id,{name:event.target.value})}/></label><label>Class<input value={item.className} onChange={event=>update(item.id,{className:event.target.value})}/></label><label>Level<input type="number" min="1" max="60" value={item.level} onChange={event=>update(item.id,{level:+event.target.value})}/></label>{stats.map((label,index)=><label key={label}>{label}<input type="number" min="0" value={item.values[index]} onChange={event=>{const values=[...item.values] as [number,number,number];values[index]=+event.target.value;update(item.id,{values})}}/></label>)}<label>Affinity<input value={item.affinity} onChange={event=>update(item.id,{affinity:event.target.value})}/></label><button type="button" className="button secondary" onClick={()=>setRoster(value=>value.filter(row=>row.id!==item.id))}>Remove</button></div>)}</div>
    </section>
    <section className="calculator-section"><h4>Mission</h4><label>Mission name<input value={mission.name} onChange={event=>setMission({...mission,name:event.target.value})}/></label><div className="calculator-fields">{stats.map((label,index)=><label key={label}>{label} required<input type="number" value={mission.required[index]} onChange={event=>{const required=[...mission.required] as [number,number,number];required[index]=+event.target.value;setMission({...mission,required})}}/></label>)}{stats.map((label,index)=><label key={`${label}-board`}>{label} board bonus<input type="number" value={mission.board[index]} onChange={event=>{const board=[...mission.board] as [number,number,number];board[index]=+event.target.value;setMission({...mission,board})}}/></label>)}</div><label className="calculator-inline-check"><input type="checkbox" checked={mission.allowPartial} onChange={event=>setMission({...mission,allowPartial:event.target.checked})}/> Show closest teams when no exact match exists</label></section>
    <section className="calculator-result"><h4>Best teams</h4>{results.length?results.map((result,index)=><div className={`calculator-ranked-result ${result.score?"partial":"success"}`} key={index}><b>{index+1}. {result.team.map(item=>item.name).join(", ")}</b><span>{result.totals.join(" / ")}</span><small>{result.score?`Still short: ${result.deficits.join(" / ")}`:"All three requirements met."}</small></div>):<p>Add and include at least four recruits.</p>}</section>
    <ReportCalculatorIssue calculator="Squadron mission" context={{roster,mission,results:results.slice(0,2)}}/></article>;
}

const subStats=["Surveillance","Retrieval","Speed","Range","Favor"] as const;
export function SubmarineCalculator(){
  const [settings,setSettings]=useSavedState("submarine",{name:"Submersible 1",rank:50,capacity:80,minimum:[0,0,0,0,0],priority:1,ownedOnly:false,owned:[] as string[],requiredRange:0});
  const eligible=SUBMARINE_PARTS.filter(part=>part.rank<=settings.rank&&(!settings.ownedOnly||settings.owned.includes(part.name)));
  const bySlot=(slot:typeof SUBMARINE_PARTS[number]["slot"])=>eligible.filter(part=>part.slot===slot);
  const results=useMemo(()=>{const output:{parts:typeof SUBMARINE_PARTS;cost:number;values:number[];code:string}[]=[];for(const hull of bySlot("Hull"))for(const stern of bySlot("Stern"))for(const bow of bySlot("Bow"))for(const bridge of bySlot("Bridge")){const parts=[hull,stern,bow,bridge],cost=parts.reduce((sum,part)=>sum+part.cost,0),values=subStats.map((_,index)=>parts.reduce((sum,part)=>sum+part.stats[index],0));if(cost<=settings.capacity&&!values.some((value,index)=>value<settings.minimum[index])&&values[3]>=settings.requiredRange)output.push({parts,cost,values,code:parts.map(part=>part.code).join("")});}return output.sort((a,b)=>b.values[settings.priority]-a.values[settings.priority]||a.cost-b.cost).slice(0,20)},[eligible,settings]);
  return <article className="calculator-panel"><header className="calculator-heading"><div><span className="tag">Complete component table</span><h3>FC submarine build finder</h3><p>Search slot-correct components by rank, capacity, range and stat thresholds.</p></div></header>
    <CalculatorTrust confidence="Exact model" updated="September 14, 2026" sources={[{label:"Submersible component table",url:"https://ffxiv.consolegameswiki.com/wiki/Submersible_Components"}]}>Build totals are exact for the listed components. Voyage duration, unlocks and loot are not yet modeled.</CalculatorTrust>
    <div className="calculator-fields"><label>Submersible name<input value={settings.name} onChange={event=>setSettings({...settings,name:event.target.value})}/></label><label>Rank<input type="number" min="1" value={settings.rank} onChange={event=>setSettings({...settings,rank:+event.target.value})}/></label><label>Capacity<input type="number" min="20" value={settings.capacity} onChange={event=>setSettings({...settings,capacity:+event.target.value})}/></label><label>Required route range<input type="number" min="0" value={settings.requiredRange} onChange={event=>setSettings({...settings,requiredRange:+event.target.value})}/></label><label>Optimize<select value={settings.priority} onChange={event=>setSettings({...settings,priority:+event.target.value})}>{subStats.map((label,index)=><option value={index} key={label}>{label}</option>)}</select></label>{subStats.map((label,index)=><label key={label}>Minimum {label}<input type="number" value={settings.minimum[index]} onChange={event=>{const minimum=[...settings.minimum];minimum[index]=+event.target.value;setSettings({...settings,minimum})}}/></label>)}</div>
    <details><summary>Restrict the search to parts the FC owns</summary><label className="calculator-inline-check"><input type="checkbox" checked={settings.ownedOnly} onChange={event=>setSettings({...settings,ownedOnly:event.target.checked})}/> Use owned parts only</label><div className="calculator-chip-grid">{SUBMARINE_PARTS.filter(part=>part.rank<=settings.rank).map(part=><label className="calculator-inline-check" key={part.name}><input type="checkbox" checked={settings.owned.includes(part.name)} onChange={()=>setSettings({...settings,owned:settings.owned.includes(part.name)?settings.owned.filter(name=>name!==part.name):[...settings.owned,part.name]})}/>{part.name}</label>)}</div></details>
    <section className="calculator-result"><h4>{results.length} best matching builds</h4>{results.length?results.map((result,index)=><div className="calculator-ranked-result" key={`${result.code}-${index}`}><b>{result.code} · {result.parts.map(part=>part.name).join(" / ")}</b><span>Capacity {result.cost}/{settings.capacity}</span><small>{subStats.map((label,i)=>`${label} ${result.values[i]}`).join(" · ")}</small></div>):<p>No build meets every restriction. Lower a minimum, increase capacity, or include more owned parts.</p>}</section>
    <ReportCalculatorIssue calculator="Submarine build" context={{settings,results:results.slice(0,3)}}/></article>;
}

type MeldStat={id:string;name:string;current:number;cap:number;priority:number};
export function MateriaCalculator(){
  const [plan,setPlan]=useSavedState("materia",{job:"Crafter",item:"New equipment",naturalSlots:2,mode:"conservative",price:15000,stats:[{id:"craftsmanship",name:"Craftsmanship",current:0,cap:108,priority:3},{id:"control",name:"Control",current:0,cap:108,priority:2},{id:"cp",name:"CP",current:0,cap:18,priority:1}] as MeldStat[]});
  const melds=useMemo(()=>{const remaining=Object.fromEntries(plan.stats.map(stat=>[stat.id,Math.max(0,stat.cap-stat.current)])),rows:{slot:number;stat:string;grade:string;gain:number;waste:number;rate:number}[]=[];for(let slot=0;slot<5;slot++){const candidates=plan.stats.filter(stat=>remaining[stat.id]>0).sort((a,b)=>b.priority-a.priority);if(!candidates.length)break;const stat=candidates[0],grades=MATERIA_GRADES.filter(grade=>slot<plan.naturalSlots||!grade.firstOvermeldOnly||slot===plan.naturalSlots);const grade=(plan.mode==="conservative"?grades.find(item=>item.value<=remaining[stat.id]):null)||grades[0];const effective=Math.min(grade.value,remaining[stat.id]);rows.push({slot:slot+1,stat:stat.name,grade:grade.name,gain:effective,waste:grade.value-effective,rate:slot<plan.naturalSlots?100:OVERMELD_RATES[slot]||7});remaining[stat.id]-=effective;}return rows},[plan]);
  const expected=melds.reduce((sum,row)=>sum+100/row.rate,0),safe90=melds.reduce((sum,row)=>sum+(row.rate===100?1:Math.ceil(Math.log(.1)/Math.log(1-row.rate/100))),0);
  return <article className="calculator-panel"><header className="calculator-heading"><div><span className="tag">Cap-aware plan</span><h3>Materia and overmeld planner</h3><p>Allocate five slots by stat priority and see waste, success rates and a practical shopping range.</p></div></header>
    <CalculatorTrust confidence="Estimate" updated="September 14, 2026" sources={[{label:"Materia melding rules",url:"https://ffxiv.consolegameswiki.com/wiki/Materia"}]}>Enter the cap shown for the individual item. Purchasing totals describe probability, not a guarantee.</CalculatorTrust>
    <div className="calculator-fields"><label>Job or role<input value={plan.job} onChange={event=>setPlan({...plan,job:event.target.value})}/></label><label>Equipment<input value={plan.item} onChange={event=>setPlan({...plan,item:event.target.value})}/></label><label>Natural slots<select value={plan.naturalSlots} onChange={event=>setPlan({...plan,naturalSlots:+event.target.value})}><option value="1">1</option><option value="2">2</option></select></label><label>Mode<select value={plan.mode} onChange={event=>setPlan({...plan,mode:event.target.value})}><option value="conservative">Cap-safe</option><option value="maximum">Maximum value</option></select></label><label>Price per materia<input type="number" min="0" value={plan.price} onChange={event=>setPlan({...plan,price:+event.target.value})}/></label></div>
    <div className="calculator-roster">{plan.stats.map(stat=><div className="calculator-roster-row materia" key={stat.id}><label>Stat<input value={stat.name} onChange={event=>setPlan({...plan,stats:plan.stats.map(row=>row.id===stat.id?{...row,name:event.target.value}:row)})}/></label>{[["Current","current"],["Item cap","cap"],["Priority","priority"]].map(([label,key])=><label key={key}>{label}<input type="number" value={stat[key as "current"|"cap"|"priority"]} onChange={event=>setPlan({...plan,stats:plan.stats.map(row=>row.id===stat.id?{...row,[key]:+event.target.value}:row)})}/></label>)}<button type="button" className="button secondary" onClick={()=>setPlan({...plan,stats:plan.stats.filter(row=>row.id!==stat.id)})}>Remove</button></div>)}</div><button type="button" className="button secondary" onClick={()=>setPlan({...plan,stats:[...plan.stats,{id:crypto.randomUUID(),name:"New stat",current:0,cap:0,priority:0}]})}>Add stat</button>
    <section className="calculator-result"><h4>Recommended order</h4>{melds.map(row=><div className="calculator-ranked-result" key={row.slot}><b>Slot {row.slot}: {row.stat} Materia {row.grade}</b><span>{row.rate}% success</span><small>Effective +{row.gain}{row.waste?` · ${row.waste} points would be wasted`:" · no overcap waste"}</small></div>)}<p><b>Shopping estimate:</b> about {Math.ceil(expected)} materia on average; {safe90} provides roughly a per-slot 90% planning allowance. At the entered price: approximately {(Math.ceil(expected)*plan.price).toLocaleString()} gil average.</p></section>
    <ReportCalculatorIssue calculator="Materia planner" context={{plan,melds,expected,safe90}}/></article>;
}

type Breakpoint={id:string;name:string;gathering:number;perception:number;gp:number;benefit:string};
export function GatheringCalculator(){
  const [profile,setProfile]=useSavedState("gathering",{job:"Miner",gathering:0,perception:0,gp:0,food:{name:"No food",gatheringPercent:0,gatheringCap:0,perceptionPercent:0,perceptionCap:0,gpPercent:0,gpCap:0},breakpoints:[{id:"custom",name:"Target node",gathering:0,perception:0,gp:0,benefit:"Enter the bonus shown by your current guide or node."}] as Breakpoint[]});
  const boosted={gathering:profile.gathering+Math.min(Math.floor(profile.gathering*profile.food.gatheringPercent/100),profile.food.gatheringCap),perception:profile.perception+Math.min(Math.floor(profile.perception*profile.food.perceptionPercent/100),profile.food.perceptionCap),gp:profile.gp+Math.min(Math.floor(profile.gp*profile.food.gpPercent/100),profile.food.gpCap)};
  return <article className="calculator-panel"><header className="calculator-heading"><div><span className="tag">Benefit-first checker</span><h3>Gathering breakpoint planner</h3><p>Save a gatherer, apply food caps correctly, and see exactly which node benefits are available.</p></div></header>
    <CalculatorTrust confidence="Planning aid" updated="September 14, 2026" sources={[{label:"Gathering attributes",url:"https://ffxiv.consolegameswiki.com/wiki/Gathering"}]}>Node breakpoints change between patches and are entered manually so the portal does not present stale thresholds as current.</CalculatorTrust>
    <div className="calculator-fields"><label>Gatherer<select value={profile.job} onChange={event=>setProfile({...profile,job:event.target.value})}><option>Miner</option><option>Botanist</option><option>Fisher</option></select></label>{["gathering","perception","gp"].map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<input type="number" min="0" value={profile[key as "gathering"|"perception"|"gp"]} onChange={event=>setProfile({...profile,[key]:+event.target.value})}/></label>)}</div>
    <details><summary>Food and capped bonuses</summary><div className="calculator-fields"><label>Food name<input value={profile.food.name} onChange={event=>setProfile({...profile,food:{...profile.food,name:event.target.value}})}/></label>{["gathering","perception","gp"].flatMap(key=>[[`${key}Percent`,`${key} %`],[`${key}Cap`,`${key} cap`]]).map(([key,label])=><label key={key}>{label}<input type="number" value={profile.food[key as keyof typeof profile.food]} onChange={event=>setProfile({...profile,food:{...profile.food,[key]:+event.target.value}})}/></label>)}</div></details>
    <section className="calculator-section"><div className="calculator-section-title"><h4>Node or item breakpoints</h4><button type="button" className="button secondary" onClick={()=>setProfile({...profile,breakpoints:[...profile.breakpoints,{id:crypto.randomUUID(),name:"",gathering:0,perception:0,gp:0,benefit:""}]})}>Add breakpoint</button></div>{profile.breakpoints.map(point=><div className="calculator-roster-row" key={point.id}><label>Item or node<input value={point.name} onChange={event=>setProfile({...profile,breakpoints:profile.breakpoints.map(row=>row.id===point.id?{...row,name:event.target.value}:row)})}/></label>{["gathering","perception","gp"].map(key=><label key={key}>Required {key}<input type="number" value={point[key as "gathering"|"perception"|"gp"]} onChange={event=>setProfile({...profile,breakpoints:profile.breakpoints.map(row=>row.id===point.id?{...row,[key]:+event.target.value}:row)})}/></label>)}<label>Benefit<input value={point.benefit} onChange={event=>setProfile({...profile,breakpoints:profile.breakpoints.map(row=>row.id===point.id?{...row,benefit:event.target.value}:row)})}/></label><button type="button" className="button secondary" onClick={()=>setProfile({...profile,breakpoints:profile.breakpoints.filter(row=>row.id!==point.id)})}>Remove</button></div>)}</section>
    <section className="calculator-result"><h4>After {profile.food.name}</h4><p>Gathering {boosted.gathering} · Perception {boosted.perception} · GP {boosted.gp}</p>{profile.breakpoints.map(point=>{const deficits=[Math.max(0,point.gathering-boosted.gathering),Math.max(0,point.perception-boosted.perception),Math.max(0,point.gp-boosted.gp)],met=!deficits.some(Boolean);return <div className={`calculator-ranked-result ${met?"success":"partial"}`} key={point.id}><b>{point.name||"Unnamed breakpoint"}</b><span>{met?"Unlocked":"Not yet available"}</span><small>{met?point.benefit:`Short by Gathering ${deficits[0]}, Perception ${deficits[1]}, GP ${deficits[2]}`}</small></div>})}</section>
    <ReportCalculatorIssue calculator="Gathering breakpoint" context={{profile,boosted}}/></article>;
}

export function RelicCalculator(){
  const [tracker,setTracker]=useSavedState("relic",{series:RELIC_SERIES[0].name as string,job:COMBAT_JOBS[0],completed:[] as string[],resources:[{id:"first",name:"Primary currency",required:0,owned:0,perRun:1,minutes:10}]});
  const series=RELIC_SERIES.find(item=>item.name===tracker.series)||RELIC_SERIES[0],key=(stage:string)=>`${tracker.series}:${tracker.job}:${stage}`;
  const done=series.stages.filter(stage=>tracker.completed.includes(key(stage))).length,runs=tracker.resources.reduce((sum,row)=>sum+Math.ceil(Math.max(0,row.required-row.owned)/Math.max(1,row.perRun)),0),minutes=tracker.resources.reduce((sum,row)=>sum+Math.ceil(Math.max(0,row.required-row.owned)/Math.max(1,row.perRun))*row.minutes,0);
  function completeThrough(index:number){const stageKeys=series.stages.slice(0,index+1).map(key);setTracker({...tracker,completed:[...tracker.completed.filter(item=>!item.startsWith(`${tracker.series}:${tracker.job}:`)),...stageKeys]})}
  return <article className="calculator-panel"><header className="calculator-heading"><div><span className="tag">Multi-job progress</span><h3>Relic and currency planner</h3><p>Remember each job’s stage and translate remaining materials into runs and time.</p></div></header>
    <CalculatorTrust confidence="Planning aid" updated="September 14, 2026" sources={[{label:"Portal relic guides",url:"/?view=guides"},{label:"Relic weapon overview",url:"https://ffxiv.consolegameswiki.com/wiki/Relic_Weapons"}]}>Stage names are preloaded. Material rows remain editable because active quests and alternative acquisition routes determine what counts.</CalculatorTrust>
    <div className="calculator-fields"><label>Relic series<select value={tracker.series} onChange={event=>setTracker({...tracker,series:event.target.value})}>{RELIC_SERIES.map(item=><option key={item.name}>{item.name}</option>)}</select></label><label>Job<select value={tracker.job} onChange={event=>setTracker({...tracker,job:event.target.value})}>{COMBAT_JOBS.map(job=><option key={job}>{job}</option>)}</select></label></div>
    <section className="calculator-progress-card"><div><b>{done}/{series.stages.length} stages complete</b><progress max={series.stages.length} value={done}/></div><ol>{series.stages.map((stage,index)=><li key={stage}><label className="calculator-inline-check"><input type="checkbox" checked={tracker.completed.includes(key(stage))} onChange={event=>event.target.checked?completeThrough(index):setTracker({...tracker,completed:tracker.completed.filter(item=>item!==key(stage))})}/>{stage}</label></li>)}</ol></section>
    <section className="calculator-section"><div className="calculator-section-title"><h4>Current material and currency goals</h4><button type="button" className="button secondary" onClick={()=>setTracker({...tracker,resources:[...tracker.resources,{id:crypto.randomUUID(),name:"",required:0,owned:0,perRun:1,minutes:10}]})}>Add requirement</button></div>{tracker.resources.map(row=><div className="calculator-roster-row" key={row.id}>{[["Material or currency","name"],["Required","required"],["Owned","owned"],["Per run","perRun"],["Minutes per run","minutes"]].map(([label,field])=><label key={field}>{label}<input type={field==="name"?"text":"number"} value={row[field as keyof typeof row]} onChange={event=>setTracker({...tracker,resources:tracker.resources.map(item=>item.id===row.id?{...item,[field]:field==="name"?event.target.value:+event.target.value}:item)})}/></label>)}<button type="button" className="button secondary" onClick={()=>setTracker({...tracker,resources:tracker.resources.filter(item=>item.id!==row.id)})}>Remove</button></div>)}</section>
    <section className="calculator-result"><h4>Remaining plan</h4><p><b>{runs} estimated runs</b> · approximately {Math.floor(minutes/60)}h {minutes%60}m</p>{tracker.resources.map(row=><div className="calculator-ranked-result" key={row.id}><b>{row.name||"Unnamed requirement"}</b><span>{Math.max(0,row.required-row.owned).toLocaleString()} remaining</span><small>{Math.ceil(Math.max(0,row.required-row.owned)/Math.max(1,row.perRun))} estimated runs</small></div>)}</section>
    <ReportCalculatorIssue calculator="Relic and currency" context={{tracker,series:series.name,runs,minutes}}/></article>;
}
