import type { BuiltInGuide } from "./guide-library";

const refs = (label: string, url: string) => [{ label, url }];

type Seed = {
  slug: string; parentSlug: string; category: string; title: string; summary: string;
  expansion: string; level: string; audience: string; imageUrl: string; order: number;
  prep: string[]; steps: string[]; source: [string, string]; notes?: string[];
};

const fullArticle = (s: Seed): BuiltInGuide => ({
  slug: s.slug, parentSlug: s.parentSlug, type: "article", category: s.category,
  title: s.title, summary: s.summary, expansion: s.expansion, level: s.level,
  audience: s.audience, imageUrl: s.imageUrl, order: s.order,
  tags: [s.category.toLowerCase(), s.expansion.toLowerCase(), s.level],
  content: [
    "## Requirements and preparation", ...s.prep.map((x) => "- [ ] " + x), "",
    "## Complete step-by-step route", ...s.steps.map((x, i) => (i + 1) + ". " + x), "",
    "## Completion checks", "| Check | Required result |", "|---|---|",
    "| Active objective | The named quest is visible in Journal before farming; earlier items may not count. |",
    "| Correct class/job | Accept, complete class-specific objectives, and turn in on the named class/job. |",
    "| Equipment state | Equip the evolving item only when requested; unequip it if the exchange NPC refuses it. |",
    "| Quantity/quality | Match the exact item, amount, HQ icon, or collectability threshold in the duty list. |",
    "| Inventory | Keep a normal inventory slot and the relevant Armoury Chest slot open. |", "",
    "## Final checklist", "- [ ] Confirm the next objective before spending currency.",
    "- [ ] Keep the old stage until the replacement is visibly received.",
    "- [ ] Record chosen attributes before resetting them.",
    "- [ ] Unlock replicas or appearance rewards before discarding a stage.", "",
    "## Troubleshooting", "- **No marker:** finish the prerequisite, switch to the required class/job, and carry the prior stage.",
    "- **No drop:** confirm the quest is active and the source is named by its current duty list.",
    "- **Grey exchange:** unequip the item, repair it, and make inventory/Armoury Chest room.",
    ...(s.notes || []).map((x) => "- " + x),
  ].join("\n"), references: refs(s.source[0], s.source[1]),
});

const societyTier = (slug: string, title: string, level: string, expansion: string, links: string[], order: number): BuiltInGuide => ({
  slug, parentSlug: "tribal-quests", type: "collection", category: "Allied Society Tier", title,
  summary: "A complete level-specific route with rank timing, unlock gates, vendors, and one full guide per society.",
  expansion, level, audience: "Combat, Crafting & Gathering", tags: ["allied society", "reputation", level],
  imageUrl: "/guides/allied-society-bases.svg", order,
  content: ["## Tier rules", "- **12 daily allowances** are shared account-wide; a society normally offers three random quests.",
    "- Rank quests consume no allowance. When reputation caps, finish the blue rank quest before another daily; reputation cannot spill through the cap.",
    "- Accept and finish synced objectives on the eligible job receiving experience. A job change can hide nodes, recipes, items, or interactions.",
    "- New rank pools join earlier pools, so a high-rank character can still receive an early daily.", "",
    "## Societies in this tier", ...links.map((x) => "- " + x), "",
    "## Daily route", "1. Check Character → Reputation for a full bar.",
    "2. Accept all three on the intended job; open every Journal map and group objectives by area.",
    "3. Put supplied Key Items, mount actions, and duty actions on a temporary hotbar.",
    "4. Craft only Special Recipes; HQ is required only when the duty list shows the HQ icon.",
    "5. Turn in before reset, spend currency before its cap, complete any new blue quest, and reopen the vendor.",
    "", "## Rank pacing", "Friendly-era societies generally use Friendly → Trusted → Respected → Honored → Sworn → Bloodsworn. Exact reputation totals differ by expansion, and extra same-day quests can appear after a rank-up. The individual pages list the actual rank stories and reward tiers."].join("\n"),
  references: refs("Allied Society allowances and reputation", "https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests"),
});

const collectTier = (slug: string, title: string, level: string, expansion: string, hubs: string, books: string, order: number): BuiltInGuide => fullArticle({
  slug, parentSlug: "collectables-scrips", category: "Collectables & Scrips", title,
  summary: "The complete unlock, appraisal, scrip, Master Recipe, folklore, gear, and timed-node route for this tier.",
  expansion, level, audience: "Crafting & Gathering", imageUrl: "/guides/collectables-route.svg", order,
  prep: ["Complete Inscrutable Tastes in Foundation to unlock collectables, appraisers, and scrip exchanges.",
    "Reach and attune the tier's hubs: " + hubs + ".", "Unlock flying before building timed-node routes.",
    "Put Collect, Scrutiny, Scour/Meticulous, and current quality actions on accessible hotbars."],
  steps: ["Open Timers → Rowena's House of Splendors and select the exact class. The live list supplies the current item, minimum rating, rewards, and limits.",
    "Crafted collectables: open the collectable/Special Recipe, synthesize it, and raise quality into the required collectability band. Ordinary HQ rules do not apply.",
    "Miner/botanist: arrive during the node window, reveal the named item, use appraisal actions to meet the displayed rating, then Collect. Stop spending GP once the next reward band is unreachable.",
    "Fisher: enable Collect before casting and use the named fishing hole, bait, time, and weather. Keep only catches meeting the threshold.",
    "Turn in at any Collectable Appraiser. Test one item before making a batch and confirm its actual scrip return.",
    "Buy permanent unlocks before consumables: " + books + ". Use every purchased folklore tome from inventory; merely buying it does not reveal nodes.",
    "Then buy required tools/gear and materia. Old red/blue/yellow scrip advice is obsolete; use the current exchange categories shown in game.",
    "For a missing legendary node, verify the correct regional tome, its use from inventory, Eorzean time, weather, perception requirement, and exact zone."],
  source: ["Official collectables guide", "https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/collectables/"],
});

type Client = { slug: string; parent: string; name: string; level: string; expansion: string; location: string; unlock: string; prereq: string; story: string; glamour: string; order: number };
const clientArticle = (c: Client): BuiltInGuide => fullArticle({
  slug: c.slug, parentSlug: c.parent, category: "Custom Delivery Client", title: c.name,
  summary: "A client-specific unlock, weekly-item, satisfaction, crafting, gathering, fishing, reward, and appearance guide.",
  expansion: c.expansion, level: c.level, audience: "Crafting & Gathering", imageUrl: "/guides/custom-deliveries-route.svg", order: c.order,
  prep: ["Unlock Custom Deliveries through Go West, Craftsman.", "Keep six of the shared twelve weekly allowances available.",
    "Travel to " + c.location + ".", "Complete: " + c.prereq + "."],
  steps: ["Accept **" + c.unlock + "** and finish the introduction to add the client to Duty → Timers → Custom Deliveries.",
    "Open the client in Timers before producing anything. It shows this week's exact item, collectability bands, bonus, satisfaction, and allowances.",
    "Crafting: buy only the client-specific material from the nearby supplier, open Special Recipes → Custom Deliveries, and make one test item. Quality becomes collectability.",
    "Mining/botany: select the requested item in Timers/Gathering Log, use the named node, and meet the rating before Collect.",
    "Fishing: enable Collect, use the Fishing Log's hole and bait, and retain catches meeting the displayed band.",
    "Deliver up to six. A bonus request pays extra scrips and satisfaction; prioritize it only if its rating is practical.",
    "Complete each blue satisfaction follow-up: " + c.story + ". A missing final scene usually means one is waiting.",
    "Appearance at maximum satisfaction: " + c.glamour + ". Continue delivering afterward for scrips, experience, and achievements."],
  source: [c.name + " delivery reference", "https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries"],
  notes: ["Requested items rotate with rank and reset, so the in-game Timers entry is the exact current-week item list.",
    "Market items with similar names do not replace the client's quest-specific supplier materials."],
});

const customTier = (slug: string, title: string, level: string, expansion: string, links: string[], order: number): BuiltInGuide => ({
  slug, parentSlug: "custom-deliveries", type: "collection", category: "Custom Delivery Tier", title,
  summary: "A complete tier plan plus one full unlock-to-rank-five guide for every client.", expansion, level,
  audience: "Crafting & Gathering", tags: ["custom deliveries", "weekly", level], imageUrl: "/guides/custom-deliveries-route.svg", order,
  content: ["## Weekly rules", "- You have **12 deliveries per week account-wide** and may give at most **6 to one client**.",
    "- Requested items and bonuses are in Duty → Timers. Quality/rating becomes collectability; higher bands pay more.",
    "- Deliver on the class receiving experience. Max-satisfaction clients remain valid for scrip farming.", "",
    "## Clients", ...links.map((x) => "- " + x), "", "## Two-client plan",
    "1. Reserve six allowances for the client whose story or appearance controls you need.",
    "2. Use the other six on a bonus client or the class needing experience.",
    "3. Produce one test item, verify its rating in Timers, then make the batch.",
    "4. Finish newly opened blue follow-up quests before leaving the area."].join("\n"),
  references: refs("Custom Delivery rules", "https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries"),
});

const CLIENTS: Client[] = [
  { slug:"delivery-zhloe",parent:"custom-deliveries-tier-60",name:"Zhloe Aliapoh",level:"55+",expansion:"Heavensward",location:"Idyllshire (X:4.6, Y:6.7)",unlock:"Arms Wide Open",prereq:"Go West, Craftsman and the Idyllshire prerequisites",story:"orphanage supplies → improved provisions → rank-five conclusion",glamour:"available",order:10 },
  { slug:"delivery-mnaago",parent:"custom-deliveries-tier-60",name:"M'naago",level:"60+",expansion:"Stormblood",location:"Rhalgr's Reach (X:14.6, Y:9.4)",unlock:"None Forgotten, None Forsaken",prereq:"Stormblood progress and Reach Long and Prosper",story:"Widows and Orphans fund → resistance support → conclusion",glamour:"not available",order:20 },
  { slug:"delivery-kurenai",parent:"custom-deliveries-tier-60",name:"Kurenai",level:"62+",expansion:"Stormblood",location:"Sui-no-Sato (X:28.3, Y:15.3)",unlock:"The Seaweed Is Always Greener",prereq:"The Two Princesses of Sui-no-Sato chain",story:"surface study → village aid → conclusion",glamour:"available",order:30 },
  { slug:"delivery-adkiragh",parent:"custom-deliveries-tier-60",name:"Adkiragh",level:"66+",expansion:"Stormblood",location:"Idyllshire (X:4.8, Y:6.6)",unlock:"Between a Rock and the Hard Place",prereq:"Stormblood and Adkiragh/Zhloe prerequisite quests",story:"Hard Place recovery → benefactor mystery → reveal",glamour:"available",order:40 },
  { slug:"delivery-kai-shirr",parent:"custom-deliveries-tier-70",name:"Kai-Shirr",level:"70+",expansion:"Shadowbringers",location:"Eulmore (X:12.2, Y:9.9)",unlock:"Oh, Beehive Yourself",prereq:"Shadowbringers and Eulmore access",story:"Beehive venture → employment → venue conclusion",glamour:"available",order:10 },
  { slug:"delivery-ehll-tou",parent:"custom-deliveries-tier-70",name:"Ehll Tou",level:"70+",expansion:"Shadowbringers",location:"Firmament (X:13.5, Y:11.2)",unlock:"O Crafter, My Crafter",prereq:"Firmament access and Ehll Tou's sidequest chain",story:"apprenticeship → dragon-human exchange → graduation",glamour:"available",order:20 },
  { slug:"delivery-charlemend",parent:"custom-deliveries-tier-70",name:"Count Charlemend",level:"70+",expansion:"Shadowbringers",location:"Firmament (X:9.4, Y:8.7)",unlock:"You Can Count on It",prereq:"Those with Iron Wills and Firmament sidequests",story:"High House reform → service project → conclusion",glamour:"available",order:30 },
  { slug:"delivery-ameliance",parent:"custom-deliveries-tier-80",name:"Ameliance",level:"80+",expansion:"Endwalker",location:"Old Sharlayan (X:15.6, Y:7.2)",unlock:"Of Mothers and Merchants",prereq:"Endwalker progress and Go West, Craftsman",story:"student aid → family support → conclusion",glamour:"available",order:10 },
  { slug:"delivery-anden",parent:"custom-deliveries-tier-80",name:"Anden",level:"80+",expansion:"Endwalker",location:"Il Mheg (X:16.5, Y:33.8)",unlock:"That's So Anden",prereq:"Endwalker and Il Mheg story",story:"leafman recovery → memories → identity conclusion",glamour:"available",order:20 },
  { slug:"delivery-margrat",parent:"custom-deliveries-tier-80",name:"Margrat",level:"80+",expansion:"Endwalker",location:"Labyrinthos (X:20.4, Y:20.1)",unlock:"A Request of One's Own",prereq:"Endwalker and Labyrinthos access",story:"researcher welfare → department requests → celebration",glamour:"available",order:30 },
  { slug:"delivery-nitowikwe",parent:"custom-deliveries-tier-90",name:"Nitowikwe",level:"90+",expansion:"Dawntrail",location:"Shaaloani (X:14.3, Y:19.3)",unlock:"Laying New Tracks",prereq:"Dawntrail and railway sidequests",story:"rail restoration → community deliveries → route conclusion",glamour:"available",order:10 },
  { slug:"delivery-tiisol-ja",parent:"custom-deliveries-tier-90",name:"Tiisol Ja",level:"90+",expansion:"Dawntrail",location:"Tuliyollal (X:15.1, Y:12.0)",unlock:"Taco Time",prereq:"Dawntrail and food-business prerequisites",story:"menu development → regional sourcing → business conclusion",glamour:"follow the live rank-five unlock",order:20 },
];

const relic = (slug: string, parentSlug: string, title: string, expansion: string, level: string, order: number, prep: string[], steps: string[], source: string): BuiltInGuide => fullArticle({
  slug, parentSlug, category: title.split(":")[0] + " Stage", title,
  summary: "A self-contained stage guide with exact prerequisites, materials, duties, hand-ins, repeat rules, and failure checks.",
  expansion, level, audience: "Combat",
  imageUrl: expansion === "Heavensward" || expansion === "Endwalker" ? "/guides/relic-stage-route.svg" : "/guides/field-operation-route.svg",
  order, prep, steps, source: [title + " reference", source],
});

const RELIC_GUIDES: BuiltInGuide[] = [
  relic("anima-stage-animated-awoken","anima-weapons","Anima: Animated & Awoken","Heavensward","60",11,
    ["Finish Heavensward and An Unexpected Proposal.","Carry a second weapon for exchanges.","Choose six luminous crystals or surrender one completed Zodiac Zeta."],
    ["Accept Soul without Life from Ardashir in Azys Lla.","Obtain one luminous crystal from FATEs in each Heavensward field zone, or surrender a Zeta to Syndony in Mor Dhona; crystals may be farmed on any combat job.","Exchange the six crystals for Astral and Umbral Nodules and receive the Animated weapon.","Accept Toughening Up and clear, in order: Snowcloak; Sastasha (Hard); Qarn (Hard); Keeper of the Lake; Wanderer's Palace (Hard); Amdapor Keep (Hard); Dusk Vigil; Sohm Al; Aery; Vault.","The Anima must be equipped when each duty completes. If using a stronger weapon inside, equip the Anima before leaving.","Complete the NPC hand-offs and receive the Awoken weapon."],
    "https://ffxiv.consolegameswiki.com/wiki/Anima_Weapons"),
  relic("anima-stage-anima-hyperconductive","anima-weapons","Anima: Anima & Hyperconductive","Heavensward","60",12,
    ["Finish Toughening Up.","Verify every material before spending Poetics.","Check Grand Company, society-currency, and alternate exchanges."],
    ["Accept Coming into Its Own.","Acquire 10 each Unidentifiable Bone, Shell, Ore, and Seeds.","Acquire four each Adamantite Francesca, Titanium Alloy Mirror, Dispelling Arrow, and Kingcake in the quality required by the exchange.","Trade the four sets to Cristiana in Mor Dhona, then complete the Anima exchange.","Accept Finding Your Voice.","Obtain five Aether Oils from Poetics or the available Crystal Tower weekly repeatable quest.","Turn in all five for the Hyperconductive weapon."],
    "https://ffxiv.consolegameswiki.com/wiki/Anima_Weapons"),
  relic("anima-stage-reconditioned-complete","anima-weapons","Anima: Reconditioned, Sharpened & Complete","Heavensward","60",13,
    ["Finish Finding Your Voice.","Choose desired substats before converting Crystal Sand.","Stock Poetics for Umbrite and Singing Clusters."],
    ["Accept A Dream Fulfilled and receive the Enhanced Anima Glass.","Exchange eligible materials for Crystal Sand, buy Umbrite, and combine one of each into treated sand; bonus yields reduce the pairs needed.","Allocate the required treated sand and confirm attributes to receive the Reconditioned weapon.","Accept Future Proof, collect 50 Singing Clusters through Poetics and repeatable quests, and receive the Sharpened weapon.","Accept Born Again Anima and farm aetheric density from eligible duties with the Sharpened weapon equipped at completion.","Inspect the Enhanced Anima Glass to measure light; bonus windows change yield, not eligibility.","Finish the three trials and soul dialogue requested by Some Assembly Required to receive the Complete weapon."],
    "https://ffxiv.consolegameswiki.com/wiki/Anima_Weapons"),
  relic("anima-stage-lux","anima-weapons","Anima: Lux Finale & Replicas","Heavensward","60",14,
    ["Finish Born Again Anima and Some Assembly Required.","Carry Poetics for Ancient Enchanted Ink.","Leave an Armoury Chest slot open."],
    ["Complete Body and Soul and its NPC hand-offs.","Purchase the required Ancient Enchanted Ink and accept Best Friends Forever.","Clear the listed primals in quest order with the current Anima equipped at completion.","Return to Ardashir and Gerolt for the Lux weapon.","Finish replica-unlock dialogue and buy desired stage replicas before storing the original.","Use the reallocation process if substats were assigned incorrectly; confirm cost and preview first.","Additional jobs restart at Soul without Life but retain shared repeatable unlocks."],
    "https://ffxiv.consolegameswiki.com/wiki/Anima_Weapons"),

  relic("eureka-weapon-anemos","eurekan-weapons","Eureka: Anemos Weapon","Stormblood","70",11,
    ["Unlock Anemos through And We Shall Call It Eureka.","Obtain the level-70 Antiquated job weapon.","Learn the Magia Board and elemental strengths."],
    ["Level through challenge-log objectives, near-level chains, and notorious monsters; complete every level-gated Krile investigation.","Collect Protean Crystals directly or convert Anemos Crystals from NMs.","Upgrade the Antiquated weapon through Gerolt's Protean stages.","Obtain Pazuzu's Feathers from Wail in the Willows or the zone crystal exchange when available.","Exchange the feathers for the Anemos weapon and retain it for Pagos.","Attune aetherytes only when their elemental-level gate is met; request a raise rather than returning dead and losing experience."],
    "https://ffxiv.consolegameswiki.com/wiki/Eurekan_Weapons"),
  relic("eureka-weapon-pagos","eurekan-weapons","Eureka: Pagos Weapon","Stormblood","70",12,
    ["Complete the Anemos weapon and enter Pagos.","Advance Krile's story until the kettle unlocks.","Learn one-way cliff routes and the sleeping-dragon aggro rule."],
    ["Earn aetheric light through eligible Pagos activities and inspect the kettle rather than guessing.","Convert every full kettle at the Crystal Forge into Frosted Protean Crystals; do not overcap it.","Collect Pagos Crystals from NMs and Louhi's Ice from Louhi.","Complete every Gerolt exchange in order; later materials cannot bypass an unfinished earlier step.","Continue Pagos story quests to elemental 35 and finish the weapon exchange.","Keep the Pagos weapon for Pyros."],
    "https://ffxiv.consolegameswiki.com/wiki/Eurekan_Weapons"),
  relic("eureka-weapon-pyros","eurekan-weapons","Eureka: Pyros Weapon & Substats","Stormblood","70",13,
    ["Complete the Pagos weapon.","Unlock Logogram Appraisal and Logos Manipulation.","Bring defensive and offensive Logos actions rather than empty trays."],
    ["Appraise logograms and synthesize unique Logos actions; registered-action count gates weapon and armor progression.","Complete Krile's level-gated Pyros investigations.","Collect Pyros Crystals from NMs and Penthesilea's Flame from Lost Epic or its applicable exchange.","Complete Gerolt's Pyros weapon exchanges.","Unlock optional substat rolls only after meeting their Logos requirement.","A reroll replaces the prior result; stop on an acceptable allocation instead of spending indefinitely.","Finish the elemental-50 story to unlock Hydatos."],
    "https://ffxiv.consolegameswiki.com/wiki/Eurekan_Weapons"),
  relic("eureka-weapon-hydatos","eurekan-weapons","Eureka: Hydatos & Physeos","Stormblood","70",14,
    ["Complete the Pyros weapon and enter Hydatos.","Finish required Logos registrations.","Join an organized Baldesion Arsenal group before planning Physeos."],
    ["Reach elemental 60 and complete every Krile investigation.","Collect Hydatos Crystals from NMs and Crystalline Scales from Provenance Watcher.","Complete Gerolt's Hydatos weapon exchanges in order.","Defeat Ovni during an organized Arsenal trigger; respect reserved unstable portals and the group's stable-portal plan.","Collect Eureka Fragments from Baldesion Arsenal bosses and coffers.","Exchange fragments for Physeos and its Eureka elemental bonus.","Unlock replicas before disposing of visual stages; keep Physeos as the functional Eureka weapon."],
    "https://ffxiv.consolegameswiki.com/wiki/Eurekan_Weapons"),

  relic("resistance-stage-base-recollection","resistance-weapons","Resistance: Base through Recollection","Shadowbringers","80",11,
    ["Complete Shadowbringers, Return to Ivalice, and Hail to the Queen.","Unlock Gangos and the Southern Front.","Choose the job before buying materials."],
    ["Complete the first Resistance Is (Not) Futile route; later base weapons cost four Thavnairian Scalepowders bought with Poetics.","Accept For Want of a Memory.","Obtain 20 each Tortured, Sorrowful, and Harrowing Memories from their named Heavensward zone groups or Bozja while the quest is active.","Turn in all 60 for the Augmented Resistance weapon.","Accept The Will to Resist and obtain six Bitter Memories from qualifying level-60 dungeons, the daily Leveling roulette reward, or Bozja.","Turn in six for the Recollection weapon.","Additional jobs repeat material stages but not completed one-time story gates."],
    "https://ffxiv.consolegameswiki.com/wiki/Resistance_Weapons"),
  relic("resistance-stage-laws-order","resistance-weapons","Resistance: Law's Order","Shadowbringers","80",12,
    ["Finish the Southern Front story through Castrum Lacus Litore.","Unlock Delubrum Reginae through Save the Queen.","Carry the Recollection weapon."],
    ["Accept Change of Arms.","Collect 15 Loathsome Memories from Crystal Tower alliance raids, Castrum Lacus Litore, or qualifying critical engagements exactly as the active quest lists.","Use Crystal Tower for deterministic clears or Bozja/Castrum when also advancing field progress.","Turn in 15 to receive the Law's Order weapon.","Complete the next one-time Save the Queen story quests before the augmented stage.","Do not pre-farm later raid memories; clears before their collection quests are active cannot be credited."],
    "https://ffxiv.consolegameswiki.com/wiki/Resistance_Weapons"),
  relic("resistance-stage-augmented-law","resistance-weapons","Resistance: Augmented Law's Order","Shadowbringers","80",13,
    ["Complete The Lady of the Blades and the one-time raid-memory quests.","Unlock the specified alliance/normal raids and Delubrum Reginae.","If using Palace of the Dead, unlock sufficient floors first."],
    ["Complete the one-time collection of 18 Haunting and 18 Vexatious Memories through their listed raid groups or FATE regions.","The 18+18 gate is shared by the relic story and is not repeated for every later job.","Accept the job-specific Timeworn Artifact quest.","Collect 15 Timeworn Artifacts from Delubrum Reginae or qualifying Palace of the Dead floor sets.","Use an essence and Lost Actions in Delubrum; an empty holster dramatically slows the run.","Turn in 15 for the Augmented Law's Order weapon and confirm its stat allocation."],
    "https://ffxiv.consolegameswiki.com/wiki/Resistance_Weapons"),
  relic("resistance-stage-blades","resistance-weapons","Resistance: Blade's Finale","Shadowbringers","80",14,
    ["Unlock Zadnor and complete its story through The Dalriada.","Keep the Augmented Law's Order weapon and a second weapon.","Activate every final-memory quest before farming."],
    ["Complete the one-time source-specific collections: 30 Compact Axles, 30 Compact Springs, and 30 each of the four named books through their exact Zadnor sectors or raid alternatives.","Only the matching active quest tracks each material; one source group does not substitute for another.","Accept the final job-specific quest and collect 15 Raw Emotions from The Dalriada, Delubrum Reginae, listed level-70 dungeons, or Heaven-on-High.","Turn in all 15 and confirm final attributes to receive the Blade's weapon.","Finish Regana's replica-unlock dialogue before storing the original.","Additional jobs repeat job-specific stages but not the large one-time collections."],
    "https://ffxiv.consolegameswiki.com/wiki/Resistance_Weapons"),

  relic("manderville-stage-base","manderville-weapons","Manderville: Base Weapon","Endwalker","90",11,
    ["Complete the Hildibrand line through The Imperfect Gentleman.","Complete Endwalker's level-90 MSQ.","Reserve 1,500 Poetics."],
    ["Accept Make It a Manderville in Radz-at-Han.","Buy three Manderium Meteorites for 500 Poetics each from Jubrunnah.","Deliver them on the chosen job to receive the Manderville weapon.","For another job, accept Make Another Manderville and repeat only the material exchange.","Do not buy later materials until their stage quest is unlocked; all four stages use similarly priced bundles."],
    "https://ffxiv.consolegameswiki.com/wiki/Manderville_Weapons"),
  relic("manderville-stage-amazing","manderville-weapons","Manderville: Amazing Weapon","Endwalker","90",12,
    ["Finish Generational Bonding.","Carry the base Manderville weapon.","Reserve 1,500 Poetics."],
    ["Accept Well-oiled.","Buy three Complementary Chondrites for 500 Poetics each.","Unequip the base weapon if the exchange asks and deliver all three.","Receive the Amazing Manderville weapon.","Additional jobs use the repeatable version after their base weapon."],
    "https://ffxiv.consolegameswiki.com/wiki/Manderville_Weapons"),
  relic("manderville-stage-majestic","manderville-weapons","Manderville: Majestic Weapon","Endwalker","90",13,
    ["Finish Not from Around Here.","Carry the Amazing weapon.","Plan selectable attributes."],
    ["Accept A Spirited Reforging.","Buy three Amplifying Achondrites for 500 Poetics each.","Deliver them with the Amazing weapon.","Select attributes for the job's intended use; relic allocations are separate from materia melds.","Confirm and receive the Majestic weapon; use the explicit reallocation option if priorities later change."],
    "https://ffxiv.consolegameswiki.com/wiki/Manderville_Weapons"),
  relic("manderville-stage-mandervillous","manderville-weapons","Manderville: Mandervillous Finale","Endwalker","90",14,
    ["Finish Gentlemen at Heart.","Carry the Majestic weapon.","Reserve the final 1,500 Poetics."],
    ["Accept Resonating with Perfection.","Buy three Cosmic Crystallites for 500 Poetics each.","Deliver them and confirm final attributes.","Receive the Mandervillous weapon and finish completion dialogue.","Unlock and buy desired replicas before storing the original.","The complete cost per job is 6,000 Poetics across four stages."],
    "https://ffxiv.consolegameswiki.com/wiki/Manderville_Weapons"),

  relic("phantom-stage-paste","phantom-weapons","Phantom: Base & Phantom Paste","Dawntrail","100",11,
    ["Complete the level-100 Phantom weapon unlock quests in the Occult Crescent story.","Choose and remain on the requested job.","Keep the stage quest active before entering any duty."],
    ["Accept the job-specific base Phantom weapon quest in the Phantom Village.","Obtain the base weapon through the opening hand-offs and confirm its stage name.","Accept the Phantom Paste enhancement quest.","Run only duties or Crescent sources explicitly listed in the duty objective; an unlisted roulette or unsynced variant does not substitute.","Keep the weapon equipped when the objective or completion text requires it.","Turn in the full Paste requirement and receive the enhanced stage before accepting Demiatma."],
    "https://ffxiv.consolegameswiki.com/wiki/Phantom_Weapons"),
  relic("phantom-stage-demiatma","phantom-weapons","Phantom: Demiatma Stage","Dawntrail","100",12,
    ["Complete the Phantom Paste stage.","Unlock all named qualifying duties.","Separate Horn currency from quest-specific Demiatma drops."],
    ["Accept the Demiatma quest on the target job.","Read the duty list and note each Demiatma group and eligible duty family.","Complete the exact required duties while the quest is active; normal and high-end versions only count when named.","Check counters after the first clear of each route before repeating it.","Turn in complete groups together and retain the evolving weapon.","Repeat jobs require their own active quest and counters even when shared Crescent content is unlocked."],
    "https://ffxiv.consolegameswiki.com/wiki/Phantom_Weapons"),
  relic("phantom-stage-final","phantom-weapons","Phantom: Final 7.55 Enhancements","Dawntrail","100",13,
    ["Complete every previous Phantom stage.","Finish current North Horn/Phantom story gates.","Unlock every duty named by the final two quests."],
    ["Accept the first 7.55 enhancement on the weapon's job.","Collect its named materials only from listed duties and current Crescent sources; Horn currency does not replace a quest drop unless an exchange explicitly says so.","Turn in the first full set and verify the penultimate weapon.","Accept the final enhancement immediately so later clears are tracked.","Complete each final duty/material group, checking its counter after one clear before choosing a farm route.","Turn in on the correct job, confirm attributes if prompted, and finish replica-unlock dialogue.","Shared story unlocks carry to another job, but every job-specific material counter repeats."],
    "https://ffxiv.consolegameswiki.com/wiki/Phantom_Weapons"),
];

const field = (slug: string, parentSlug: string, title: string, expansion: string, level: string, order: number, prep: string[], steps: string[], source: string): BuiltInGuide => fullArticle({
  slug, parentSlug, category: "Field Operation Tier", title,
  summary: "A zone-specific guide covering entry, progression, map routing, encounters, special systems, rewards, death rules, and exit gates.",
  expansion, level, audience: "Combat", imageUrl: "/guides/field-operation-route.svg",
  order, prep, steps, source: [title + " reference", source],
  notes: ["Join a party for contribution and recovery even when objectives can be completed solo.", "Wait for a raise whenever returning would trigger the operation's experience/knowledge penalty."],
});

const FIELD_GUIDES: BuiltInGuide[] = [
  field("field-eureka-anemos","eureka-field-guide","Eureka Anemos: Elemental 1–20","Stormblood","70 / Elemental 1–20",11,
    ["Complete And We Shall Call It Eureka in Rhalgr's Reach.","Repair gear, clear inventory, and understand that elemental level replaces normal level.","Set Magia offensively against a target's weakness or defensively to the target's element."],
    ["Complete Krile's opening investigation and attune the first aetheryte.","Use the weekly Eureka challenge log for early levels; kill enemies near your elemental level in a party to build chains.","Join NM trains after gaining map access. Sync to each FATE and wait for the organizer's pull call.","Complete every level-gated Krile quest; converging-current destinations only function after their stated level.","Attune the other aetherytes when eligible; approaching early does not unlock them.","Farm Anemos/Protean crystals and Pazuzu materials, appraise lockboxes at camp, and finish the level-20 story to open Pagos.","Past the protected early levels, request a raise instead of returning and risking elemental experience loss."],
    "https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/eureka/"),
  field("field-eureka-pagos","eureka-field-guide","Eureka Pagos: Elemental 20–35","Stormblood","70 / Elemental 20–35",12,
    ["Complete Anemos' level-20 story.","Expect one-way cliff drops and unlock northern aetherytes before long routes.","Walk past sleeping dragons; running or mounted movement wakes them."],
    ["Follow Krile's level gates and unlock the kettle.","Use challenge-log objectives, near-level chains, and NMs for elemental experience.","Reach cliff destinations from the correct upper plateau; they cannot be climbed from below.","For Happy Bunnies, finish the FATE and follow the bunny's direction/distance messages to treasure before its timer expires.","Fill the kettle with eligible light and convert it at the Crystal Forge; never leave it capped.","Collect Pagos crystals and Louhi's Ice for the weapon.","Reach elemental 35, finish Krile's objectives, and unlock Pyros."],
    "https://ffxiv.consolegameswiki.com/wiki/The_Forbidden_Land,_Eureka_Pagos"),
  field("field-eureka-pyros","eureka-field-guide","Eureka Pyros: Elemental 35–50","Stormblood","70 / Elemental 35–50",13,
    ["Complete Pagos and carry its weapon for relic progression.","Reserve inventory for logograms and appraised actions.","Prepare a defensive Logos tray before solo travel."],
    ["Unlock Logogram Appraisal, Logos Manipulation, and the action tray.","Acquire logograms from enemies, NMs, bunnies, and lockboxes; appraise them before synthesis.","Combine mnemes into unique Logos actions. Registration count gates weapon and elemental-armor progress, so register new actions instead of hoarding duplicates.","Use offensive actions for trains and defensive/utility actions for travel, raises, and difficult NMs.","Complete all level-gated Krile investigations.","Collect Pyros crystals and Penthesilea's Flame, complete the weapon, and advance elemental armor separately.","Reach 50 and finish the story to open Hydatos."],
    "https://ffxiv.consolegameswiki.com/wiki/The_Forbidden_Land,_Eureka_Pyros"),
  field("field-eureka-hydatos","eureka-field-guide","Eureka Hydatos: Elemental 50–60","Stormblood","70 / Elemental 50–60",14,
    ["Complete Pyros and the relevant Logos registrations.","Bring raise-capable and defensive Logos actions.","Join the zone's NM/Arsenal communication group before Ovni."],
    ["Complete Krile's Hydatos investigation chain while leveling to 60.","Farm Hydatos crystals from NMs and Crystalline Scales from Provenance Watcher.","Continue appraising logograms and meet the registration count for elemental armor.","Defeat Ovni when an Arsenal run is forming; its defeat creates unstable portals.","Do not click an organized group's reserved unstable portal. Stable portals appear later after the support FATE for eligible outside players.","Finish the level-60 story and unlock the Arsenal route.","Upgrade elemental armor and the Hydatos weapon independently; their materials do not substitute."],
    "https://ffxiv.consolegameswiki.com/wiki/The_Forbidden_Land,_Eureka_Hydatos"),
  field("field-eureka-arsenal","eureka-field-guide","Baldesion Arsenal: Entry to Proto Ozma","Stormblood","70 / Elemental 60",15,
    ["Reach elemental 60 and finish Hydatos' story.","Join an organized run; follow its Logos, gear, food, potion, voice/chat, and portal requirements.","Carry the assigned resurrection and utility actions because ordinary raises are restricted."],
    ["Be in the organizer's Hydatos instance before Ovni and follow its portal assignment rules.","Enter only the assigned unstable portal; unclaimed stable portals follow after the support FATE.","Form assigned parties inside and do not cross unexplored floor tiles before trap detection.","Follow calls for Art/Owain, Absolute Virtue support timing, and Proto Ozma platform assignments.","Use remembered/reraise effects according to the group's recovery plan; normal resurrection is unavailable for most deaths.","Outside players complete the support FATE to weaken Absolute Virtue and create stable portals.","Collect Eureka Fragments for Physeos/armor and finish Proto Ozma for the Demi-Ozma reward and clear credit."],
    "https://ffxiv.consolegameswiki.com/wiki/The_Baldesion_Arsenal"),

  field("field-bozja-southern","bozja-field-guide","Bozjan Southern Front: Ranks 1–15","Shadowbringers","80 / Resistance 1–15",11,
    ["Complete Return to Ivalice and Hail to the Queen.","Unlock the Southern Front from Gangos.","Bring a useful essence and actions as soon as fragments unlock."],
    ["Complete the tutorial and earn mettle from skirmishes and critical engagements.","Return to camp for promotion whenever the bar fills; new sectors and story quests are rank-gated.","Appraise forgotten fragments, assign an essence, and place useful Lost Actions in the holster; empty holsters make encounters unnecessarily slow.","Enter critical engagements through the recruitment window. Queue priority and eligibility differ from open-world FATEs.","For a duel invitation, complete its prerequisite CE without taking avoidable damage; merely clearing it is insufficient.","At the story gate, complete Castrum Lacus Litore. Learn the opening split, prisoner rescues, and boss routes before entry.","Reach rank 15 and finish Southern Front story to continue to Delubrum and Zadnor.","Incapacitation costs mettle and returning costs more, but achieved Resistance rank cannot fall."],
    "https://ffxiv.consolegameswiki.com/wiki/Bozjan_Southern_Front"),
  field("field-bozja-castrum","bozja-field-guide","Castrum Lacus Litore: Full Operation","Shadowbringers","80 / Resistance 10+",12,
    ["Reach the required Southern Front story rank.","Equip an essence and damage/utility Lost Actions.","Join when the critical engagement appears and form parties inside."],
    ["Split groups between the upper and lower opening encounters and finish them close together.","Free prisoners promptly; each rescued group improves end rewards.","For Adrammelech, identify elemental pair effects and resolve combined mechanics rather than following only one telegraph.","Use Lost Death or assigned burst only when the group's strategy calls for it.","Complete the Lyon side encounter with its assigned party while the main force continues Dawon.","Finish the final encounter, loot every personal coffer, and complete the Gangos story hand-off.","If farming Loathsome Memories or notes, verify the corresponding relic/note objective before entering."],
    "https://ffxiv.consolegameswiki.com/wiki/Castrum_Lacus_Litore"),
  field("field-bozja-delubrum","bozja-field-guide","Delubrum Reginae: Normal & Savage","Shadowbringers","80 / Resistance 15+",13,
    ["Finish Castrum and the required Save the Queen story.","Unlock normal Delubrum before considering Savage.","Equip an appropriate essence and actions; the duty is not balanced around empty holsters."],
    ["Queue for normal through the Gangos NPC and form parties inside as needed.","Many avoidable attacks apply Twice-come Ruin; a second stack causes Doom. Treat telegraphs as lethal progression.","Follow trap-detection handling and do not run ahead across unexplored floor tiles.","Normal clears award Timeworn Artifacts and story/relic items only while their quests are active.","Complete normal and its story before unlocking Zadnor and Savage prerequisites.","For Savage, join an organized 48-player group and meet its gear, action, reraise, consumable, and communication requirements.","Savage resurrection is restricted; follow assigned calls, splits, and recovery plans rather than improvising."],
    "https://ffxiv.consolegameswiki.com/wiki/Delubrum_Reginae"),
  field("field-bozja-zadnor","bozja-field-guide","Zadnor: Ranks 16–25 & Honors","Shadowbringers","80 / Resistance 16–25",14,
    ["Finish Delubrum story and unlock Zadnor.","Carry useful essences/actions and leave inventory room for fragments and lockboxes.","Activate the exact final Resistance quests before farming their memories."],
    ["Advance through three sectors as rank and story allow.","Complete skirmishes and CEs for mettle; use their chains to target specific field notes.","Farm the six final relic material groups only in the exact sector/raid source named by each active quest.","Complete duel prerequisites without avoidable damage when pursuing duel notes.","At rank 25, unlock Proofs of Mettle and spend them on honors for permanent field-operation bonuses.","Complete The Dalriada, including the opening split and its rescue/side objectives.","Use the Field Record menu to identify missing notes and target their exact skirmish, CE, duel, or operation source.","Continue Dalriada and CEs for Raw Emotions only with the final weapon quest active."],
    "https://ffxiv.consolegameswiki.com/wiki/Zadnor"),
  field("field-bozja-dalriada","bozja-field-guide","The Dalriada: Full Operation","Shadowbringers","80 / Resistance 25",15,
    ["Reach rank 25 and finish Zadnor's entry story.","Equip a strong essence and role-appropriate Lost Actions.","Join the operation recruitment and form balanced parties."],
    ["Assign a small capable group to the upper route while the main force handles the lower opening; synchronize completion.","Complete the prisoner/rescue and side objectives before their timers expire to improve rewards.","Use dispels, interrupts, mitigation, and burst actions according to the encounter and party composition.","For the split and corridor sections, follow map markers and avoid abandoning slower parties.","Resolve Diablo Armament mechanics with the operation's agreed positioning rather than scattering.","Loot all personal coffers and finish the story hand-off in Gangos.","When farming Raw Emotions, verify the correct job's active quest before the clear."],
    "https://ffxiv.consolegameswiki.com/wiki/The_Dalriada"),

  field("field-occult-south","occult-crescent-guide","Occult Crescent South Horn: Knowledge 1–20","Dawntrail","100 / Knowledge 1–20",11,
    ["Complete One Last Hurrah and enter through the expedition NPC.","Finish New Job, Old Tricks to unlock phantom jobs.","Choose a phantom job that supplies missing damage, sustain, support, or traversal."],
    ["Complete Ketenramm's opening investigations and the phantom-job tutorial.","Earn knowledge from ordinary enemies, encounters, challenge objectives, and story tasks.","Level phantom jobs separately by using their actions; unlocking one is not mastery.","Watch weather and map announcements for special encounters and access conditions.","Collect and spend South Horn currency at its own vendors; inspect weapon, gear, record, mount, and minion gates before buying glamour.","Complete records as their objectives become available; record completion and phantom mastery are separate tracks.","Advance every story and knowledge gate to the South Horn climax and North Horn continuation.","After protected early levels, request a raise rather than returning when knowledge loss applies."],
    "https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/occult_crescent/"),
  field("field-occult-north","occult-crescent-guide","Occult Crescent North Horn: Knowledge 21–40","Dawntrail","100 / Knowledge 21–40",12,
    ["Complete South Horn story and North Horn's entry quest.","Carry mastered phantom options for solo travel and organized encounters.","Treat North and South Horn vendor currencies separately."],
    ["Follow North Horn story objectives and unlock local travel points at their knowledge gates.","Build knowledge through local enemies and encounters rather than under-level South Horn farming.","Unlock and train newly available phantom progression; update action loadouts for North Horn mechanics.","Track special weather and encounter chains and arrive before participation locks.","Complete North Horn records, including objectives requiring a named encounter, weather state, or phantom action.","Spend currency only after checking current weapon-stage and collection requirements.","Reach knowledge 40 and finish current story before its end operations.","Keep raise/survival options ready; knowledge loss makes reckless returns expensive."],
    "https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/occult_crescent/"),
  field("field-occult-phantom-jobs","occult-crescent-guide","Phantom Jobs, Mastery & Records","Dawntrail","100",13,
    ["Unlock New Job, Old Tricks.","Open the phantom-job menu and read each action, passive, and mastery objective.","Carry a base-job loadout that complements the phantom role."],
    ["Unlock the starting phantom jobs through their quests or required items.","Assign one phantom job before combat and place its actions on the duty-action interface.","Earn phantom experience from eligible Crescent activities; base-job experience and knowledge do not replace phantom experience.","Complete mastery objectives and unlock follow-on phantom options as the menu specifies.","Build separate solo, NM/encounter, and tower loadouts; one high-damage setup cannot cover raises, cleanses, mitigation, and traversal.","Open the record list and target each named enemy, encounter, weather condition, location, or phantom action.","Claim record rewards and check vendors for items gated by completion count.","For towers, use exactly the phantom assignment given by the organizer."],
    "https://ffxiv.consolegameswiki.com/wiki/Occult_Crescent"),
  field("field-occult-towers","occult-crescent-guide","Forked Towers: Blood, Magic & Extreme","Dawntrail","100",14,
    ["Complete the applicable Horn story and tower prerequisites.","Join an organized group and meet its base-job, phantom-job, action, food, potion, and communication rules.","Repair, clear inventory, and carry only permitted recovery consumables."],
    ["Confirm the tower variant; Blood, Magic, and Extreme have different prerequisites and preparation.","Be in the correct instance before the trigger. Capacity and portals do not work like Duty Finder.","Assign parties and phantom roles before entry; missing utility may be impossible to repair inside.","Follow portal claims. Do not consume a reserved portal merely because it is clickable.","Treat resurrection as restricted and use assigned reraises/recovery actions only as directed.","Follow calls for splits, interrupts, mitigation, and variant-specific mechanics.","Verify any weapon or record quest is active before expecting credit and follow the group's loot rules.","For Extreme, meet prior-clear and loadout requirements; it is not a blind-progression substitute for the normal tower."],
    "https://ffxiv.consolegameswiki.com/wiki/Occult_Crescent"),
];

const tool = (slug: string, title: string, expansion: string, level: string, order: number, prep: string[], steps: string[], source: string): BuiltInGuide => fullArticle({
  slug, parentSlug: "relic-tools", category: "Profession Relic Tier", title,
  summary: "A level-specific crafter/gatherer equipment guide with every unlock, class route, rating rule, exchange, and repeat condition.",
  expansion, level, audience: "Crafting & Gathering", imageUrl: "/guides/relic-stage-route.svg",
  order, prep, steps, source: [title + " reference", source],
  notes: ["Quest tool progress is class-specific even when the storyline and vendors are shared.", "Use Trial Synthesis or one test gather/catch before consuming a full batch of limited materials."],
});

const TOOL_GUIDES: BuiltInGuide[] = [
  tool("tools-blessed-level-60","Level 60 Blessed Tools","Heavensward","60",10,
    ["Reach the achievement's required class level.","Open Achievements → Items → Crafting/Gathering and pin the exact tool objective.","Unlock the recipes, gathering logs, or fishing logs counted by that achievement."],
    ["For each crafter, complete the required number of unique recipes in that class's Crafting Log; repeated crafts of one recipe do not increase unique-recipe achievements.","For miner and botanist, discover the required unique items in the Gathering Log. Hidden, timed, and folklore items count only after successful collection.","For fisher, record the required unique fish in the Fishing Log; catching duplicates does not replace an undiscovered entry.","Claim prerequisite achievement tiers as they complete; some final achievements remain hidden until earlier tiers are claimed.","Claim the Blessed tool directly from the achievement reward interface.","Repeat for each class. Blessed tools are achievement glamour/stat items, not an evolving shared quest line.","Use search/filter in the logs to locate blank entries and verify regional folklore or bait requirements."],
    "https://ffxiv.consolegameswiki.com/wiki/Blessed_Tools"),
  tool("tools-skysteel-level-80","Level 80 Skysteel Tools","Shadowbringers","80",20,
    ["Unlock the Firmament and complete Mislaid Plans in Ishgard.","Buy each prototype from Denys; the first is supplied by the quest.","Equip the Skysteel tool while producing every required quest item."],
    ["Crafters buy Oddly Specific materials from the Scrip Exchange and craft the Skysteel recipes under Special Recipes. Meet the stage's displayed quality/collectability.","Miner and botanist gather the named Skysteel items plus hidden/high-quality companion items in the specified Shadowbringers zones with the tool equipped.","Fisher uses the named bait and fishing holes and enables Collect when a rating is shown.","Turn items in to Denys for Skysteel +1, Dragonsung, Augmented Dragonsung, Skysung, and final Skybuilders' stages in order.","Later expert-recipe stages require high collectability, not ordinary HQ. Practice before consuming limited materials.","Repeat every class separately; story access is shared, tools and item sets are not."],
    "https://ffxiv.consolegameswiki.com/wiki/Skysteel_Tools"),
  tool("tools-resplendent-level-80","Level 80 Resplendent Tools","Shadowbringers","80",21,
    ["Reach level 80 on the selected crafter and unlock required Master Recipe books.","Equip endgame Shadowbringers crafting gear with enough CP for expert recipes.","Practice each expert recipe with Trial Synthesis."],
    ["Accept the Resplendent tool request for one crafting class in Eulmore.","Craft the first component tier at the required collectability; lower bands yield fewer exchange components.","Exchange accepted crafts for the next-tier material.","Repeat through the second and third expert-recipe component tiers.","Hand in the final quantity for that class's Resplendent tool.","Repeat independently for other crafters. Gatherers have Blessed achievements but no equivalent Resplendent expert-craft chain.","Keep the tool as achievement glamour; this route is separate from Skysteel quest tools."],
    "https://ffxiv.consolegameswiki.com/wiki/Resplendent_Tools"),
  tool("tools-splendorous-level-90","Level 90 Splendorous Tools","Endwalker","90",30,
    ["Complete Endwalker and The Crystalline Mean.","Unlock An Original Improvement in the Crystarium.","Buy the base Splendorous tool and equip it for all stage items."],
    ["Complete the base exchange for the selected class.","Crafters buy stage materials with scrips and craft collectables under Special Recipes; rating determines component yield.","Miner and botanist gather collectable stage items plus hidden support materials at the named nodes.","Fisher uses the specified bait, Collect, and fishing holes; weak/strong bites correspond to different targets.","Exchange components through Augmented Splendorous, Crystalline, Chora-Zoi's Crystalline, and final Lodestar stages.","Each class has distinct recipes, nodes, or fish even though the story structure repeats.","The finished tool's special effect remains useful for its intended production rules; keep it after stat replacement."],
    "https://ffxiv.consolegameswiki.com/wiki/Splendorous_Tools"),
  tool("tools-cosmic-level-100","Level 100 Cosmic Tools","Dawntrail","100",40,
    ["Reach level 100 on the selected crafter or gatherer and unlock Cosmic Exploration.","Complete the opening Sinus Ardorum expedition quests and receive the class's cosmic tool.","Read every stellar mission's time, weather, score, class, and item conditions before deployment."],
    ["Equip the cosmic tool and choose a stellar mission appropriate to the class and gear.","Complete its objective before the timer expires. Crafting missions score recipe output/quality; gathering missions score exact items and mission actions.","Claim mission credit; making similar normal items outside the active mission does not grant tool research.","Use stellar projects, red alerts, mech operations, and special weather missions when their rewards advance the current requirement.","Spend enhancement points only after reviewing the current stage's selectable attributes and cap.","Complete class-specific research requests and turn-ins through every released stage.","Repeat per class. Expedition development is shared, but tool research and missions remain class-specific.","At later destinations, verify the mission belongs to the current tool stage; an old-zone mission may pay general currency without the required research item."],
    "https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/cosmic_exploration/"),
  tool("tools-profession-gear-caps","Crafter & Gatherer Body Gear by Level Cap","Multiple","50–100",50,
    ["Unlock each expansion's Scrip Exchange.","Separate artifact sets, shared scrip sets, crafted sets, achievement tools, and relic tools.","Compare Craftsmanship/Control/CP or Gathering/Perception/GP breakpoints—not item level alone."],
    ["Level 50: class artifact/Supra/Lucis-era pieces are historical progression; Ironworks profession gear is the practical scrip bridge.","Level 60: augmented scrip or crafted Ironworks profession sets support Blessed achievements. Blessed is a tool reward, not body relic armor.","Level 70: Handking/Landking and crafted Onishi/Yamashi-era sets bridge to Shadowbringers; there is no combat-style profession relic armor quest.","Level 80: Handsaint/Landsaint and crafted Aesthete sets support Skysteel/Resplendent work.","Level 90: Afflatus and crafted Indagator-era sets support Splendorous tools; augment only where an NPC shows an explicit exchange.","Level 100: current scrip and crafted profession gear support Cosmic tools. Melded crafted gear is preferred when expert-mission breakpoints exceed scrip gear.","Replace main hand and body first, then off hand and armor, then accessories; CP/GP thresholds can make a melded lower-item-level piece better.","No unified crafter/gatherer body-relic line exists. Special body sets are artifact, scrip, crafted, achievement, or content rewards; the evolving relic-like projects are tools."],
    "https://ffxiv.consolegameswiki.com/wiki/Leveling_Gear_Guide"),
];

export const EXPANDED_GUIDES: BuiltInGuide[] = [
  societyTier("societies-level-50","Level 50 and 50–60 Allied Societies","1–60","A Realm Reborn / Heavensward",["[[society-amaljaa|Amalj'aa — level 43 combat]]","[[society-sylph|Sylphs — level 42 combat]]","[[society-kobold|Kobolds — level 41 combat]]","[[society-sahagin|Sahagin — level 44 combat]]","[[society-ixal|Ixal — level 1+ crafting]]","[[society-vanu-vanu|Vanu Vanu — level 50–60 combat]]","[[society-vath|Vath — level 50–60 combat]]","[[society-moogle|Moogle — level 50–60 crafting]]"],10),
  societyTier("societies-level-60","Level 60–70 Allied Societies","60–70","Stormblood",["[[society-kojin|Kojin — combat]]","[[society-ananta|Ananta — combat]]","[[society-namazu-crafting|Namazu — crafting/gathering]]"],20),
  societyTier("societies-level-70","Level 70–80 Allied Societies","70–80","Shadowbringers",["[[society-pixie|Pixies — combat]]","[[society-dwarf|Dwarves — crafting]]","[[society-qitari|Qitari — gathering]]"],30),
  societyTier("societies-level-80","Level 80–90 Allied Societies","80–90","Endwalker",["[[society-arkasodara|Arkasodara — combat]]","[[society-loporrit|Loporrits — crafting]]","[[society-omicron|Omicron — gathering]]"],40),
  societyTier("societies-level-90","Level 90–100 Allied Societies","90–100","Dawntrail",["[[society-pelupelu|Pelupelu — combat]]","[[society-yok-huy|Yok Huy — crafting]]","[[society-mamool-ja|Mamool Ja — gathering]]"],50),
  collectTier("collectables-tier-50","Level 50–60: Collectables, Scrips & Folklore","50–60","ARR / Heavensward","Foundation and Idyllshire","Master Recipes I–IV; Folklore: Coerthas, Dravania, Abalathia",10),
  collectTier("collectables-tier-60","Level 60–70: Collectables, Scrips & Folklore","60–70","Stormblood","Rhalgr's Reach and Kugane","Master Recipes V–VI; Folklore: Gyr Abania and Othard",20),
  collectTier("collectables-tier-70","Level 70–80: Collectables, Scrips & Folklore","70–80","Shadowbringers","Eulmore and Crystarium","Master Recipes VII–VIII; Folklore: Norvrandt",30),
  collectTier("collectables-tier-80","Level 80–90: Collectables, Scrips & Folklore","80–90","Endwalker","Radz-at-Han and Old Sharlayan","Master Recipes IX–X; Folklore: Ilsabard/Northern Empty, Sea of Stars, World Unsundered",40),
  collectTier("collectables-tier-90","Level 90–100: Collectables, Scrips & Folklore","90–100","Dawntrail","Solution Nine and Tuliyollal","Master Recipes XI–XII/current; Folklore: Yok Tural, Xak Tural, Alexandria",50),
  customTier("custom-deliveries-tier-60","Level 60 Custom Deliveries","55–70","Heavensward / Stormblood",["[[delivery-zhloe|Zhloe]]","[[delivery-mnaago|M'naago]]","[[delivery-kurenai|Kurenai]]","[[delivery-adkiragh|Adkiragh]]"],10),
  customTier("custom-deliveries-tier-70","Level 70 Custom Deliveries","70–80","Shadowbringers",["[[delivery-kai-shirr|Kai-Shirr]]","[[delivery-ehll-tou|Ehll Tou]]","[[delivery-charlemend|Charlemend]]"],20),
  customTier("custom-deliveries-tier-80","Level 80 Custom Deliveries","80–90","Endwalker",["[[delivery-ameliance|Ameliance]]","[[delivery-anden|Anden]]","[[delivery-margrat|Margrat]]"],30),
  customTier("custom-deliveries-tier-90","Level 90 Custom Deliveries","90–100","Dawntrail",["[[delivery-nitowikwe|Nitowikwe]]","[[delivery-tiisol-ja|Tiisol Ja]]"],40),
  ...CLIENTS.map(clientArticle),
  ...RELIC_GUIDES,
  ...FIELD_GUIDES,
  ...TOOL_GUIDES,
];
