import type { Client, PoolClient } from "pg";
import { ensurePrivacyTables, privacyFingerprint } from "./privacy";
import { pollVoterKey } from "./polls/identity";
import { giveawayVoterKey } from "./giveaways/identity";
type Queryable=Pick<Client|PoolClient,"query">;
export const personalDataTargets=[
  ["portal_alt_character_claims","discord_user_id"],["portal_alt_character_limits","discord_user_id"],["portal_alt_character_links","discord_user_id"],["portal_discord_event_drafts","discord_user_id"],
  ["portal_discord_links","discord_user_id"],["portal_discord_member_snapshots","discord_user_id"],["portal_discord_guest_access","discord_user_id"],["portal_discord_roster_review_decisions","discord_user_id"],["portal_discord_action_queue","discord_user_id"],["portal_discord_audit_log","discord_user_id"],["portal_command_diagnostics","discord_user_id"],["portal_member_availability_profiles","discord_user_id"],["portal_member_availability_windows","discord_user_id"],["portal_event_plan_interest","discord_user_id"],["portal_event_plan_availability_windows","discord_user_id"],["portal_event_plan_availability_drafts","discord_user_id"],["portal_member_preferences","discord_user_id"],["portal_crafter_profiles","discord_user_id"],["portal_community_gallery_posts","discord_user_id"],["portal_giveaway_entries","discord_user_id"],["portal_giveaway_submissions","discord_user_id"],["portal_giveaway_votes","voter_discord_user_id"],["portal_crafting_contributions","contributor_discord_user_id"],["portal_crafting_claims","claimant_discord_user_id"],["portal_crafting_activity","actor_discord_user_id"]
] as const;
export const characterDataTargets=[
  ["portal_character_mounts","character_id"],["portal_character_minions","character_id"],["portal_character_achievements","character_id"],["portal_character_achievement_sync_state","character_id"],["portal_mount_acquisitions","character_id"],["portal_character_rename_history","character_id"],["portal_character_fc_rank_history","character_id"],["portal_discord_event_signups","character_id"],["portal_crafting_contributions","contributor_character_id"],["portal_crafting_claims","claimant_character_id"]
] as const;
async function exists(db:Queryable,table:string,column:string){return Boolean((await db.query(`select exists(select 1 from information_schema.columns where table_schema='public' and table_name=$1 and column_name=$2) ok`,[table,column])).rows[0]?.ok)}
async function anonymizeSharedCraftingAttribution(db:Queryable,subject:{discordUserId:string;characterId:number|null},characterIds:number[]){
  await deidentifyPollParticipation(db,subject.discordUserId);
  await deidentifyGiveawayParticipation(db,subject.discordUserId);
  if(await exists(db,"portal_crafting_projects","lead_character_id")){
    await db.query(`update portal_crafting_projects set lead_character_id=null,created_by_character_id=null,created_by_discord_user_id=null where lead_character_id=any($1::bigint[]) or created_by_character_id=any($1::bigint[]) or created_by_discord_user_id=$2`,[characterIds,subject.discordUserId]);
  }
  if(await exists(db,"portal_crafting_project_discord_posts","posted_by_character_id")){
    await db.query(`update portal_crafting_project_discord_posts set posted_by_character_id=null,posted_by_discord_user_id=null where posted_by_character_id=any($1::bigint[]) or posted_by_discord_user_id=$2`,[characterIds,subject.discordUserId]);
  }
  if(await exists(db,"portal_event_plans","created_by_discord_user_id")){
    await db.query(`update portal_event_plans set created_by_discord_user_id=null,created_by_character_id=null,created_by='Deleted member',updated_at=now() where created_by_discord_user_id=$1 or created_by_character_id=any($2::bigint[])`,[subject.discordUserId,characterIds]);
  }
}
async function subjectAnchorCharacterId(db:Queryable,discordUserId:string){if(!await exists(db,"portal_discord_links","discord_user_id"))return null;const row=(await db.query(`select character_id::int from portal_discord_links where discord_user_id=$1 limit 1`,[discordUserId])).rows[0];return row?.character_id?Number(row.character_id):null;}
async function subjectCharacterIds(db:Queryable,subject:{discordUserId:string;characterId:number|null}){const ids=new Set<number>();const anchorId=await subjectAnchorCharacterId(db,subject.discordUserId);if(anchorId)ids.add(anchorId);if(subject.characterId)ids.add(subject.characterId);if(await exists(db,"portal_alt_character_links","discord_user_id")){const rows=(await db.query(`select character_id::int from portal_alt_character_links where discord_user_id=$1`,[subject.discordUserId])).rows;for(const row of rows)ids.add(Number(row.character_id));}return [...ids];}
async function subjectPollKeys(db:Queryable,discordUserId:string){if(!await exists(db,"portal_polls","id"))return[] as string[];return(await db.query(`select id::int from portal_polls`)).rows.map(row=>pollVoterKey(Number(row.id),discordUserId));}
async function deidentifyPollParticipation(db:Queryable,discordUserId:string){if(!await exists(db,"portal_poll_ballots","voter_key"))return;const keys=await subjectPollKeys(db,discordUserId);if(!keys.length)return;await db.query(`delete from portal_poll_ballots b using portal_polls p where b.poll_id=p.id and p.status in ('draft','scheduled','open','awaiting_tie') and(b.voter_discord_user_id=$1 or b.voter_key=any($2::text[]))`,[discordUserId,keys]);await db.query(`update portal_poll_ballots b set voter_key='deidentified-'||b.id||'-'||md5(random()::text||clock_timestamp()::text),voter_discord_user_id=null,voter_discord_ciphertext=null,voter_character_id=null,voter_label='Deleted member',updated_at=now() from portal_polls p where b.poll_id=p.id and p.status in ('closed','cancelled') and(b.voter_discord_user_id=$1 or b.voter_key=any($2::text[]))`,[discordUserId,keys]);if(await exists(db,"portal_poll_audit","actor_discord_user_id"))await db.query(`update portal_poll_audit set actor_discord_user_id=null,actor_character_id=null,actor_label='Deleted member',details=details-'discordUserId'-'characterId' where actor_discord_user_id=$1`,[discordUserId]);}
async function subjectGiveawayKeys(db:Queryable,discordUserId:string){if(!await exists(db,"portal_giveaways","id"))return[] as string[];return(await db.query(`select id::int from portal_giveaways`)).rows.map(row=>giveawayVoterKey(Number(row.id),discordUserId));}
async function deidentifyGiveawayParticipation(db:Queryable,discordUserId:string){if(!await exists(db,"portal_giveaway_votes","voter_key"))return;const keys=await subjectGiveawayKeys(db,discordUserId);if(!keys.length)return;await db.query(`delete from portal_giveaway_votes v using portal_giveaways g where v.giveaway_id=g.id and g.status in ('draft','scheduled','open','submissions_open','submissions_closed','voting_open','voting_closed') and(v.voter_discord_user_id=$1 or v.voter_key=any($2::text[]))`,[discordUserId,keys]);await db.query(`update portal_giveaway_votes v set voter_key='deidentified-'||v.id||'-'||md5(random()::text||clock_timestamp()::text),voter_discord_user_id=null,voter_discord_ciphertext=null,voter_character_id=null,voter_label='Deleted member',updated_at=now() from portal_giveaways g where v.giveaway_id=g.id and g.status in ('awaiting_claim','completed','cancelled','no_eligible_entries') and(v.voter_discord_user_id=$1 or v.voter_key=any($2::text[]))`,[discordUserId,keys]);}
export async function resolvePrivacySubject(db:Queryable,input:string){const value=input.trim();let row;if(/^\d{15,22}$/.test(value)){row=(await db.query(`select dl.discord_user_id,dl.character_id,c.character_name from portal_discord_links dl left join portal_characters c on c.id=dl.character_id where dl.discord_user_id=$1 limit 1`,[value])).rows[0];return {discordUserId:value,characterId:row?.character_id?Number(row.character_id):null,label:row?.character_name||value};}const result=await db.query(`select dl.discord_user_id,dl.character_id,c.character_name from portal_discord_links dl join portal_characters c on c.id=dl.character_id where lower(c.character_name)=lower($1) order by dl.updated_at desc limit 2`,[value]);if(result.rowCount!==1)throw new Error(result.rowCount?"More than one linked character matched. Search by Discord user ID.":"No linked Discord account matched that character name.");row=result.rows[0];return {discordUserId:String(row.discord_user_id),characterId:Number(row.character_id),label:String(row.character_name)};}
export async function inspectPrivacySubject(db:Queryable,subject:{discordUserId:string;characterId:number|null;label:string},includeRows=false){const records:Record<string,unknown>= {};for(const [table,column] of personalDataTargets){if(!await exists(db,table,column))continue;const result=await db.query(`select * from ${table} where ${column}=$1 limit 1000`,[subject.discordUserId]);records[table]=includeRows?result.rows:result.rowCount;}const pollKeys=await subjectPollKeys(db,subject.discordUserId);if(pollKeys.length&&await exists(db,"portal_poll_ballots","voter_key")){const result=await db.query(`select b.*,coalesce(json_agg(json_build_object('choiceId',bc.choice_id,'rank',bc.rank_choice)) filter(where bc.choice_id is not null),'[]'::json) selections from portal_poll_ballots b left join portal_poll_ballot_choices bc on bc.ballot_id=b.id where b.voter_discord_user_id=$1 or b.voter_key=any($2::text[]) group by b.id limit 1000`,[subject.discordUserId,pollKeys]);records.portal_poll_ballots=includeRows?result.rows:result.rowCount;}const giveawayKeys=await subjectGiveawayKeys(db,subject.discordUserId);if(giveawayKeys.length&&await exists(db,"portal_giveaway_votes","voter_key")){const result=await db.query(`select * from portal_giveaway_votes where voter_discord_user_id=$1 or voter_key=any($2::text[]) limit 1000`,[subject.discordUserId,giveawayKeys]);records.portal_giveaway_votes=includeRows?result.rows:result.rowCount;}const characterIds=await subjectCharacterIds(db,subject);if(characterIds.length){if(await exists(db,"portal_characters","id")){const result=await db.query(`select * from portal_characters where id=any($1::bigint[]) limit 1000`,[characterIds]);records.portal_characters=includeRows?result.rows:result.rowCount;}for(const [table,column] of characterDataTargets){if(!await exists(db,table,column))continue;const result=await db.query(`select * from ${table} where ${column}=any($1::bigint[]) limit 1000`,[characterIds]);records[table]=includeRows?result.rows:result.rowCount;}}return records;}
export async function minimizePrivacySubject(db:Queryable,subject:{discordUserId:string;characterId:number|null;label:string},requestedBy:string){await ensurePrivacyTables(db);await db.query("begin");try{const anchorId=await subjectAnchorCharacterId(db,subject.discordUserId);const allCharacterIds=await subjectCharacterIds(db,subject);const additionalIds=allCharacterIds.filter((id)=>id!==anchorId);const before=await inspectPrivacySubject(db,subject,false);const keepPersonal=new Set(["portal_discord_links"]);await anonymizeSharedCraftingAttribution(db,subject,allCharacterIds);for(const characterId of allCharacterIds)for(const [table,column] of [...characterDataTargets].reverse()){if(await exists(db,table,column))await db.query(`delete from ${table} where ${column}=$1`,[characterId]);}for(const [table,column] of [...personalDataTargets].reverse()){if(keepPersonal.has(table))continue;if(await exists(db,table,column))await db.query(`delete from ${table} where ${column}=$1`,[subject.discordUserId]);}await db.query(`update portal_discord_links set discord_username=null,discord_global_name=null,discord_nickname=null,discord_display_name=null,privacy_mode='verification_only',updated_at=now() where discord_user_id=$1`,[subject.discordUserId]);if(anchorId)await db.query(`update portal_characters set authentik_email=null,portrait_url=null,avatar_url=null,portrait_synced_at=null,notes=null,mount_win_notifications_enabled=false,sync_status='privacy_minimized',updated_at=now() where id=$1`,[anchorId]);if(additionalIds.length)await db.query(`update portal_characters set display_name='Minimized linked character',character_name='Minimized linked character',world='Removed',lodestone_character_id=null,ffxiv_collect_character_id=null,authentik_email=null,portrait_url=null,avatar_url=null,portrait_synced_at=null,notes=null,active=false,mount_win_notifications_enabled=false,fc_membership_status='privacy_minimized',sync_status='privacy_minimized',privacy_suppressed=true,updated_at=now() where id=any($1::bigint[])`,[additionalIds]);const fp=privacyFingerprint("discord",subject.discordUserId);const request=(await db.query(`insert into portal_privacy_requests(subject_fingerprint,subject_label,request_type,status,requested_by,request_note,result_summary,completed_at) values($1,'Verification-only member','erasure','completed',$2,'Member selected verification-only data minimization',$3::jsonb,now()) returning id`,[fp,requestedBy,JSON.stringify({removed:before,retained:"Minimal Discord-character-FC verification link and current membership status; shared crafting records retain no member attribution"})])).rows[0];await db.query("commit");return {requestId:Number(request.id),removed:before};}catch(error){await db.query("rollback");throw error;}}
export async function erasePrivacySubject(db:Queryable,subject:{discordUserId:string;characterId:number|null;label:string},requestedBy:string,note:string){await ensurePrivacyTables(db);const configuredAdmins=String(process.env.PORTAL_ADMIN_DISCORD_IDS||"").split(",").map((value)=>value.trim()).filter(Boolean);const primaryAdminId=String(process.env.PORTAL_PRIMARY_ADMIN_DISCORD_ID||configuredAdmins[0]||"").trim();if(subject.discordUserId===primaryAdminId)throw new Error("The primary portal officer cannot be opted out. Transfer the primary-officer configuration first.");await db.query("begin");try{const allCharacterIds=await subjectCharacterIds(db,subject);const before=await inspectPrivacySubject(db,subject,false);const character=subject.characterId?(await db.query(`select lodestone_character_id from portal_characters where id=$1`,[subject.characterId])).rows[0]:null;const discordFingerprint=privacyFingerprint("discord",subject.discordUserId);const lodestoneFingerprint=character?.lodestone_character_id?privacyFingerprint("lodestone",String(character.lodestone_character_id)):null;const adminRow=await db.query(`select value from portal_settings where key='additionalAdminDiscordIds' limit 1`);const remainingAdmins=String(adminRow.rows[0]?.value||"").split(",").map((value)=>value.trim()).filter((value)=>value&&value!==subject.discordUserId);await db.query(`insert into portal_settings(key,value,updated_at) values('additionalAdminDiscordIds',$1,now()) on conflict(key) do update set value=excluded.value,updated_at=now()`,[remainingAdmins.join(",")]);await db.query(`insert into portal_privacy_suppressions(discord_fingerprint,lodestone_fingerprint,status,requested_by_kind,requested_at,opted_back_in_at) values($1,$2,'active',$3,now(),null) on conflict(discord_fingerprint) do update set lodestone_fingerprint=excluded.lodestone_fingerprint,status='active',requested_by_kind=excluded.requested_by_kind,requested_at=now(),opted_back_in_at=null`,[discordFingerprint,lodestoneFingerprint,requestedBy==="member_self_service"?"member":"officer"]);if(await exists(db,"portal_discord_action_queue","discord_user_id")){await db.query(`delete from portal_discord_action_queue where discord_user_id=$1`,[subject.discordUserId]);}
    const suppressedCharacters=allCharacterIds.length?(await db.query(`select lodestone_character_id from portal_characters where id=any($1::bigint[]) and lodestone_character_id is not null`,[allCharacterIds])).rows:[];
    for(const suppressedCharacter of suppressedCharacters)await db.query(`insert into portal_privacy_suppressed_characters(discord_fingerprint,lodestone_fingerprint) values($1,$2) on conflict do nothing`,[discordFingerprint,privacyFingerprint("lodestone",String(suppressedCharacter.lodestone_character_id))]);
    if(await exists(db,"portal_giveaway_audit","actor_discord_user_id"))await db.query(`update portal_giveaway_audit set actor_discord_user_id=null,actor_character_id=null,actor_label='Deleted member',details=details-'discordUserId'-'characterId' where actor_discord_user_id=$1 or actor_character_id=any($2::bigint[])`,[subject.discordUserId,allCharacterIds]);
    if(allCharacterIds.length&&await exists(db,"portal_giveaway_results","character_id"))await db.query(`update portal_giveaway_results set character_name_snapshot='Deleted member' where character_id=any($1::bigint[])`,[allCharacterIds]);
    if(await exists(db,"portal_discord_event_audit_log","changed_by"))await db.query(`update portal_discord_event_audit_log set changed_by='Deleted member' where changed_by=$1`,[subject.discordUserId]);
    await anonymizeSharedCraftingAttribution(db,subject,allCharacterIds);
    for(const characterId of allCharacterIds)for(const [table,column] of [...characterDataTargets].reverse()){if(await exists(db,table,column))await db.query(`delete from ${table} where ${column}=$1`,[characterId]);}
    for(const [table,column] of [...personalDataTargets].reverse()){if(table==="portal_discord_action_queue")continue;if(await exists(db,table,column))await db.query(`delete from ${table} where ${column}=$1`,[subject.discordUserId]);}
    if(allCharacterIds.length)await db.query(`update portal_characters set display_name='Opted-out member',character_name='Opted-out member',world='Suppressed',lodestone_character_id=null,ffxiv_collect_character_id=null,authentik_email=null,portrait_url=null,avatar_url=null,portrait_synced_at=null,role='Former Member',fc_rank_name=null,notes=null,active=false,mount_win_notifications_enabled=false,fc_membership_status='privacy_opt_out',sync_status='privacy_opt_out',privacy_suppressed=true,updated_at=now() where id=any($1::bigint[])`,[allCharacterIds]);
    if(await exists(db,"portal_discord_action_queue","discord_user_id"))await db.query(`insert into portal_discord_action_queue(discord_user_id,action_type,action_payload,status,requested_by,requested_at,updated_at) values($1,'privacy_full_opt_out','{}'::jsonb,'pending','member privacy request',now(),now())`,[subject.discordUserId]);
    await db.query(`update portal_privacy_requests set subject_discord_user_id=null,subject_character_id=null,subject_label='Deleted member',subject_fingerprint=$2 where subject_discord_user_id=$1 or subject_character_id=any($3::bigint[])`,[subject.discordUserId,discordFingerprint,allCharacterIds]);
    const request=(await db.query(`insert into portal_privacy_requests(subject_fingerprint,subject_label,request_type,status,requested_by,request_note,result_summary,completed_at) values($1,'Deleted member','erasure','completed',$2,$3,$4::jsonb,now()) returning id`,[discordFingerprint,requestedBy,note,JSON.stringify({removed:before,retained:"One-way suppression fingerprints, a non-identifying request receipt, deidentified shared crafting records, and deidentified records required for integrity"})])).rows[0];await db.query("commit");return {requestId:Number(request.id),removed:before};}catch(error){await db.query("rollback");throw error;}}
