import { NextResponse } from "next/server";
import { Client } from "pg";
import { auth } from "../../../auth";
import { attachPlanAvailability, attachSavedAvailability, cancelEventPlan, createEventPlan, ensureEventPlanningTables, getEventPlanDashboard, updateEventPlan, withdrawEventPlanInterest, type EventPlanInput } from "../../../lib/event-plans";
import type { AvailabilityWindow } from "../../../lib/availability";
import { getAvailableDiscordPostChannels } from "../../../lib/discord-channel-access";

type Session={user?:{discordUserId?:string|null;groups?:string[]}}|null;
const id=(session:Session)=>String(session?.user?.discordUserId||"").trim();
const officer=(session:Session)=>Boolean(session?.user?.groups?.some(group=>group==="Admins"||group==="Guild Officers"));
async function db(){const client=new Client({connectionString:process.env.DATABASE_URL});await client.connect();return client;}
function fail(error:unknown,status=400){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status});}
async function availableChannels(settings:Record<string,unknown>,userId:string){try{const channels=await getAvailableDiscordPostChannels({guildId:String(settings.guild_id||""),userId,preferredChannelId:String(settings.event_channel_id||"")});if(channels.length)return channels;}catch(error){console.warn("[event-plans] Discord channel discovery failed; using Party Planner fallback.",error);}return settings.event_channel_id?[{id:String(settings.event_channel_id),label:"Party Planner"}]:[];}

export async function GET(){const session=await auth() as Session,userId=id(session);if(!userId)return fail(new Error("Sign in with your linked Discord account."),401);const client=await db();try{await ensureEventPlanningTables(client);return NextResponse.json({ok:true,plans:await getEventPlanDashboard(client,userId,officer(session))});}catch(error){return fail(error);}finally{await client.end();}}

export async function POST(request:Request){const session=await auth() as Session,userId=id(session);if(!userId)return fail(new Error("Sign in with your linked Discord account."),401);const client=await db();try{await ensureEventPlanningTables(client);const character=(await client.query(`select c.id::int,c.character_name from portal_discord_links dl join portal_characters c on c.id=dl.character_id where dl.discord_user_id=$1 and c.active=true and c.fc_membership_status='current' limit 1`,[userId])).rows[0];if(!character)throw new Error("Current verified FC membership is required.");const body=await request.json(),action=String(body?.action||"");
  if(action==="create"){const input=body.plan as EventPlanInput;const settings=(await client.query(`select guild_id,event_channel_id,officer_log_channel_id,test_channel_id from portal_discord_bot_settings where id=1`)).rows[0]||{};const isOfficer=officer(session),channels=await availableChannels(settings,userId),allowed=new Set(channels.map(channel=>channel.id));if(!allowed.has(input.targetChannelId))throw new Error("Choose a Discord channel that you can view and send messages in.");input.targetChannelName=channels.find(channel=>channel.id===input.targetChannelId)?.label||input.targetChannelName;const planId=await createEventPlan(client,{discordUserId:userId,characterId:character.id,characterName:character.character_name,isOfficer},input);await client.query(`insert into portal_discord_scheduled_posts(post_type,title,message,target_channel_kind,target_channel_id,scheduled_for,status,created_by,event_plan_id,created_at,updated_at) values('event_plan',$1,'Availability planning request','event',$2,now()+interval '5 seconds','scheduled',$3,$4,now(),now())`,[input.title,input.targetChannelId,character.character_name,planId]);return NextResponse.json({ok:true,planId,plans:await getEventPlanDashboard(client,userId,isOfficer)});}
  const planId=Number(body?.planId||0);if(!planId)throw new Error("Choose a valid planning request.");const actor={discordUserId:userId,characterId:character.id,characterName:character.character_name,isOfficer:officer(session)};
  if(action==="interest"){await attachSavedAvailability(client,planId,userId,character.id);}else if(action==="withdraw"){await withdrawEventPlanInterest(client,planId,userId);}else if(action==="planAvailability"){const windows=(Array.isArray(body.windows)?body.windows:[]).map((window:Record<string,unknown>):AvailabilityWindow=>({day:Number(window.day),slot:Number(window.slot),start:Number(window.start),end:Number(window.end)}));await attachPlanAvailability(client,planId,userId,character.id,String(body.timeZone||"America/Chicago"),windows);}else if(action==="cancel"){await cancelEventPlan(client,planId,actor);}else if(action==="update"){const input=body.plan as EventPlanInput;const settings=(await client.query(`select guild_id,event_channel_id,officer_log_channel_id,test_channel_id from portal_discord_bot_settings where id=1`)).rows[0]||{},channels=await availableChannels(settings,userId),allowed=new Set(channels.map(channel=>channel.id));if(!allowed.has(input.targetChannelId))throw new Error("Choose a Discord channel that you can view and send messages in.");input.targetChannelName=channels.find(channel=>channel.id===input.targetChannelId)?.label||input.targetChannelName;await updateEventPlan(client,planId,actor,input);}else throw new Error("Unknown planning action.");return NextResponse.json({ok:true,plans:await getEventPlanDashboard(client,userId,actor.isOfficer)});
}catch(error){return fail(error);}finally{await client.end();}}
