import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

const appRoot=path.dirname(decodeURIComponent(new URL(import.meta.url).pathname).replace(/^\/(?:([A-Za-z]:))/,"$1"));
const page=fs.readFileSync(path.join(appRoot,"app","page.tsx"),"utf8");
const schema=fs.readFileSync(path.join(appRoot,"lib","achievement-collections.ts"),"utf8");
const guideLinks=fs.readFileSync(path.join(appRoot,"lib","achievement-guide-links.ts"),"utf8");
const tracker=fs.readFileSync(path.join(appRoot,"app","components","AchievementTitleTracker.tsx"),"utf8");
const guideLibrary=fs.readFileSync(path.join(appRoot,"app","components","GuideLibrary.tsx"),"utf8");
const worker=fs.readFileSync(new URL("../worker/achievement-collections.mjs",import.meta.url),"utf8");
const workerEntry=fs.readFileSync(new URL("../worker/worker.mjs",import.meta.url),"utf8");
const acquisitionLinks=fs.readFileSync(path.join(appRoot,"app","components","CollectionAcquisitionLinks.tsx"),"utf8");
const mountCard=fs.readFileSync(path.join(appRoot,"app","components","MountAcquisitionCard.tsx"),"utf8");
const minionCard=fs.readFileSync(path.join(appRoot,"app","components","MinionAcquisitionCard.tsx"),"utf8");
const sourceGuideLinks=fs.readFileSync(path.join(appRoot,"lib","collection-source-guide-links.ts"),"utf8");

function loadTypeScriptModule(file,localRequire){const source=fs.readFileSync(file,"utf8");const javascript=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const module={exports:{}};new Function("exports","require","module","__filename","__dirname",javascript)(module.exports,localRequire,module,file,path.dirname(file));return module.exports;}
const linksModule=loadTypeScriptModule(path.join(appRoot,"lib","achievement-guide-links.ts"),()=>{throw new Error("unexpected guide-link import");});
const sourceLinksModule=loadTypeScriptModule(path.join(appRoot,"lib","collection-source-guide-links.ts"),(id)=>{if(id==="./achievement-guide-links")return linksModule;throw new Error(`unexpected source-guide import: ${id}`);});
const collectionsModule=loadTypeScriptModule(path.join(appRoot,"lib","achievement-collections.ts"),(id)=>{if(id==="./achievement-guide-links")return linksModule;throw new Error(`unexpected collection import: ${id}`);});

test("Collections keeps Mount Party Tracker and links all four collection areas",()=>{assert.match(page,/>Mounts<\/a>/);assert.match(page,/>Minions<\/a>/);assert.match(page,/>Titles<\/a>/);assert.match(page,/>Achievements<\/a>/);assert.match(page,/>Party Tracker<\/a>/);});
test("personal achievement ownership is scoped by server-known character ID",()=>{assert.match(schema,/ca\.character_id=\$1/);assert.doesNotMatch(page,/collectionCharacterId/);});
test("ownership sync is additive and retains last-known data",()=>{assert.match(worker,/on conflict \(character_id,achievement_id\) do update/);assert.doesNotMatch(worker,/delete from portal_character_achievements/i);assert.match(worker,/existing ownership retained/);});
test("titles use one row, any-source ownership, and distinct owned totals",()=>{assert.match(schema,/left join lateral/);assert.match(schema,/jsonb_agg\(jsonb_build_object\('achievementId'/);assert.match(schema,/exists \(select 1 from portal_title_achievements owned_ta/);assert.match(schema,/count\(distinct ta\.title_id\)/);assert.match(tracker,/Ways to earn/);});
test("a multi-source title maps once and is owned when any path is complete",()=>{const row=collectionsModule.mapCollectionCatalogRow({id:7,name:"Example Title",owned:true,sources:[{achievementId:1026,name:"First path",points:10,typeName:"Quests",categoryName:"Allied Societies",owned:false,rewards:[]},{achievementId:1952,name:"Second path",points:20,typeName:"Battle",categoryName:"Deep Dungeon",owned:true,rewards:[]}],rewards:[]});assert.equal(row.sources.length,2);assert.equal(row.owned,true);assert.ok(row.guides.some((guide)=>guide.depth==="detailed"));assert.ok(row.guides.some((guide)=>guide.depth==="category"));assert.equal(new Set(row.guides.map((guide)=>guide.slug)).size,row.guides.length);});
test("title query keeps pagination at title level and passes guide IDs to PostgreSQL",async()=>{let mainSql="";let mainParams=[];const client={query:async(sql,params=[])=>{if(sql.includes("count(*) over()")){mainSql=sql;mainParams=params;return{rows:[{id:9,name:"One title",owned:true,sources:[{achievementId:1026,name:"A path",owned:true,rewards:[]}],matching_total:1,rewards:[]}]};}if(sql.includes("achievements_total"))return{rows:[{titles_total:1,titles_owned:1,achievements_total:1,achievements_owned:1,points_total:10,points_earned:10}]};if(sql.includes("array(select"))return{rows:[{types:[],categories:[],patches:[]}]};return{rows:[{status:"synced",last_success_at:null,message:null}]};}};const result=await collectionsModule.getCollectionCatalogPage(client,"titles",99,{search:"",type:"",category:"",patch:"",availability:"",ownership:"all",guide:"detailed",page:1});assert.equal(result.rows.length,1);assert.equal(result.owned,1);assert.match(mainSql,/from portal_titles t/);assert.doesNotMatch(mainSql,/from portal_titles t left join portal_title_achievements ta/);assert.equal(mainParams.length,11);assert.ok(Array.isArray(mainParams[10]));});
test("guide depth is filterable and related guides preserve return state",()=>{assert.match(schema,/guide:CollectionGuideFilter/);assert.match(schema,/\$10='detailed'/);assert.match(schema,/\$10='category'/);assert.match(tracker,/>Detailed guide</);assert.match(tracker,/>Category guide</);assert.match(tracker,/returnTo=/);assert.match(guideLibrary,/Back to collection results/);assert.match(page,/requestedGuideReturnHref/);});
test("curated achievement links provide detailed and broader category help",()=>{for(const id of [1026,1952,3375,3536,3786,3985,4016])assert.match(guideLinks,new RegExp(`\\b${id}\\b`));const guides=linksModule.getAchievementGuideLinks({achievementId:1026,typeName:"Quests",categoryName:"Allied Societies"});assert.ok(guides.some((guide)=>guide.depth==="detailed"));assert.ok(guides.some((guide)=>guide.depth==="category"));});
test("mount and minion source cards link achievements and guides without consuming the artwork flip",()=>{assert.match(acquisitionLinks,/View achievement/);assert.match(acquisitionLinks,/getCollectionSourceGuideLinks\(source\)/);assert.match(acquisitionLinks,/event\.stopPropagation\(\)/);assert.match(mountCard,/role="button"/);assert.match(minionCard,/role="button"/);assert.match(mountCard,/CollectionAcquisitionLinks/);assert.match(minionCard,/CollectionAcquisitionLinks/);assert.doesNotMatch(mountCard,/<button className="minion-acquisition-face minion-acquisition-front"/);assert.doesNotMatch(minionCard,/<button\s+className="minion-acquisition-face minion-acquisition-front"/);});
test("collection source families resolve to public reward guides",()=>{const cases=[["Trial","The Minstrel's Ballad","trial-mount-series"],["Purchase","18 Seafarer's Cowries - Island Sanctuary","island-sanctuary-collection-rewards"],["PvP","Series Malmstones","pvp-collection-rewards"],["Treasure Hunt","The Excitatron 6000","treasure-dungeon-collection-rewards"],["Deep Dungeon","Gold-trimmed Sack","deep-dungeon-collection-rewards"],["Other","Bozja lockbox","field-operation-collection-rewards"],["Purchase","Sacks of Nuts","hunt-collection-rewards"],["Gold Saucer","MGP","gold-saucer-collection-rewards"],["Tribal","Pixie","society-pixie"],["V&C Dungeon","Trisassant - 100 manuscripts","variant-criterion-collection-rewards"],["Cosmic Exploration","Cosmic Fortune","cosmic-exploration"],["Skybuilders","Fête Present","ishgard-restoration"],["Wondrous Tails","600 Faux Leaves","wondrous-tails-faux-hollows-rewards"],["Dungeon","The Clyteum","duty-drop-collection-rewards"],["Chaotic Raid","Cloud of Darkness","duty-drop-collection-rewards"],["FATE","500 Bicolor Gemstone Vouchers","fate-bicolor-collection-rewards"],["Venture","Highland Exploration XXXI","retainer-venture-minion-rewards"],["Voyages","South Indigo Deep","fc-voyage-collection-rewards"],["Crafting","Crafted by Weaver","crafted-gathered-gardening-rewards"],["Other","Gardening","crafted-gathered-gardening-rewards"]];for(const [type,text,slug] of cases){const guides=sourceLinksModule.getCollectionSourceGuideLinks({type,text,relatedType:null,relatedId:null});assert.ok(guides.some((guide)=>guide.slug===slug),`${type}: ${text} did not resolve ${slug}`);}assert.match(sourceGuideLinks,/getAchievementGuideLinks/);});

test("variant and criterion mount sources open their exact dungeon guide",()=>{const cases=[
  ["Silkie - The Sil'dihn Subterrane","variant-criterion-sildihn-subterrane"],
  ["Shishioji - Mount Rokkon","variant-criterion-mount-rokkon"],
  ["Quaqua - Aloalo Island","variant-criterion-aloalo-island"],
  ["Genie of the Lamp - Another Merchant's Tale","variant-criterion-merchants-tale"],
];for(const [text,slug] of cases){const guides=sourceLinksModule.getCollectionSourceGuideLinks({type:"V&C Dungeon",text,relatedType:null,relatedId:null});assert.ok(guides.some((guide)=>guide.slug===slug),`${text} did not resolve ${slug}`);}});
test("collection source availability notices distinguish premium, event, and legacy entries",()=>{for(const [type,text,label] of [["Premium","Online Store","External purchase"],["Event","Moonfire Faire","Limited-time source"],["Other","Legacy Campaign","Legacy source"]]){assert.equal(sourceLinksModule.getCollectionSourceNotice({type,text,relatedType:null,relatedId:null})?.label,label);}assert.match(acquisitionLinks,/collection-source-notice/);});
test("app and worker recognize the same upstream collection source categories",()=>{const appTypes=[...sourceLinksModule.KNOWN_COLLECTION_SOURCE_TYPES].sort();const match=workerEntry.match(/KNOWN_COLLECTION_SOURCE_TYPES = new Set\((\[[^\]]+\])\)/);assert.ok(match,"worker source policy is missing");const workerTypes=JSON.parse(match[1]).sort();assert.deepEqual(workerTypes,appTypes);assert.match(workerEntry,/auditCollectionSourceTypes\(client, "Minion catalog"/);assert.match(workerEntry,/auditCollectionSourceTypes\(client, "Mount catalog"/);});
test("unmapped collection sources are persisted and exposed to officers",()=>{assert.match(workerEntry,/insert into portal_collection_source_warnings/);assert.match(workerEntry,/first_observed_at/);assert.match(workerEntry,/last_observed_at/);assert.match(workerEntry,/resolved_at = null/);assert.match(page,/getCollectionSourceWarnings/);assert.match(page,/Collection source mapping needs review/);assert.match(page,/Examples:/);});
test("mount sync retains structured achievement IDs for exact collection links",()=>{assert.match(workerEntry,/acquisitionData = \(Array\.isArray\(mount\.sources\)/);assert.match(workerEntry,/relatedType: String\(source\?\.related_type/);assert.match(workerEntry,/relatedId: Number\(source\?\.related_id/);assert.match(workerEntry,/acquisition_data = excluded\.acquisition_data/);assert.match(page,/m\.acquisition_data/);});
