import type { CollectionCatalogPage, CollectionFilters, CollectionKind } from "../../lib/achievement-collections";

function labelAvailability(value:string){return value==="ranked_pvp"?"Ranked PvP":value==="time_limited"?"Time-limited":value==="legacy"?"Legacy":value==="obtainable"?"Obtainable":"Unknown";}
function pageHref(kind:CollectionKind,filters:CollectionFilters,page:number){const q=new URLSearchParams({view:kind,collectionSearch:filters.search,collectionType:filters.type,collectionCategory:filters.category,collectionPatch:filters.patch,collectionAvailability:filters.availability,collectionOwnership:filters.ownership,collectionGuide:filters.guide,collectionPage:String(page)});for(const [key,value] of [...q.entries()])if(!value||value==="all")q.delete(key);return`/?${q.toString()}#collection-catalog`;}
function guideHref(slug:string,returnHref:string){return`/?view=guides&guide=${encodeURIComponent(slug)}&returnTo=${encodeURIComponent(returnHref)}#guides`;}

export default function AchievementTitleTracker({kind,data,filters,characterName}:{kind:CollectionKind;data:CollectionCatalogPage;filters:CollectionFilters;characterName:string|null}){
  const titles=kind==="titles";const noun=titles?"title":"achievement";const plural=titles?"Titles":"Achievements";const returnHref=pageHref(kind,filters,data.page);
  return <section className="section-block collection-tracker" id="collection-catalog">
    <div className="section-title-row"><div><p className="eyebrow">Personal collections</p><h2>{plural}</h2><p>{titles?"Browse every title, all known ways to earn it, and your personal progress.":"Explore achievement requirements, points, rewards, availability, and your personal progress."}</p></div><a className="small-link" href={guideHref("achievement-title-journeys",returnHref)}>Open journey guides</a></div>
    <div className="collection-tabs"><a className={titles?"active":""} href="/?view=titles">Titles</a><a className={!titles?"active":""} href="/?view=achievements">Achievements</a></div>
    <div className="stat-grid collection-stats"><article><span>Catalog</span><strong>{data.catalogTotal.toLocaleString()}</strong></article><article><span>{characterName?`${characterName}'s owned`:"Personal progress"}</span><strong>{characterName?data.owned.toLocaleString():"Sign in"}</strong></article>{!titles?<article><span>Achievement points</span><strong>{characterName?`${data.pointsEarned.toLocaleString()} / ${data.pointsTotal.toLocaleString()}`:data.pointsTotal.toLocaleString()}</strong></article>:null}<article><span>Ownership source</span><strong>{characterName?(data.syncStatus?.status==="synced"?"Lodestone synced":"Waiting for sync"):"Public catalog"}</strong></article></div>
    {!characterName?<div className="notice-card"><strong>Catalog view</strong><p>Sign in with a linked, current FC character to see Owned and Missing status. Other members&apos; achievement history is never exposed here.</p></div>:data.syncStatus?.message?<div className="notice-card"><strong>Last-known personal progress</strong><p>{data.syncStatus.message}</p></div>:null}
    <form className="collection-filter-panel" method="get" action="/"><input type="hidden" name="view" value={kind}/><label><span>Search</span><input name="collectionSearch" defaultValue={filters.search} placeholder={`Search ${plural.toLowerCase()}, requirements, or rewards`}/></label><label><span>Type</span><select name="collectionType" defaultValue={filters.type}><option value="">All types</option>{data.types.map((value)=><option key={value}>{value}</option>)}</select></label><label><span>Category</span><select name="collectionCategory" defaultValue={filters.category}><option value="">All categories</option>{data.categories.map((value)=><option key={value}>{value}</option>)}</select></label><label><span>Patch</span><select name="collectionPatch" defaultValue={filters.patch}><option value="">All patches</option>{data.patches.map((value)=><option key={value}>{value}</option>)}</select></label><label><span>Availability</span><select name="collectionAvailability" defaultValue={filters.availability}><option value="">All availability</option><option value="obtainable">Obtainable</option><option value="time_limited">Time-limited</option><option value="legacy">Legacy</option><option value="ranked_pvp">Ranked PvP</option><option value="unknown">Unknown</option></select></label><label><span>Progress</span><select name="collectionOwnership" defaultValue={filters.ownership} disabled={!characterName}><option value="all">All {plural.toLowerCase()}</option><option value="owned">Owned</option><option value="missing">Missing</option></select></label><label><span>Guide</span><select name="collectionGuide" defaultValue={filters.guide}><option value="all">All guide depths</option><option value="detailed">Detailed guide</option><option value="category">Category guide</option><option value="none">No guide</option></select></label><button className="button primary" type="submit">Apply Filters</button><a className="button" href={`/?view=${kind}#collection-catalog`}>Clear</a></form>
    <p className="collection-result-count">Showing {data.rows.length?`${(data.page-1)*data.pageSize+1}-${(data.page-1)*data.pageSize+data.rows.length}`:"0"} of {data.total.toLocaleString()} matching {plural.toLowerCase()}.</p>
    <div className="collection-card-grid">{data.rows.map((row)=>{const guideDepth=row.guides.some((guide)=>guide.depth==="detailed")?"Detailed guide":row.guides.length?"Category guide":null;return <article className={`collection-card ${row.owned?"owned":""}`} key={row.id}>
      <div className="collection-card-heading">{row.iconUrl?<img src={row.iconUrl} alt="" loading="lazy"/>:null}<div><div className="tag-row"><span className={`tag availability-${row.availability}`}>{labelAvailability(row.availability)}</span>{characterName?<span className={`tag ${row.owned?"owned-tag":"missing-tag"}`}>{row.owned?"Owned":"Missing"}</span>:null}{guideDepth?<span className={`tag guide-available-tag guide-depth-${guideDepth.startsWith("Detailed")?"detailed":"category"}`}>{guideDepth}</span>:null}</div><h3>{row.name}</h3>{row.alternateName?<p className="collection-alt-name">Alternate: {row.alternateName}</p>:null}</div></div>
      <div className="collection-meta"><span>{row.typeName||"Uncategorized"}</span><span>{row.categoryName||"General"}</span>{row.patch?<span>Patch {row.patch}</span>:null}{!titles?<span>{row.points} points</span>:null}</div>
      {titles&&row.sources.length?<div className="collection-sources"><h4>{row.sources.length>1?"Ways to earn":"How to earn"}</h4>{row.sources.map((source)=><section className={`collection-source ${source.owned?"owned":""}`} key={source.achievementId}><div className="collection-source-heading"><strong>{source.name}</strong>{characterName?<span className={`tag ${source.owned?"owned-tag":"missing-tag"}`}>{source.owned?"Completed":"Not completed"}</span>:null}</div>{source.description?<p>{source.description}</p>:null}<div className="collection-meta"><span>{source.typeName||"Uncategorized"}</span><span>{source.categoryName||"General"}</span><span>{source.points} points</span></div>{source.rewards.length?<p><strong>Rewards:</strong> {source.rewards.map((reward)=>reward.name||reward.type).join(", ")}</p>:null}</section>)}</div>:null}
      {!titles&&row.description?<p><strong>How to earn:</strong> {row.description}</p>:null}{!titles&&row.rewards.length?<p><strong>Rewards:</strong> {row.rewards.map((reward)=>reward.name||reward.type).join(", ")}</p>:null}{titles&&!row.sources.length?<p className="muted-text">No source achievement is currently linked to this title.</p>:null}{row.availabilityReason?<p className="muted-text">{row.availabilityReason}</p>:null}
      {row.guides.length?<div className="collection-guide-links" aria-label="Related guides">{row.guides.map((guide)=><a className={`button ${guide.depth==="detailed"?"primary":""}`} key={guide.slug} href={guideHref(guide.slug,returnHref)}>{guide.depth==="detailed"?"Open detailed guide":"Browse category guide"}: {guide.title} →</a>)}</div>:null}
    </article>;})}</div>
    {!data.rows.length?<p className="empty-state">No {noun}s match those filters. Your saved collection was not changed.</p>:null}
    <nav className="collection-pagination" aria-label={`${plural} pages`}><a className={data.page<=1?"button disabled":"button"} href={data.page>1?pageHref(kind,filters,data.page-1):undefined}>Previous</a><span>Page {data.page} of {data.totalPages}</span><a className={data.page>=data.totalPages?"button disabled":"button"} href={data.page<data.totalPages?pageHref(kind,filters,data.page+1):undefined}>Next</a></nav>
  </section>;
}
