"use client";

import { useEffect, useMemo, useState } from "react";

const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const ZONES=[
  ["America/St_Johns","Newfoundland Time"],["America/Halifax","Atlantic Time"],["America/New_York","Eastern Time"],["America/Chicago","Central Time"],["America/Denver","Mountain Time"],["America/Phoenix","Arizona Time"],["America/Los_Angeles","Pacific Time"],["America/Anchorage","Alaska Time"],["Pacific/Honolulu","Hawaii Time"],["UTC","UTC"],["Europe/London","United Kingdom"],["Europe/Paris","Central European Time"],["Europe/Berlin","Germany"],["Africa/Johannesburg","South Africa"],["Asia/Dubai","Gulf Time"],["Asia/Kolkata","India Time"],["Asia/Bangkok","Indochina Time"],["Asia/Singapore","Singapore Time"],["Asia/Shanghai","China Time"],["Asia/Tokyo","Japan Time"],["Asia/Seoul","Korea Time"],["Australia/Sydney","Sydney Time"],["Australia/Brisbane","Brisbane Time"],["Australia/Perth","Perth Time"],["Pacific/Auckland","New Zealand Time"]
] as const;
type Window={day:number;slot:number;start:number;end:number};
type Availability={profile:null|{time_zone:string;schedule_scope:"ongoing"|"week"|"two_weeks";expires_at:string|null;last_confirmed_at:string;stale:boolean};windows:Window[];reconfirmAt:string|null};
type Planner={durationMinutes:number;weeks:number;totalMembers:number;reportingMembers:number;missingMembers:number;suggestions:Array<{startsAt:string;endsAt:string;date:string;time:string;label:string;count:number;members:string[]}>;members:Array<{discordUserId:string;name:string;timeZone:string;scope:string;expiresAt:string|null;reconfirmAt:string|null;windows:Window[]}>};

function minuteValue(value:string){if(!/^\d{2}:\d{2}$/.test(value))return null;const [hour,minute]=value.split(":").map(Number);return hour*60+minute;}
function timeValue(value:number){const normalized=((value%1440)+1440)%1440;return `${String(Math.floor(normalized/60)).padStart(2,"0")}:${String(normalized%60).padStart(2,"0")}`;}
function displayTime(value:number){const normalized=((value%1440)+1440)%1440,hour=Math.floor(normalized/60),minute=normalized%60;return `${hour%12||12}:${String(minute).padStart(2,"0")} ${hour>=12?"PM":"AM"}${value>=1440?" next day":""}`;}
function scheduleLine(windows:Window[],day:number){const values=windows.filter((window)=>window.day===day).sort((a,b)=>a.slot-b.slot);return values.length?values.map((window)=>`${displayTime(window.start)}–${displayTime(window.end)}`).join(", "):"Unavailable";}
function deadline(availability:Availability|null){if(!availability?.profile)return "No schedule entered";const value=availability.profile.schedule_scope==="ongoing"?availability.reconfirmAt:availability.profile.expires_at;return `${availability.profile.schedule_scope==="ongoing"?"Reconfirm by":"Expires"} ${value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium"}).format(new Date(value)):"—"}`;}

export default function AvailabilityPanel({isOfficer,defaultTimeZone,compact=false}:{isOfficer:boolean;defaultTimeZone:string;compact?:boolean}){
  const [availability,setAvailability]=useState<Availability|null>(null),[editor,setEditor]=useState(false),[plannerOpen,setPlannerOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [planContext,setPlanContext]=useState<{planId:number;title:string;usesPlanHours:boolean}|null>(null);
  const [timeZone,setTimeZone]=useState(defaultTimeZone),[scope,setScope]=useState<"ongoing"|"week"|"two_weeks">("ongoing"),[windows,setWindows]=useState<Window[]>([]),[duration,setDuration]=useState(120),[weeks,setWeeks]=useState(4),[planner,setPlanner]=useState<Planner|null>(null);
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/availability",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error);setAvailability(body.availability);setTimeZone(body.availability.profile?.time_zone||defaultTimeZone);setScope(body.availability.profile?.schedule_scope||"ongoing");setWindows(body.availability.windows||[]);}catch(caught){setError(caught instanceof Error?caught.message:"Availability could not be loaded.");}finally{setLoading(false);}}
  useEffect(()=>{void load();const openPlan=(event:Event)=>{const detail=(event as CustomEvent<{planId?:number;title?:string;usesPlanHours?:boolean;windows?:Window[];timeZone?:string|null}>).detail;if(!detail?.planId)return;const usesPlanHours=Boolean(detail.usesPlanHours);if(usesPlanHours){setWindows(Array.isArray(detail.windows)?detail.windows:[]);if(detail.timeZone)setTimeZone(detail.timeZone);}setPlanContext({planId:Number(detail.planId),title:String(detail.title||"this plan"),usesPlanHours});setEditor(true);};window.addEventListener("cotf:availability-plan",openPlan);return()=>window.removeEventListener("cotf:availability-plan",openPlan);},[]);
  const grouped=useMemo(()=>DAYS.map((_,day)=>[0,1].map((slot)=>windows.find((window)=>window.day===day&&window.slot===slot)||null)),[windows]);
  function setPeriod(day:number,slot:number,field:"start"|"end",value:string){const minute=minuteValue(value);setWindows((current)=>{const without=current.filter((window)=>!(window.day===day&&window.slot===slot));if(minute===null)return without;const prior=current.find((window)=>window.day===day&&window.slot===slot),start=field==="start"?minute:prior?.start??minute,endRaw=field==="end"?minute:prior?.end??minute+120,end=endRaw<=start?endRaw+1440:endRaw;return [...without,{day,slot,start,end}];});}
  function clearDay(day:number){setWindows((current)=>current.filter((window)=>window.day!==day));}
  async function save(){setLoading(true);setError("");try{const response=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({timeZone,scope,windows})}),body=await response.json();if(!response.ok)throw new Error(body.error);setAvailability(body.availability);if(planContext){const joined=await fetch("/api/event-plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"interest",planId:planContext.planId})}),joinedBody=await joined.json();if(!joined.ok)throw new Error(joinedBody.error);}setEditor(false);setPlanContext(null);window.dispatchEvent(new Event("cotf:event-plans-refresh"));}catch(caught){setError(caught instanceof Error?caught.message:"Availability could not be saved.");}finally{setLoading(false);}}
  async function saveForPlan(){if(!planContext)return;setLoading(true);setError("");try{const response=await fetch("/api/event-plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"planAvailability",planId:planContext.planId,timeZone,windows})}),body=await response.json();if(!response.ok)throw new Error(body.error);setEditor(false);setPlanContext(null);window.dispatchEvent(new Event("cotf:event-plans-refresh"));}catch(caught){setError(caught instanceof Error?caught.message:"Plan availability could not be saved.");}finally{setLoading(false);}}
  async function action(name:"clear"|"confirm"){if(name==="clear"&&!window.confirm("Clear your saved availability?"))return;const response=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:name})}),body=await response.json();if(response.ok){setAvailability(body.availability);setWindows(body.availability.windows||[]);}else setError(body.error||"Availability could not be updated.");}
  async function loadPlanner(nextDuration=duration,nextWeeks=weeks){setLoading(true);setError("");try{const params=new URLSearchParams({planner:"1",duration:String(nextDuration),weeks:String(nextWeeks),timeZone:defaultTimeZone}),response=await fetch(`/api/availability?${params}`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error);setPlanner(body.planner);setPlannerOpen(true);}catch(caught){setError(caught instanceof Error?caught.message:"Suggestions could not be calculated.");}finally{setLoading(false);}}
  function planEvent(suggestion:Planner["suggestions"][number]){window.dispatchEvent(new CustomEvent("cotf:plan-event",{detail:{date:suggestion.date,time:suggestion.time}}));setPlannerOpen(false);}
  return <>
    <article className={`panel availability-launch ${compact?"compact":""}`}>
      <div><span className="tag">Availability</span><h3>{availability?.profile?"Your weekly availability":"Share when you can join"}</h3><p>{availability?.profile?`${availability.profile.time_zone} · ${deadline(availability)}`:"Set recurring hours or a temporary one- or two-week schedule. Ongoing schedules require confirmation every 90 days."}</p>{availability?.profile?.stale?<small className="availability-stale">This schedule is stale and excluded from officer suggestions until reconfirmed.</small>:null}</div>
      <div className="availability-launch-actions"><button type="button" className="button primary" onClick={()=>setEditor(true)}>{availability?.profile?"Update My Availability":"Set My Availability"}</button>{availability?.profile?<button type="button" className="button secondary" onClick={()=>void action("confirm")}>Still Current</button>:null}{isOfficer?<button type="button" className="button secondary" onClick={()=>void loadPlanner()}>Availability Planner</button>:null}</div>
    </article>
    {error?<p className="availability-error" role="alert">{error}</p>:null}
    {editor?<div className="giveaway-wizard-backdrop" role="presentation"><section className="giveaway-wizard availability-dialog" role="dialog" aria-modal="true" aria-labelledby="availability-title"><header className="giveaway-wizard-header"><div><p className="eyebrow">{planContext?"Planning request":"Weekly schedule"}</p><h3 id="availability-title">{planContext?`Availability for ${planContext.title}`:"My Availability"}</h3></div><button type="button" className="button secondary" onClick={()=>{setEditor(false);setPlanContext(null);}}>Close</button></header><div className="availability-editor">
      {planContext?<div className="giveaway-wizard-note"><strong>Only this planning request will count you</strong><p>{planContext.usesPlanHours?"Your existing event-specific hours are loaded below. You can review or change them without affecting your reusable schedule.":"Choose whether to update your reusable schedule or attach these hours only to this plan. Other members with old schedules are not included unless they also expressed interest."}</p></div>:null}
      <div className="availability-settings"><label><span>Timezone</span><select value={timeZone} onChange={(event)=>setTimeZone(event.target.value)}>{ZONES.map(([value,label])=><option key={value} value={value}>{label} · {new Intl.DateTimeFormat("en-US",{timeZone:value,hour:"numeric",minute:"2-digit"}).format(new Date())}</option>)}</select></label><label><span>Keep this schedule</span><select value={scope} onChange={(event)=>setScope(event.target.value as typeof scope)}><option value="ongoing">Ongoing · reconfirm after 90 days</option><option value="week">Temporary · expires after 1 week</option><option value="two_weeks">Temporary · expires after 2 weeks</option></select></label></div>
      <p className="availability-scope-note">The saved confirmation shows the exact expiration or reconfirmation date. Expired temporary schedules are deleted automatically.</p>
      <div className="availability-days">{DAYS.map((day,dayIndex)=><article key={day} className="availability-day"><div><strong>{day}</strong><button type="button" onClick={()=>clearDay(dayIndex)}>Unavailable</button></div>{[0,1].map((slot)=>{const period=grouped[dayIndex][slot];return <div className="availability-period" key={slot}><span>{slot===0?"Primary":"Optional second period"}</span><label>From<input type="time" step="1800" value={period?timeValue(period.start):""} onChange={(event)=>setPeriod(dayIndex,slot,"start",event.target.value)} /></label><label>Until<input type="time" step="1800" value={period?timeValue(period.end):""} onChange={(event)=>setPeriod(dayIndex,slot,"end",event.target.value)} /></label></div>;})}</article>)}</div>
    </div><footer className="giveaway-wizard-footer"><button type="button" className="button secondary" onClick={()=>availability?.profile&&!planContext?void action("clear"):(setEditor(false),setPlanContext(null))}>{availability?.profile&&!planContext?"Clear Schedule":"Cancel"}</button><span>{windows.length} availability period{windows.length===1?"":"s"}</span>{planContext?<button type="button" className="button secondary" disabled={loading||windows.length===0} onClick={()=>void saveForPlan()}>Use for This Plan Only</button>:null}<button type="button" className="button primary" disabled={loading} onClick={()=>void save()}>{loading?"Saving…":planContext?"Update Saved Schedule & Use It":"Save Availability"}</button></footer></section></div>:null}
    {plannerOpen&&planner?<div className="giveaway-wizard-backdrop" role="presentation"><section className="giveaway-wizard availability-dialog planner-dialog" role="dialog" aria-modal="true" aria-labelledby="planner-title"><header className="giveaway-wizard-header"><div><p className="eyebrow">Officer planning</p><h3 id="planner-title">Availability Suggestions</h3></div><button type="button" className="button secondary" onClick={()=>setPlannerOpen(false)}>Close</button></header><div className="availability-planner">
      <div className="availability-settings"><label><span>Event duration</span><select value={duration} onChange={(event)=>{const value=Number(event.target.value);setDuration(value);void loadPlanner(value,weeks);}}><option value="60">1 hour</option><option value="90">1½ hours</option><option value="120">2 hours</option><option value="180">3 hours</option><option value="240">4 hours</option></select></label><label><span>Search ahead</span><select value={weeks} onChange={(event)=>{const value=Number(event.target.value);setWeeks(value);void loadPlanner(duration,value);}}><option value="2">2 weeks</option><option value="4">4 weeks</option><option value="8">8 weeks</option></select></label></div>
      <p><strong>{planner.reportingMembers} of {planner.totalMembers}</strong> current members have active, non-stale availability. {planner.missingMembers} missing or stale schedule{planner.missingMembers===1?"":"s"} are not counted as unavailable.</p>
      <div className="availability-suggestions">{planner.suggestions.length?planner.suggestions.map((suggestion,index)=><article key={suggestion.startsAt}><div><span className="tag">#{index+1}</span><strong>{suggestion.label}</strong><small>{suggestion.count} reporting member{suggestion.count===1?"":"s"} available · {suggestion.members.join(", ")}</small></div><button type="button" className="button primary" onClick={()=>planEvent(suggestion)}>Plan Event</button></article>):<p>No complete overlap was found for the selected duration.</p>}</div>
      <details><summary>View submitted schedules</summary><div className="availability-member-list">{planner.members.map((member)=><article key={member.discordUserId}><strong>{member.name}</strong><small>{member.timeZone} · {member.scope==="ongoing"?`reconfirm by ${member.reconfirmAt?new Date(member.reconfirmAt).toLocaleDateString():"—"}`:`expires ${member.expiresAt?new Date(member.expiresAt).toLocaleDateString():"—"}`}</small>{DAYS.map((day,index)=><span key={day}><b>{day.slice(0,3)}</b> {scheduleLine(member.windows,index)}</span>)}</article>)}</div></details>
    </div></section></div>:null}
  </>;
}
