"use client";
import { useEffect, useMemo, useState } from "react";
import { macroChunks, makeCraft, solveCraft, solveCraftProgressive, type CalculatorStats, type SolverProgress } from "../../lib/crafting/macro-solver";
import type { CraftingCalculatorData, CraftingCatalogSearchItem } from "../../lib/crafting/service";
import { CalculatorTrust, ReportCalculatorIssue } from "./calculators/CalculatorCommon";

type Consumable = CraftingCalculatorData["consumables"][number];
type Profile = CalculatorStats & { job:string; foodId:number|null; foodHq:boolean; medicineId:number|null; medicineHq:boolean; updatedAt:string };
const JOBS=["Carpenter","Blacksmith","Armorer","Goldsmith","Leatherworker","Weaver","Alchemist","Culinarian"];
const JOB_ALIASES:Record<string,string>={Woodworking:"Carpenter",Smithing:"Blacksmith",Armorcraft:"Armorer",Goldsmithing:"Goldsmith",Leatherworking:"Leatherworker",Clothcraft:"Weaver",Alchemy:"Alchemist",Cooking:"Culinarian"};
function normalizeJob(job:string){return JOB_ALIASES[job]||job}
function withConsumables(base: CalculatorStats, choices: Array<{ item: Consumable | null; hq: boolean }>) {
  const next = { ...base };
  for (const {item,hq} of choices) for (const bonus of item?.bonuses || []) {
    const value = hq ? bonus.valueHq : bonus.value; const cap = hq ? bonus.maxHq : bonus.max;
    const amount = bonus.relative ? Math.min(Math.floor(base[bonus.stat] * value / 100), cap) : value;
    next[bonus.stat] += amount;
  }
  return next;
}
function bonusLabel(item: Consumable, hq=true) { return item.bonuses.map((b) => `${b.stat === "cp" ? "CP" : b.stat[0].toUpperCase()+b.stat.slice(1)} +${hq?b.valueHq:b.value}${b.relative?`% (max ${hq?b.maxHq:b.max})`:""}`).join(", "); }
function actionLabel(name:string){const special:Record<string,string>={ByregotsBlessing:"Byregot's Blessing",MastersMend:"Master's Mend",WasteNotII:"Waste Not II"};return special[name]||name.replace(/([a-z])([A-Z])/g,"$1 $2");}

export default function CraftingMacroCalculator() {
  const [query,setQuery]=useState(""); const [items,setItems]=useState<CraftingCatalogSearchItem[]>([]); const [data,setData]=useState<CraftingCalculatorData|null>(null);
  const [stats,setStats]=useState<CalculatorStats>({level:100,craftsmanship:0,control:0,cp:0,specialist:false});
  const [foodId,setFoodId]=useState(0); const [medicineId,setMedicineId]=useState(0); const [foodHq,setFoodHq]=useState(true); const [medicineHq,setMedicineHq]=useState(true);
  const [profiles,setProfiles]=useState<Profile[]>([]); const [profilesReady,setProfilesReady]=useState(false); const [profileJob,setProfileJob]=useState("Carpenter"); const [profileStatus,setProfileStatus]=useState("");
  const [goal,setGoal]=useState<"max"|"complete">("max"); const [status,setStatus]=useState(""); const [result,setResult]=useState<ReturnType<typeof solveCraft>>(null); const [suggestion,setSuggestion]=useState(""); const [generating,setGenerating]=useState(false); const [searchProgress,setSearchProgress]=useState<SolverProgress|null>(null); const [searchPass,setSearchPass]=useState(0); const [resultSignature,setResultSignature]=useState(""); const [searchExhausted,setSearchExhausted]=useState(false);
  useEffect(()=>{ if(query.trim().length<2){setItems([]);return;} const timer=setTimeout(()=>fetch(`/api/crafting/catalog?q=${encodeURIComponent(query)}`).then(r=>r.json()).then(v=>setItems(v.items||[])).catch(()=>setItems([])),250); return()=>clearTimeout(timer);},[query]);
  useEffect(()=>{fetch("/api/crafting/profiles").then(r=>r.json()).then(v=>setProfiles(v.profiles||[])).catch(()=>setProfiles([])).finally(()=>setProfilesReady(true));},[]);
  useEffect(()=>{if(profilesReady)applyProfile(profileJob,profiles)},[profilesReady]);
  const foods=useMemo(()=>data?.consumables.filter((x)=>x.type==="food")||[],[data]); const medicines=useMemo(()=>data?.consumables.filter((x)=>x.type==="medicine")||[],[data]);
  const selectedFood=foods.find(x=>x.id===foodId)||null, selectedMedicine=medicines.find(x=>x.id===medicineId)||null;
  const recommendedFoods=useMemo(()=>ranked(foods,stats,goal),[foods,stats,goal]); const recommendedMedicines=useMemo(()=>ranked(medicines,stats,goal),[medicines,stats,goal]);
  function applyProfile(job:string, available=profiles){setProfileJob(job);const profile=available.find(x=>x.job===job);if(profile){setStats({level:profile.level,craftsmanship:profile.craftsmanship,control:profile.control,cp:profile.cp,specialist:profile.specialist});setFoodId(profile.foodId||0);setMedicineId(profile.medicineId||0);setFoodHq(profile.foodHq);setMedicineHq(profile.medicineHq);}else{setStats({level:100,craftsmanship:0,control:0,cp:0,specialist:false});setFoodId(0);setMedicineId(0);setFoodHq(true);setMedicineHq(true);}setResult(null);}
  async function choose(item: CraftingCatalogSearchItem){ setQuery(item.name);setItems([]);setStatus("Loading recipe…");setResult(null);setSearchExhausted(false); const response=await fetch(`/api/crafting/calculator?itemId=${item.id}`); const value=await response.json(); if(!response.ok){setData(null);setStatus(value.error||"Recipe unavailable.");return;} value.recipe.job=normalizeJob(value.recipe.job);setData(value);setGoal(value.recipe.collectable||value.recipe.canHq?"max":"complete");setStatus("");applyProfile(value.recipe.job); }
  async function saveProfile(){setProfileStatus("Saving…");const response=await fetch("/api/crafting/profiles",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({job:profileJob,...stats,foodId:foodId||null,foodHq,medicineId:medicineId||null,medicineHq})});const value=await response.json().catch(()=>({}));if(!response.ok){setProfileStatus(value.error||"Profile could not be saved.");return;}const profile={job:profileJob,...stats,foodId:foodId||null,foodHq,medicineId:medicineId||null,medicineHq,updatedAt:new Date().toISOString()};setProfiles(current=>[...current.filter(x=>x.job!==profileJob),profile]);setProfileStatus(`${profileJob} profile saved.`);}
  function ranked(values:Consumable[],base:CalculatorStats,currentGoal:"max"|"complete"){const score=(item:Consumable)=>{const boosted=withConsumables(base,[{item,hq:item.canBeHq}]);const craftsmanship=boosted.craftsmanship-base.craftsmanship,control=boosted.control-base.control,cp=boosted.cp-base.cp;return currentGoal==="max"?craftsmanship+control*1.35+cp*10:craftsmanship*1.5+control*.15+cp*10};return [...values].filter(item=>score(item)>0).sort((a,b)=>score(b)-score(a)||a.name.localeCompare(b.name)).slice(0,4)}
  function currentSearchSignature(){return JSON.stringify([data?.recipe.id,stats,foodId,foodHq,medicineId,medicineHq,goal])}
  async function generate(continueSearch=false){if(!data||generating)return;const signature=currentSearchSignature();const continuing=continueSearch&&goal==="max"&&Boolean(result)&&resultSignature===signature;const previous=continuing?result:null;const nextPass=continuing?searchPass+1:0;const beamWidth=goal==="max"?Math.min(2500,700+nextPass*400):300;setGenerating(true);setSearchExhausted(false);setStatus(continuing?`Continuing the quality search — pass ${nextPass+1}…`:"Searching for the highest-quality completed rotation…");if(!continuing)setResult(null);setSuggestion("");setSearchProgress({percent:0,elapsedMs:0,depth:0,maxDepth:goal==="max"?45:35,explored:0,bestQuality:previous?.quality??null});try{const craft=makeCraft(data.recipe);const target=goal==="max"?craft.quality:0;const boosted=withConsumables(stats,[{item:selectedFood,hq:foodHq},{item:selectedMedicine,hq:medicineHq}]);const solved=await solveCraftProgressive(craft,boosted,target,{timeLimitMs:goal==="max"?15000:5000,maxDepth:goal==="max"?45:35,beamWidth,incumbentActions:previous?.actions,onProgress:setSearchProgress});setResult(solved);if(solved){const terminal=solved.searchStopReason==="exhausted"||(continuing&&beamWidth>=2500);setSearchExhausted(terminal);setSearchPass(nextPass);setResultSignature(signature);setStatus(terminal?(solved.quality>(previous?.quality||0)?"A stronger completed rotation was found. The configured search space is now exhausted; further runs would repeat the same work.":"Search complete. No stronger rotation was found within the configured limits; further runs would repeat the same work."):continuing?(solved.quality>(previous?.quality||0)?"A stronger completed rotation was found.":"No stronger rotation was found in this pass; the previous best was kept."):(goal==="max"?"Best completed rotation found.":"Completion rotation found."));return;}let found="";const suggestionDeadline=Date.now()+1200;const foodOptions=[null,...recommendedFoods],medicineOptions=[null,...recommendedMedicines];outer:for(const food of foodOptions)for(const medicine of medicineOptions){if(Date.now()>=suggestionDeadline)break outer;if(!food&&!medicine)continue;const trial=withConsumables(stats,[{item:food,hq:food?.canBeHq||false},{item:medicine,hq:medicine?.canBeHq||false}]);if(solveCraft(craft,trial,target,suggestionDeadline)){found=[food&&`${food.name}${food.canBeHq?" HQ":""}`,medicine&&`${medicine.name}${medicine.canBeHq?" HQ":""}`].filter(Boolean).join(" + ");break outer;}}setSuggestion(found);setStatus(found?"Your current setup falls short, but a consumable combination can make it work.":"The calculator could not find a deterministic macro for these stats and this target.");}finally{setGenerating(false)}}
  const macros=result?macroChunks(result.actions):[];
  return <article className="panel crafting-calculator" id="crafting-calculator">
    <div><span className="tag">Crafting calculator</span><h3>Recipe macro builder</h3><p>Enter your exact crafter stats, choose a recipe, and generate a deterministic completion or maximum-quality rotation. Calculation runs on your device.</p></div>
    <CalculatorTrust confidence="Estimate" updated="September 14, 2026" sources={[{label:"Teamcraft simulator model",url:"https://github.com/ffxiv-teamcraft/simulator"}]}>The result is the best completed fixed rotation found within the selected search time. Expert recipe conditions can still change the outcome.</CalculatorTrust>
    <section className="crafting-profile-panel"><div><h4>My crafter profiles</h4><p>Save different stats for each crafting class. Choosing a recipe automatically loads its matching profile.</p></div><div className="crafting-profile-jobs">{JOBS.map(job=><button type="button" className={profileJob===job?"active":""} onClick={()=>applyProfile(job)} key={job}>{job}{profiles.some(x=>x.job===job)?" ✓":""}</button>)}</div><div className="crafting-calculator-grid"><label>Crafter level<input type="number" min="1" max="100" value={stats.level} onChange={e=>setStats({...stats,level:+e.target.value})}/></label><label>Craftsmanship<input type="number" min="0" value={stats.craftsmanship||""} onChange={e=>setStats({...stats,craftsmanship:+e.target.value})}/></label><label>Control<input type="number" min="0" value={stats.control||""} onChange={e=>setStats({...stats,control:+e.target.value})}/></label><label>CP<input type="number" min="0" value={stats.cp||""} onChange={e=>setStats({...stats,cp:+e.target.value})}/></label></div><div className="crafting-profile-actions"><label className="crafting-calculator-check"><input type="checkbox" checked={stats.specialist} onChange={e=>setStats({...stats,specialist:e.target.checked})}/> Specialist</label><button className="button secondary" type="button" onClick={saveProfile} disabled={!stats.craftsmanship||!stats.control||!stats.cp}>Save {profileJob}</button><span aria-live="polite">{profileStatus}</span></div></section>
    <label>Recipe<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for a craftable item…" /></label>
    {items.length?<div className="crafting-calculator-results">{items.slice(0,30).map(item=><button type="button" key={item.id} onClick={()=>choose(item)}><strong>{item.name}</strong><small>{[item.category,item.level&&`Lv. ${item.level}`].filter(Boolean).join(" · ")}</small></button>)}</div>:null}
    {data?<><div className="crafting-calculator-recipe"><div><strong>{data.recipe.name}</strong><small>{data.recipe.job} · Lv. {data.recipe.level}{data.recipe.stars?` · ${data.recipe.stars}★`:""}</small></div><div><span>Difficulty {data.recipe.difficulty}</span><span>Durability {data.recipe.durability}</span><span>{data.recipe.collectable?"Max collectability":"Quality"} {data.recipe.collectable?Math.floor(data.recipe.quality/10):data.recipe.quality}</span>{data.recipe.requiredCraftsmanship?<span>Requires {data.recipe.requiredCraftsmanship} craftsmanship</span>:null}{data.recipe.requiredControl?<span>Requires {data.recipe.requiredControl} control</span>:null}{data.recipe.collectable?<span>Collectable</span>:null}{data.recipe.expert?<span>Expert</span>:null}</div></div>
      {data.recipe.expert?<p className="crafting-calculator-warning">Expert recipes react to changing conditions. This tool can simulate a fixed rotation, but it cannot guarantee an expert craft.</p>:null}
      <p>Using your <strong>{profileJob}</strong> profile. Changes here can be saved above for your next visit or Discord macro request.</p>
      <div className="crafting-calculator-grid"><label>Food<select value={foodId} onChange={e=>setFoodId(+e.target.value)}><option value="0">No food</option>{foods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{selectedFood?<small>{bonusLabel(selectedFood,foodHq)}</small>:null}</label><label>Medicine<select value={medicineId} onChange={e=>setMedicineId(+e.target.value)}><option value="0">No medicine</option>{medicines.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{selectedMedicine?<small>{bonusLabel(selectedMedicine,medicineHq)}</small>:null}</label>{selectedFood?.canBeHq?<label className="crafting-calculator-check"><input type="checkbox" checked={foodHq} onChange={e=>setFoodHq(e.target.checked)}/> HQ food</label>:null}{selectedMedicine?.canBeHq?<label className="crafting-calculator-check"><input type="checkbox" checked={medicineHq} onChange={e=>setMedicineHq(e.target.checked)}/> HQ medicine</label>:null}</div>
      <section className="crafting-consumable-recommendations"><div><h4>Recommended consumables</h4><p>These stat-based options give the solver more room to complete the craft and improve quality or collectability. Expert recipe conditions can still change the result.</p></div><div className="crafting-consumable-columns"><div><strong>Food options</strong>{recommendedFoods.length?recommendedFoods.map(item=><button type="button" className={foodId===item.id?"active":""} key={item.id} onClick={()=>{setFoodId(item.id);setFoodHq(item.canBeHq);setResult(null);setStatus("")}}><span>{item.name}{item.canBeHq?" HQ":""}</span><small>{bonusLabel(item,item.canBeHq)}</small><em>{foodId===item.id?"Selected":"Use"}</em></button>):<small>No helpful food is available in the synced catalog.</small>}</div><div><strong>Medicine options</strong>{recommendedMedicines.length?recommendedMedicines.map(item=><button type="button" className={medicineId===item.id?"active":""} key={item.id} onClick={()=>{setMedicineId(item.id);setMedicineHq(item.canBeHq);setResult(null);setStatus("")}}><span>{item.name}{item.canBeHq?" HQ":""}</span><small>{bonusLabel(item,item.canBeHq)}</small><em>{medicineId===item.id?"Selected":"Use"}</em></button>):<small>No helpful medicine is available in the synced catalog.</small>}</div></div></section>
      <fieldset><legend>Goal</legend><label><input type="radio" checked={goal==="max"} onChange={()=>setGoal("max")}/> {data.recipe.collectable?"Complete with maximum collectability":"Complete with maximum quality"}</label><label><input type="radio" checked={goal==="complete"} onChange={()=>setGoal("complete")}/> Prioritize quickest completion</label></fieldset>
      <button className="button primary" type="button" onClick={()=>generate(false)} disabled={generating||!stats.craftsmanship||!stats.control||!stats.cp}>{generating?"Calculating…":"Generate macro"}</button>
    </>:null}
    {generating&&searchProgress?<div className="crafting-solver-progress" aria-live="polite"><div><strong>Evaluating rotations</strong><span>{Math.round(searchProgress.percent)}%</span></div><progress max="100" value={searchProgress.percent}> {Math.round(searchProgress.percent)}% </progress><small>{(searchProgress.elapsedMs/1000).toFixed(1)}s elapsed · depth {searchProgress.depth}/{searchProgress.maxDepth} · {searchProgress.explored.toLocaleString()} action paths tested{searchProgress.bestQuality!==null?` · best completed ${data?.recipe.collectable?"collectability":"quality"} ${data?.recipe.collectable?Math.floor(searchProgress.bestQuality/10):searchProgress.bestQuality}`:" · no completed rotation yet"}</small></div>:null}
    {status?<p className="crafting-calculator-status" aria-live="polite">{status}</p>:null}{suggestion?<p><strong>Suggested boost:</strong> {suggestion}. Select those consumables above and generate again to see the macro.</p>:null}
    {result?<div className="crafting-calculator-output"><h4>Successful rotation</h4><p>{result.actions.length} steps · Progress {result.progress}/{data?.recipe.difficulty} · {data?.recipe.collectable?`Collectability ${Math.floor(result.quality/10)}/${goal==="max"?Math.floor((data?.recipe.quality||0)/10):"not targeted"}`:`Quality ${result.quality}/${goal==="max"?data?.recipe.quality:"not targeted"}`} · {result.cp} CP and {result.durability} durability remaining</p>{goal==="max"&&result.quality<(data?.recipe.quality||0)?searchExhausted?<p className="crafting-search-exhausted"><strong>Search exhausted.</strong> Further runs with these recipe settings and stats would repeat the same work.</p>:<button className="button secondary crafting-continue-search" type="button" onClick={()=>generate(true)} disabled={generating}>{generating?"Continuing search…":"Continue searching for another 15 seconds"}</button>:null}<details><summary>Console-friendly entry order</summary><ol>{result.actions.map((action,index)=><li key={`${action}-${index}`}>{actionLabel(action)}</li>)}</ol></details>{macros.map((macro,index)=><div key={index}><div><strong>Macro {index+1} of {macros.length}</strong><button className="button secondary" type="button" onClick={()=>navigator.clipboard.writeText(macro)}>Copy</button></div><pre>{macro}</pre></div>)}</div>:null}
    <ReportCalculatorIssue calculator="Crafting macro" context={{recipe:data?.recipe?.name||query,profileJob,stats,goal,food:selectedFood?.name||null,medicine:selectedMedicine?.name||null,result:result?{actions:result.actions,progress:result.progress,quality:result.quality,cp:result.cp,durability:result.durability}:null}}/>
  </article>;
}
