"use client";

import { useEffect, useMemo, useState } from "react";

type Duty={id:number;duty_type:string;name:string;level:number|null;party_size?:number|null};
type Mount={id:number;mount_name:string;source_name:string|null};
type Destination={id:string;label:string};
type Suggestion={startsAt:string;endsAt:string;label:string;count:number;members:string[]};
type AvailabilityWindow={day:number;slot:number;start:number;end:number};
type ParticipantSchedule={discordUserId:string;name:string;source:string|null;timeZone:string;windows:string[]};
type Plan={id:number;status:string;event_type:string;title:string;description:string;duty_id:number|null;duty_name:string|null;duty_image_url:string|null;mount_id:number|null;mount_name:string|null;mount_image_url:string|null;level:number|null;party_size:number;standard_party_roles_required:boolean;possible_start_date:string;possible_end_date:string;duration_minutes:number;event_time_zone:string;target_channel_id:string;created_by:string;created_by_discord_user_id:string;current_interest_status:string;availability_source:string|null;availability_confirmed_at:string|null;current_plan_availability_windows:AvailabilityWindow[];current_plan_availability_time_zone:string|null;interested_count:number;availability_count:number;can_manage:boolean;suggestions:Suggestion[];groups:null|{viewerTimeZone:string;confirmed:string[];confirmedSchedules:ParticipantSchedule[];awaiting:string[];withdrawn:string[]}};

async function request(body?:unknown){const response=await fetch("/api/event-plans",body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"Planning requests could not be loaded.");return payload;}
function dateOnly(value:string){return String(value||"").slice(0,10);}

export default function EventPlanningBoard({duties,mounts,destinations,timeZone}:{duties:Duty[];mounts:Mount[];destinations:Destination[];timeZone:string}){
  const [plans,setPlans]=useState<Plan[]>([]),[open,setOpen]=useState(false),[editingId,setEditingId]=useState<number|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [type,setType]=useState("raid"),[dutyId,setDutyId]=useState(""),[mountId,setMountId]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[duration,setDuration]=useState("120"),[partySize,setPartySize]=useState("8"),[roles,setRoles]=useState(false),[channel,setChannel]=useState(destinations[0]?.id||"");
  const visibleDuties=useMemo(()=>duties.filter(duty=>duty.duty_type.toLowerCase()===type),[duties,type]);
  const selectedDuty=visibleDuties.find(duty=>String(duty.id)===dutyId);
  const matchingMounts=useMemo(()=>selectedDuty?mounts.filter(mount=>mount.source_name?.toLowerCase().includes(selectedDuty.name.toLowerCase())):[],[mounts,selectedDuty]);
  async function load(silent=false){if(!silent)setLoading(true);setError("");try{const payload=await request();setPlans(payload.plans||[]);}catch(caught){setError(caught instanceof Error?caught.message:"Planning requests could not be loaded.");}finally{if(!silent)setLoading(false);}}
  useEffect(()=>{void load();const refresh=()=>void load(true),timer=window.setInterval(refresh,15000);window.addEventListener("cotf:event-plans-refresh",refresh);return()=>{window.clearInterval(timer);window.removeEventListener("cotf:event-plans-refresh",refresh);};},[]);
  async function act(action:string,planId:number){setLoading(true);setError("");try{const payload=await request({action,planId});setPlans(payload.plans||[]);}catch(caught){setError(caught instanceof Error?caught.message:"The planning response could not be saved.");}finally{setLoading(false);}}
  async function create(event:React.FormEvent){event.preventDefault();setLoading(true);setError("");try{const plan={eventType:type,title,description,dutyId:dutyId?Number(dutyId):null,mountId:mountId?Number(mountId):null,level:selectedDuty?.level||null,partySize:Number(partySize),standardRoles:roles,startDate,endDate,durationMinutes:Number(duration),timeZone,targetChannelId:channel,targetChannelName:destinations.find(item=>item.id===channel)?.label||"Party Planner"};const payload=await request(editingId?{action:"update",planId:editingId,plan}:{action:"create",plan});setPlans(payload.plans||[]);setOpen(false);setEditingId(null);setTitle("");setDescription("");setStartDate("");setEndDate("");}catch(caught){setError(caught instanceof Error?caught.message:"The planning request could not be saved.");}finally{setLoading(false);}}
  function startNew(){setEditingId(null);setType("raid");setDutyId("");setMountId("");setTitle("");setDescription("");setStartDate("");setEndDate("");setDuration("120");setPartySize("8");setRoles(false);setChannel(destinations[0]?.id||"");setOpen(true);}
  function edit(plan:Plan){setEditingId(plan.id);setType(plan.event_type==="mount_farm"?"trial":plan.event_type);setDutyId(plan.duty_id?String(plan.duty_id):"");setMountId(plan.mount_id?String(plan.mount_id):"");setTitle(plan.title);setDescription(plan.description||"");setStartDate(dateOnly(plan.possible_start_date));setEndDate(dateOnly(plan.possible_end_date));setDuration(String(plan.duration_minutes));setPartySize(String(plan.party_size));setRoles(plan.standard_party_roles_required);setChannel(plan.target_channel_id||destinations[0]?.id||"");setOpen(true);}
  async function cancel(plan:Plan){if(!window.confirm(`Cancel “${plan.title}”? The Discord post will remain as a closed record, with its response buttons disabled.`))return;await act("cancel",plan.id);}
  function availability(plan:Plan){const usesPlanHours=plan.availability_source==="plan";window.dispatchEvent(new CustomEvent("cotf:availability-plan",{detail:{planId:plan.id,title:plan.title,usesPlanHours,windows:usesPlanHours?plan.current_plan_availability_windows:undefined,timeZone:usesPlanHours?plan.current_plan_availability_time_zone:undefined}}));}
  function schedule(plan:Plan,suggestion:Suggestion){window.dispatchEvent(new CustomEvent("cotf:plan-event",{detail:{startsAt:suggestion.startsAt,eventPlanId:plan.id,activityType:plan.event_type==="mount_farm"?"trial":plan.event_type,dutyId:plan.duty_id,title:plan.title,description:plan.description,partySize:plan.party_size,standardRoles:plan.standard_party_roles_required,mountFarm:plan.event_type==="mount_farm"}}));}
  return <section className="event-planning-board">
    <article className="panel member-event-wizard-launch"><div><span className="tag">Tentative Planning</span><h3>Collect Availability First</h3><p>Choose an activity and possible dates without committing to a final event time. Only members who explicitly join this request are included.</p></div><button type="button" className="button primary" onClick={startNew}>Start Planning Request</button></article>
    {error?<p className="availability-error" role="alert">{error}</p>:null}
    {plans.length?<div className="event-plan-grid">{plans.map(plan=><article key={plan.id} id={`event-plan-${plan.id}`} className="panel event-plan-card">
      {plan.duty_image_url||plan.mount_image_url?<img className="event-plan-artwork" src={plan.mount_image_url||plan.duty_image_url||""} alt="" />:null}
      <div className="event-plan-heading"><div><span className="tag">Collecting Availability</span><h3>{plan.title}</h3><p>{plan.duty_name||plan.event_type.replaceAll("_"," ")}{plan.level?` · Level ${plan.level}`:""}</p></div><div><strong>{plan.availability_count}/{plan.interested_count}</strong><small>interested members ready</small></div></div>
      <p>{dateOnly(plan.possible_start_date)} through {dateOnly(plan.possible_end_date)} · {plan.duration_minutes/60} hour{plan.duration_minutes===60?"":"s"} · organized by {plan.created_by}</p>{plan.description?<p>{plan.description}</p>:null}
      {plan.suggestions.length?<div className="event-plan-suggestions"><strong>Best current overlaps</strong>{plan.suggestions.map((suggestion,index)=><article key={suggestion.startsAt} className={index===0?"best":""}><div><span>{index===0?"Best match":`Option ${index+1}`}</span><strong>{suggestion.label}</strong><small>{suggestion.count} confirmed interested member{suggestion.count===1?"":"s"}{suggestion.count<plan.party_size?` · needs ${plan.party_size-suggestion.count} more for a full party`:" · full party possible"}</small>{suggestion.members.length?<small>Available: {suggestion.members.join(", ")}</small>:null}{plan.standard_party_roles_required?<small className="availability-stale">Tank, healer, and DPS roles still need confirmation.</small>:null}</div>{plan.can_manage?<button type="button" className="button secondary" onClick={()=>schedule(plan,suggestion)}>Use This Time</button>:null}</article>)}</div>:<p className="muted-copy">No complete overlap is available yet.</p>}
      <div className="form-actions">{plan.current_interest_status!=="interested"?<button type="button" className="button primary" disabled={loading} onClick={()=>void act("interest",plan.id)}>I&apos;m Interested</button>:<><button type="button" className="button secondary" onClick={()=>availability(plan)}>{plan.availability_source==="plan"?"Change Event-Specific Hours":"Set Event-Specific Hours"}</button><button type="button" className="ghost-button" disabled={loading} onClick={()=>void act("withdraw",plan.id)}>Withdraw</button></>}{plan.can_manage?<><button type="button" className="button secondary" onClick={()=>edit(plan)}>Edit Request</button><button type="button" className="button danger" disabled={loading} onClick={()=>void cancel(plan)}>Cancel Request</button></>:null}</div>
      {plan.groups?<details><summary>View plan-specific participants</summary><div className="event-plan-groups"><div><strong>Interested with availability ({plan.groups.confirmed.length})</strong><p>Times shown in your timezone: {plan.groups.viewerTimeZone}</p>{plan.groups.confirmedSchedules.length?<div className="event-plan-member-schedules">{plan.groups.confirmedSchedules.map(member=><article key={member.discordUserId}><strong>{member.name}</strong><small>{member.source==="plan"?"Event-specific hours":"Reusable availability"}{member.timeZone!==plan.groups!.viewerTimeZone?` · converted from ${member.timeZone}`:""}</small>{member.windows.length?member.windows.map((window,index)=><span key={`${member.discordUserId}-${index}`}>{window}</span>):<span>No availability falls within the possible event dates.</span>}</article>)}</div>:<p>None yet</p>}</div><div><strong>Interested, availability needed ({plan.groups.awaiting.length})</strong><p>{plan.groups.awaiting.join(", ")||"None"}</p></div>{plan.groups.withdrawn.length?<div><strong>Withdrawn</strong><p>{plan.groups.withdrawn.join(", ")}</p></div>:null}</div></details>:null}
    </article>)}</div>:!loading?<p className="muted-copy">No tentative planning requests are collecting availability.</p>:null}
    {open?<div className="giveaway-wizard-backdrop" role="presentation"><section className="giveaway-wizard availability-dialog" role="dialog" aria-modal="true" aria-labelledby="plan-create-title"><header className="giveaway-wizard-header"><div><p className="eyebrow">Tentative event</p><h3 id="plan-create-title">{editingId?"Edit Availability Request":"Collect Availability"}</h3></div><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Close</button></header><form className="giveaway-wizard-form" onSubmit={create}><div className="giveaway-wizard-step"><div className="giveaway-wizard-grid">
      <label><span>Activity</span><select value={type} onChange={event=>{setType(event.target.value);setDutyId("");setMountId("");}}><option value="raid">Raid</option><option value="trial">Trial / Mount Farm</option><option value="dungeon">Dungeon</option><option value="custom">Custom</option></select></label>
      <label className="full"><span>Duty</span><select value={dutyId} required={type!=="custom"} onChange={event=>{const value=event.target.value,set=visibleDuties.find(duty=>String(duty.id)===value);setDutyId(value);setPartySize(String(set?.party_size||8));setTitle(set?.name||title);}}><option value="">{type==="custom"?"No catalog duty":"Choose a duty"}</option>{visibleDuties.map(duty=><option key={duty.id} value={duty.id}>{duty.name}{duty.level?` · Level ${duty.level}`:""}</option>)}</select></label>
      {matchingMounts.length?<label className="full"><span>Mount target (optional)</span><select value={mountId} onChange={event=>setMountId(event.target.value)}><option value="">No mount target</option>{matchingMounts.map(mount=><option key={mount.id} value={mount.id}>{mount.mount_name}</option>)}</select></label>:null}
      <label className="full"><span>Planning title</span><input value={title} onChange={event=>setTitle(event.target.value)} required maxLength={150} /></label><label><span>Earliest possible date</span><input type="date" value={startDate} onChange={event=>{setStartDate(event.target.value);if(!endDate||endDate<event.target.value)setEndDate(event.target.value);}} required /></label><label><span>Latest possible date</span><input type="date" min={startDate} value={endDate} onChange={event=>setEndDate(event.target.value)} required /></label>
      <label><span>Expected duration</span><select value={duration} onChange={event=>setDuration(event.target.value)}><option value="60">1 hour</option><option value="90">1½ hours</option><option value="120">2 hours</option><option value="180">3 hours</option><option value="240">4 hours</option></select></label><label><span>Party size</span><input type="number" min="1" max="24" value={partySize} onChange={event=>setPartySize(event.target.value)} required /></label><label><span>Discord destination</span><select value={channel} onChange={event=>setChannel(event.target.value)} required>{destinations.map(destination=><option key={destination.id} value={destination.id}>{destination.label}</option>)}</select></label><label className="check"><input type="checkbox" checked={roles} onChange={event=>setRoles(event.target.checked)} /><span><strong>Standard party roles</strong><small>Consider tank, healer, and DPS coverage.</small></span></label><label className="full"><span>Details (optional)</span><textarea rows={5} value={description} onChange={event=>setDescription(event.target.value)} maxLength={1500} /></label>
    </div></div><footer className="giveaway-wizard-footer"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><span>{editingId?"Updates the existing site and Discord request":"Posts a compact availability request"}</span><button type="submit" className="button primary" disabled={loading||!channel}>{loading?"Saving…":editingId?"Save Changes":"Post Planning Request"}</button></footer></form></section></div>:null}
  </section>;
}
