"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { PollActor, PollDashboard, PollRecord } from "../../lib/polls/types";
import { cancelPollAction, createPollAction, deleteTestPollAction, editScheduledPollAction, endPollEarlyAction, resolvePollTieAction, savePollBallotAction } from "../../lib/polls/actions";

type Channel={id:string;label:string};
type Props={dashboard:PollDashboard;actor:PollActor;channels:Channel[];testChannelId:string|null};
const fmt=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Immediately";
const label=(value:string)=>value.split("_").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ");
function dateInput(value:string|null){if(!value)return"";const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value)),part=(type:string)=>parts.find(item=>item.type===type)?.value||"";return`${part("year")}-${part("month")}-${part("day")}T${part("hour")}:${part("minute")}`;}

function PollWizard({channels,testChannelId}:{channels:Channel[];testChannelId:string|null}){
  const [open,setOpen]=useState(false),[step,setStep]=useState(1),[pollType,setPollType]=useState("single"),[optionCount,setOptionCount]=useState(3),[maxSelections,setMaxSelections]=useState(2),[winnerCount,setWinnerCount]=useState(2),[isTest,setIsTest]=useState(false);
  const publishIntent=useRef(false);
  const needsOptions=!['yes_no','rating'].includes(pollType),image=pollType==='image';
  function close(){publishIntent.current=false;setOpen(false);setStep(1);}
  return <>
    <button className="button primary" type="button" onClick={()=>setOpen(true)}>Create Poll</button>
    {open?<div className="giveaway-wizard-backdrop" role="presentation"><section className="giveaway-wizard poll-wizard" role="dialog" aria-modal="true" aria-labelledby="poll-wizard-title">
      <header className="giveaway-wizard-header"><div><p className="eyebrow">Poll Setup · Step {step} of 4</p><h3 id="poll-wizard-title">Create a Poll</h3></div><button className="button secondary" type="button" onClick={close}>Close</button></header>
      <nav className="giveaway-wizard-progress" aria-label="Poll setup progress">{['Question','Choices','Delivery','Review'].map((name,index)=><button key={name} type="button" className={step===index+1?'active':step>index+1?'complete':''} onClick={()=>index+1<step&&setStep(index+1)}><span>{index+1}</span>{name}</button>)}</nav>
      <form action={async form=>{await createPollAction(form);close();}} className="giveaway-wizard-form" onInvalidCapture={()=>{publishIntent.current=false;}} onSubmit={event=>{if(!publishIntent.current){event.preventDefault();if(step<4)setStep(current=>Math.min(4,current+1));return;}publishIntent.current=false;}}>
        <input type="hidden" name="optionCount" value={needsOptions?optionCount:0}/>
        <section hidden={step!==1} className="giveaway-wizard-step"><div className="giveaway-wizard-intro"><h4>Question and voting method</h4><p>Choose how members will respond.</p></div><div className="giveaway-wizard-grid">
          <label className="full"><span>Question</span><input name="question" required maxLength={240} placeholder="What would you like the FC to decide?"/></label>
          <label className="full"><span>Description (optional)</span><textarea name="description" rows={4} maxLength={1500}/></label>
          <label><span>Poll type</span><select name="pollType" value={pollType} onChange={event=>setPollType(event.target.value)}><option value="single">Single choice</option><option value="multiple">Multiple choice</option><option value="yes_no">Yes / No / Abstain</option><option value="ranked">Ranked choice</option><option value="rating">Rating 1–5</option><option value="image">Image poll</option></select></label>
          {pollType==='multiple'?<><label><span>Maximum selections per voter</span><input name="maxSelections" type="number" min="1" max={optionCount} value={maxSelections} onChange={event=>{const value=Math.max(1,Math.min(optionCount,Number(event.target.value)||1));setMaxSelections(value);setWinnerCount(value);}}/></label><label><span>Number of winning choices</span><input name="winnerCount" type="number" min="1" max={optionCount} value={winnerCount} onChange={event=>setWinnerCount(Math.max(1,Math.min(optionCount,Number(event.target.value)||1)))}/><small>Defaults to the number of selections each voter may make.</small></label><label><span>Minimum selections per ballot (optional)</span><input name="minSelections" type="number" min="1" max={optionCount} placeholder="No minimum"/><small>A ballot must contain at least this many choices before it can be submitted.</small></label></>:null}
          {pollType==='ranked'?<label><span>Number to rank</span><select name="rankDepth" defaultValue="3"><option value="2">Top 2</option><option value="3">Top 3</option></select></label>:null}
          {pollType==='yes_no'?<label className="check"><input name="abstainEnabled" type="checkbox" defaultChecked/><span><strong>Include Abstain</strong></span></label>:null}
        </div></section>
        <section hidden={step!==2} className="giveaway-wizard-step"><div className="giveaway-wizard-intro"><h4>{needsOptions?'Add choices':'Built-in choices'}</h4><p>{pollType==='yes_no'?'Yes and No are included automatically.':pollType==='rating'?'Members will choose a rating from 1 through 5.':'Use clear, distinct choices. Image polls require one image for every choice.'}</p></div>
          {needsOptions?<><label><span>Number of choices</span><input type="number" min="2" max={image?10:25} value={optionCount} onChange={event=>setOptionCount(Math.max(2,Math.min(image?10:25,Number(event.target.value)||2)))}/></label>{image?<p className="giveaway-wizard-note">Upload only images you may publish. FFXIV screenshots remain subject to the current Materials Usage Policy.</p>:null}<div className="poll-option-editor">{Array.from({length:optionCount},(_,index)=><fieldset key={index}><legend>Choice {index+1}</legend><label><span>Label</span><input name={`optionLabel${index}`} required maxLength={100}/></label><label><span>Short description</span><input name={`optionDescription${index}`} maxLength={100}/></label>{image?<label><span>Image</span><input name={`optionImage${index}`} type="file" accept="image/jpeg,image/png,image/gif,image/webp" required/></label>:null}</fieldset>)}</div></>:<div className="giveaway-wizard-note"><strong>No setup required</strong><p>The standard choices will be generated automatically.</p></div>}
        </section>
        <section hidden={step!==3} className="giveaway-wizard-step"><div className="giveaway-wizard-intro"><h4>Privacy, schedule, and Discord</h4><p>Choose who can inspect ballots and where the poll is posted.</p></div><div className="giveaway-wizard-grid">
          <label><span>Ballot privacy</span><select name="privacyMode" defaultValue="private"><option value="public">Public to eligible FC members</option><option value="private">Private from members; officers can inspect</option><option value="anonymous">Fully anonymous from members and officers</option></select></label>
          <label><span>Results</span><select name="resultsVisibility" defaultValue="hidden_until_close"><option value="hidden_until_close">Hidden until close</option><option value="live">Live aggregates</option><option value="officer_only_until_close">Officers only until close</option></select></label>
          <label><span>Opens (optional, Central time)</span><input name="opensAt" type="datetime-local"/></label><label><span>Closes (Central time)</span><input name="closesAt" type="datetime-local" required/></label>
          <label><span>Discord channel</span><select name="channelId" required={!isTest} disabled={isTest} defaultValue=""><option value="">Choose a writable channel</option>{channels.map(channel=><option key={channel.id} value={channel.id}>{channel.label}</option>)}</select></label>
          <label><span>Minimum voters tallied (optional)</span><input name="quorumMinimum" type="number" min="1" placeholder="No minimum turnout"/><small>The number of submitted member ballots required for the poll result to qualify.</small></label>
          <label className="check"><input name="officerVotingEnabled" type="checkbox" defaultChecked/><span><strong>Allow officers to vote</strong></span></label><label className="check"><input name="postResults" type="checkbox" defaultChecked/><span><strong>Post results to Discord</strong></span></label>
          <label className="check"><input name="reminderMinutes" type="checkbox" value="1440"/><span><strong>24-hour reminder</strong></span></label><label className="check"><input name="reminderMinutes" type="checkbox" value="60"/><span><strong>1-hour reminder</strong></span></label>
          <label className="check full"><input name="isTest" type="checkbox" checked={isTest} disabled={!testChannelId} onChange={event=>setIsTest(event.target.checked)}/><span><strong>Disposable test poll</strong><small>{testChannelId?'Test polls are routed to the configured shared test channel.':'Configure a shared test channel first.'}</small></span></label>{isTest&&testChannelId?<input type="hidden" name="channelId" value={testChannelId}/>:null}
        </div></section>
        <section hidden={step!==4} className="giveaway-wizard-step"><div className="giveaway-wizard-intro"><h4>Review and publish</h4><p>The poll will post immediately unless a future opening time was selected.</p></div><div className="giveaway-review-card"><div><span>Type</span><strong>{label(pollType)}</strong></div><div><span>Choices</span><strong>{needsOptions?optionCount:pollType==='rating'?5:'2 or 3'}</strong></div>{pollType==='multiple'?<div><span>Winning choices</span><strong>{winnerCount}</strong></div>:null}<div><span>Voting</span><strong>Current FC + current Discord members</strong></div><div><span>Ties</span><strong>Extend, officer selection, or secure random choice</strong></div></div><div className="giveaway-wizard-note"><strong>Discord delivery is durable</strong><p>The bot tracks the exact message and retries temporary delivery failures without creating duplicate polls.</p></div></section>
        <footer className="giveaway-wizard-footer"><button className="button secondary" type="button" onClick={()=>step===1?close():setStep(step-1)}>{step===1?'Cancel':'Previous'}</button><span>Step {step} of 4</span>{step<4?<button className="button primary" type="button" onClick={()=>setStep(step+1)}>Next</button>:<button className="button primary" type="submit" onClick={()=>{publishIntent.current=true;}}>Finish and Publish</button>}</footer>
      </form>
    </section></div>:null}
  </>;
}

function ScheduledPollEditor({poll,channels}:{poll:PollRecord;channels:Channel[]}){
  const [open,setOpen]=useState(false),[pollType,setPollType]=useState<string>(poll.pollType),[optionCount,setOptionCount]=useState(Math.max(2,poll.choices.length)),[error,setError]=useState("");
  const needsOptions=!['yes_no','rating'].includes(pollType),image=pollType==='image';
  function close(){setError("");setOpen(false);}
  function changeType(value:string){setPollType(value);if(value==='image')setOptionCount(count=>Math.min(10,count));}
  return <>
    <button className="button secondary" type="button" onClick={()=>setOpen(true)}>Edit Scheduled Poll</button>
    {open?<div className="giveaway-wizard-backdrop" role="presentation"><section className="giveaway-wizard poll-wizard" role="dialog" aria-modal="true" aria-labelledby={`edit-poll-${poll.id}`}>
      <header className="giveaway-wizard-header"><div><p className="eyebrow">Scheduled Poll</p><h3 id={`edit-poll-${poll.id}`}>Edit Poll</h3></div><button className="button secondary" type="button" onClick={close}>Close</button></header>
      <form action={async form=>{setError("");try{await editScheduledPollAction(form);close();}catch(reason){setError(reason instanceof Error?reason.message:"The scheduled poll could not be updated.");}}} className="giveaway-wizard-form">
        <input type="hidden" name="pollId" value={poll.id}/><input type="hidden" name="optionCount" value={needsOptions?optionCount:0}/><input type="hidden" name="isTest" value={poll.isTest?'true':'false'}/>
        <section className="giveaway-wizard-step"><div className="giveaway-wizard-intro"><h4>Poll details and delivery</h4><p>Changes are accepted only while the poll is still scheduled and its opening time remains in the future.</p></div>{error?<p className="giveaway-wizard-error">{error}</p>:null}<div className="giveaway-wizard-grid">
          <label className="full"><span>Question</span><input name="question" required maxLength={240} defaultValue={poll.question}/></label><label className="full"><span>Description (optional)</span><textarea name="description" rows={3} maxLength={1500} defaultValue={poll.description}/></label>
          <label><span>Poll type</span><select name="pollType" value={pollType} onChange={event=>changeType(event.target.value)}><option value="single">Single choice</option><option value="multiple">Multiple choice</option><option value="yes_no">Yes / No / Abstain</option><option value="ranked">Ranked choice</option><option value="rating">Rating 1–5</option><option value="image">Image poll</option></select></label>
          {pollType==='multiple'?<><label><span>Maximum selections per voter</span><input name="maxSelections" type="number" min="1" max={optionCount} defaultValue={poll.maxSelections}/></label><label><span>Number of winning choices</span><input name="winnerCount" type="number" min="1" max={optionCount} defaultValue={poll.winnerCount}/></label><label><span>Minimum selections per ballot (optional)</span><input name="minSelections" type="number" min="1" max={optionCount} defaultValue={poll.minSelections??""} placeholder="No minimum"/></label></>:null}{pollType==='ranked'?<label><span>Number to rank</span><select name="rankDepth" defaultValue={poll.rankDepth}><option value="2">Top 2</option><option value="3">Top 3</option></select></label>:null}{pollType==='yes_no'?<label className="check"><input name="abstainEnabled" type="checkbox" defaultChecked={poll.abstainEnabled}/><span><strong>Include Abstain</strong></span></label>:null}
        </div>
        {needsOptions?<><div className="giveaway-wizard-divider">Choices</div><label><span>Number of choices</span><input type="number" min="2" max={image?10:25} value={optionCount} onChange={event=>setOptionCount(Math.max(2,Math.min(image?10:25,Number(event.target.value)||2)))}/></label><div className="poll-option-editor">{Array.from({length:optionCount},(_,index)=>{const choice=poll.choices[index];return <fieldset key={index}><legend>Choice {index+1}</legend>{choice?<input type="hidden" name={`optionExistingId${index}`} value={choice.id}/>:null}<label><span>Label</span><input name={`optionLabel${index}`} required maxLength={100} defaultValue={choice?.label||""}/></label><label><span>Short description</span><input name={`optionDescription${index}`} maxLength={100} defaultValue={choice?.description||""}/></label>{image?<label><span>{choice?.hasImage?'Replacement image (optional)':'Image'}</span><input name={`optionImage${index}`} type="file" accept="image/jpeg,image/png,image/gif,image/webp" required={!choice?.hasImage}/>{choice?.hasImage?<small>The current image will be retained if this is left blank.</small>:null}</label>:null}</fieldset>})}</div></>:<div className="giveaway-wizard-note"><strong>Built-in choices</strong><p>The standard choices will be regenerated when you save.</p></div>}
        <div className="giveaway-wizard-divider">Privacy, schedule, and Discord</div><div className="giveaway-wizard-grid">
          <label><span>Ballot privacy</span><select name="privacyMode" defaultValue={poll.privacyMode}><option value="public">Public to eligible FC members</option><option value="private">Private from members; officers can inspect</option><option value="anonymous">Fully anonymous from members and officers</option></select></label><label><span>Results</span><select name="resultsVisibility" defaultValue={poll.resultsVisibility}><option value="hidden_until_close">Hidden until close</option><option value="live">Live aggregates</option><option value="officer_only_until_close">Officers only until close</option></select></label>
          <label><span>Opens (Central time)</span><input name="opensAt" type="datetime-local" required defaultValue={dateInput(poll.opensAt)}/></label><label><span>Closes (Central time)</span><input name="closesAt" type="datetime-local" required defaultValue={dateInput(poll.closesAt)}/></label>
          <label><span>Discord channel</span><select name="channelId" required disabled={poll.isTest} defaultValue={poll.channelId}>{channels.map(channel=><option key={channel.id} value={channel.id}>{channel.label}</option>)}</select>{poll.isTest?<><input type="hidden" name="channelId" value={poll.channelId}/><small>Disposable tests remain in the configured test channel.</small></>:null}</label><label><span>Minimum voters tallied (optional)</span><input name="quorumMinimum" type="number" min="1" defaultValue={poll.quorumMinimum??""} placeholder="No minimum turnout"/></label>
          <label className="check"><input name="officerVotingEnabled" type="checkbox" defaultChecked={poll.officerVotingEnabled}/><span><strong>Allow officers to vote</strong></span></label><label className="check"><input name="postResults" type="checkbox" defaultChecked={poll.postResults}/><span><strong>Post results to Discord</strong></span></label><label className="check"><input name="reminderMinutes" type="checkbox" value="1440" defaultChecked={poll.reminders.includes(1440)}/><span><strong>24-hour reminder</strong></span></label><label className="check"><input name="reminderMinutes" type="checkbox" value="60" defaultChecked={poll.reminders.includes(60)}/><span><strong>1-hour reminder</strong></span></label>
        </div></section>
        <footer className="giveaway-wizard-footer"><button className="button secondary" type="button" onClick={close}>Cancel</button><span>Not yet posted to Discord</span><button className="button primary" type="submit">Save Changes</button></footer>
      </form>
    </section></div>:null}
  </>;
}

function PollLeaderGraph({poll,actor}:{poll:PollRecord;actor:PollActor}){
  const [open,setOpen]=useState(false),[expanded,setExpanded]=useState(false);
  const canView=actor.isOfficer||(poll.privacyMode==='public'&&Boolean(actor.characterId));
  const hasMetrics=poll.choices.some(choice=>choice.voteCount!==null);
  if(!canView||!hasMetrics)return null;
  const metric=(choice:PollRecord["choices"][number])=>poll.pollType==='ranked'?choice.score||0:choice.voteCount||0;
  const sorted=[...poll.choices].sort((left,right)=>metric(right)-metric(left)||left.sortOrder-right.sortOrder);
  const winningSlots=Math.max(1,Math.min(poll.winnerCount,sorted.length));
  const hasVotes=sorted.some(choice=>metric(choice)>0);
  const cutoff=sorted[Math.min(winningSlots,sorted.length)-1]?metric(sorted[Math.min(winningSlots,sorted.length)-1]):0;
  const leaders=hasVotes?sorted.filter(choice=>metric(choice)>=cutoff):[];
  const includesCutoffTie=leaders.length>winningSlots;
  const visibleChoices=expanded?sorted:leaders;
  const maximum=Math.max(1,...visibleChoices.map(metric));
  const total=Math.max(1,poll.voteCount);
  const summary=hasVotes?(includesCutoffTie?'Top '+winningSlots+' plus '+(leaders.length-winningSlots)+' tied at the cutoff':'Top '+winningSlots):'No votes yet';
  function close(){setOpen(false);setExpanded(false);}
  return <><button className="button secondary poll-graph-button" type="button" onClick={()=>setOpen(true)}>Graph</button>{open?<div className="giveaway-wizard-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close();}}><section className="giveaway-wizard poll-graph-dialog" role="dialog" aria-modal="true" aria-labelledby={`poll-graph-title-${poll.id}`}><header className="giveaway-wizard-header"><div><p className="eyebrow">Poll Standings</p><h3 id={`poll-graph-title-${poll.id}`}>{poll.question}</h3><p>{expanded?'Full standings · '+sorted.length+' choices':summary}</p></div><button className="button secondary" type="button" onClick={close}>Close</button></header><div className="poll-graph-content">{hasVotes?<div className="poll-leader-results" role="list" aria-label={'Current poll standings for '+poll.question}>{visibleChoices.map(choice=>{const value=metric(choice),rank=sorted.findIndex(item=>metric(item)===value)+1;return <div key={choice.id} role="listitem" className="poll-leader-row"><div><span className="poll-leader-rank">{rank}</span><strong>{choice.label}</strong><span>{poll.pollType==='ranked'?value+' points':value+' ('+Math.round((value/total)*100)+'%)'}</span></div><progress max={maximum} value={value}/></div>})}</div>:<p className="muted">The graph will appear after the first counted vote.</p>}</div><footer className="giveaway-wizard-footer"><span>{expanded?'All '+sorted.length+' choices':summary}</span>{hasVotes&&sorted.length>leaders.length?<button className="button secondary" type="button" aria-expanded={expanded} onClick={()=>setExpanded(value=>!value)}>{expanded?'Show Leaders':'Expand Full List'}</button>:null}<button className="button primary" type="button" onClick={close}>Done</button></footer></section></div>:null}</>;
}

function PollChoiceResults({poll,actor}:{poll:PollRecord;actor:PollActor}){
  const canView=actor.isOfficer||(poll.privacyMode==='public'&&Boolean(actor.characterId));
  const hasMetrics=poll.choices.some(choice=>choice.voteCount!==null);
  if(!canView||!hasMetrics)return null;
  const metric=(choice:PollRecord["choices"][number])=>poll.pollType==='ranked'?choice.score||0:choice.voteCount||0;
  const total=Math.max(1,poll.voteCount);
  const maximum=poll.pollType==='ranked'?Math.max(1,...poll.choices.map(metric)):total;
  return <div className="poll-results" aria-label={'Vote totals for '+poll.question}>{poll.choices.map(choice=>{const value=metric(choice);return <div key={choice.id}><div><strong>{choice.label}</strong><span>{poll.pollType==='ranked'?value+' points':value+' ('+Math.round((value/total)*100)+'%)'}</span></div><progress max={maximum} value={value}/></div>})}</div>;
}

function BallotForm({poll}:{poll:PollRecord}){
  const ranks=Array.from({length:poll.rankDepth},(_,index)=>index+1),router=useRouter();
  const [submission,setSubmission]=useState<{state:"idle"|"saving"|"saved"|"error";message:string}>({state:"idle",message:""});
  const wasUpdate=poll.viewerHasBallot;
  async function submit(formData:FormData){
    setSubmission({state:"saving",message:wasUpdate?"Updating your vote…":"Submitting your vote…"});
    try{
      await savePollBallotAction(formData);
      setSubmission({state:"saved",message:wasUpdate?"Your updated vote was accepted.":"Your vote was accepted."});
      router.refresh();
    }catch(reason){
      setSubmission({state:"error",message:reason instanceof Error?reason.message:"Your vote could not be saved. Please try again."});
    }
  }
  function changed(){if(submission.state!=="idle")setSubmission({state:"idle",message:""});}
  return <form action={submit} onChange={changed} className="poll-ballot-form">
    <input type="hidden" name="pollId" value={poll.id}/><input type="hidden" name="pollType" value={poll.pollType}/>
    {poll.pollType==='multiple'&&poll.minSelections?<p className="poll-selection-requirement">Choose between {poll.minSelections} and {poll.maxSelections} options.</p>:null}
    {poll.pollType==='ranked'?<div className="poll-ranks">{ranks.map(rank=><label key={rank}><span>Rank {rank}</span><select name={`rank${rank}`} required defaultValue={poll.viewerRanks[rank]?String(poll.viewerRanks[rank]):""}><option value="">Choose an option</option>{poll.choices.map(choice=><option key={choice.id} value={choice.id}>{choice.label}</option>)}</select></label>)}</div>:<div className={`poll-choice-list ${poll.pollType==='image'?'images':''}`}>{poll.choices.map(choice=><label key={choice.id} className={choice.viewerSelected?'selected':''}>{choice.hasImage?<img src={`/api/polls/images/${choice.id}`} alt=""/>:null}<span><input name="choiceId" type={poll.pollType==='multiple'?'checkbox':'radio'} value={choice.id} defaultChecked={choice.viewerSelected}/><strong>{choice.label}</strong>{choice.description?<small>{choice.description}</small>:null}</span></label>)}</div>}
    <button className="button primary" type="submit" disabled={submission.state==="saving"}>{submission.state==="saving"?(wasUpdate?'Updating…':'Submitting…'):submission.state==="saved"?'✓ Vote Accepted':wasUpdate?'Update My Vote':'Submit Vote'}</button>
    <p className={`poll-ballot-status ${submission.state}`} role="status" aria-live="polite">{submission.message}</p>
  </form>
}

function PollTieControls({poll}:{poll:PollRecord}){
  const metric=(choice:PollRecord["choices"][number])=>poll.pollType==='ranked'?choice.score||0:choice.voteCount||0;
  const sorted=[...poll.choices].sort((left,right)=>metric(right)-metric(left)||left.sortOrder-right.sortOrder);
  const cutoff=metric(sorted[Math.max(0,Math.min(poll.winnerCount,sorted.length)-1)]);
  const tied=sorted.filter(choice=>metric(choice)===cutoff&&!poll.winnerChoiceIds.includes(choice.id));
  const remaining=Math.max(1,poll.winnerCount-poll.winnerChoiceIds.length);
  return <div className="poll-tie-controls"><h4>Resolve Winning Cutoff</h4><p>{remaining} winner slot{remaining===1?'':'s'} remain. Select from the choices tied at the cutoff, extend voting, or fill the remaining slots randomly.</p><form action={resolvePollTieAction}><input type="hidden" name="pollId" value={poll.id}/><input type="hidden" name="resolutionMode" value="extend"/><label><span>New closing time</span><input name="newClosesAt" type="datetime-local" required/></label><button className="button secondary" type="submit">Extend Voting</button></form><form action={resolvePollTieAction}><input type="hidden" name="pollId" value={poll.id}/><input type="hidden" name="resolutionMode" value="officer"/><select name="choiceId" required defaultValue=""><option value="">Choose a tied winner</option>{tied.map(choice=><option key={choice.id} value={choice.id}>{choice.label}</option>)}</select><button className="button secondary" type="submit">Confirm This Winner</button></form><form action={resolvePollTieAction}><input type="hidden" name="pollId" value={poll.id}/><input type="hidden" name="resolutionMode" value="random"/><button className="button primary" type="submit">Randomly Fill Remaining Slots</button></form></div>;
}

function PollWinners({poll}:{poll:PollRecord}){
  const metric=(choice:PollRecord["choices"][number])=>poll.pollType==='ranked'?choice.score||0:choice.voteCount||0;
  const sorted=[...poll.choices].sort((left,right)=>metric(right)-metric(left)||left.sortOrder-right.sortOrder);
  const winners=poll.winnerChoiceIds.map(choiceId=>sorted.find(choice=>choice.id===choiceId)).filter((choice):choice is PollRecord["choices"][number]=>Boolean(choice));
  return <div className="poll-winner"><strong>{winners.length===1?'Result':'Winning choices'}:</strong><ol>{winners.map(choice=>{const value=metric(choice),rank=sorted.findIndex(item=>metric(item)===value)+1,tied=sorted.filter(item=>metric(item)===value).length>1;return <li key={choice.id}><span className="poll-winner-rank">{tied?'T':''}{rank}</span>{choice.label}</li>})}</ol></div>;
}

function PollCard({poll,actor,channels}:{poll:PollRecord;actor:PollActor;channels:Channel[]}){return <article className={`panel poll-card ${poll.isTest?'test':''}`}><header><div><div className="giveaway-tags"><span className="tag">{label(poll.pollType)}</span><span className="tag">{label(poll.privacyMode)}</span><span className="tag">{label(poll.status)}</span>{poll.isTest?<span className="tag warning">Test</span>:null}</div><h3>{poll.question}</h3>{poll.description?<p>{poll.description}</p>:null}</div><div className="poll-count"><strong>{poll.voteCount}</strong><span>voter{poll.voteCount===1?'':'s'} tallied</span></div></header><div className="poll-facts">{poll.status==='scheduled'?<span>Opens {fmt(poll.opensAt)}</span>:null}<span>Closes {fmt(poll.closesAt)}</span><span>Posts in {poll.channelName}</span>{poll.winnerCount>1?<span>{poll.winnerCount} winning choices</span>:null}{poll.quorumMinimum?<span>Minimum voters: {poll.voteCount}/{poll.quorumMinimum}</span>:null}{poll.minSelections?<span>Each ballot requires {poll.minSelections}–{poll.maxSelections} choices</span>:null}</div>
    <PollLeaderGraph poll={poll} actor={actor}/>
    <PollChoiceResults poll={poll} actor={actor}/>
    {poll.status==='open'&&actor.characterId?<BallotForm poll={poll}/>:poll.status==='open'?<p className="status-badge warning">{actor.discordUserId?'Current FC and Discord membership is required.':'Sign in to vote.'}</p>:null}
    {poll.status==='closed'&&poll.winnerChoiceIds.length?<PollWinners poll={poll}/>:null}
    {poll.status==='closed'&&!poll.winnerChoiceIds.length&&poll.resolutionNote?<p className="poll-winner"><strong>Result:</strong> {poll.resolutionNote}</p>:null}
    {actor.isOfficer?<details className="giveaway-officer-controls"><summary>Officer Insights and Controls</summary><div className="poll-officer-insights"><p><strong>Privacy:</strong> {poll.privacyMode==='anonymous'?'Ballot identities are unavailable to officers.':poll.privacyMode==='private'?'Individual ballots are visible only here.':'Eligible signed-in members can see ballots when results are visible.'}</p>{poll.ballots.length?<div className="poll-ballot-details">{poll.ballots.map(ballot=><div key={ballot.id}><strong>{ballot.voterLabel}</strong><span>{ballot.selections.join(', ')}</span><small>{ballot.counted?'Counted':`Excluded: ${ballot.invalidationReason||'Ineligible'}`} · {fmt(ballot.submittedAt)}</small></div>)}</div>:poll.privacyMode==='anonymous'?<p>Anonymous turnout: {poll.voteCount}. No identity list is stored for officer display.</p>:<p>No inspectable ballots.</p>}<div className="giveaway-officer-actions">{poll.status==='scheduled'?<ScheduledPollEditor poll={poll} channels={channels}/>:null}{poll.status==='open'?<form action={endPollEarlyAction}><input type="hidden" name="pollId" value={poll.id}/><button className="button secondary" type="submit">End Poll Early</button></form>:null}{!['closed','cancelled'].includes(poll.status)?<form action={cancelPollAction}><input type="hidden" name="pollId" value={poll.id}/><button className="danger-button" type="submit">Cancel Poll</button></form>:null}{poll.isTest?<form action={deleteTestPollAction}><input type="hidden" name="pollId" value={poll.id}/><button className="danger-button" type="submit">Delete Test Poll</button></form>:null}</div>{poll.status==='awaiting_tie'?<PollTieControls poll={poll}/>:null}</div></details>:null}
  </article>}

export default function PollsView({dashboard,actor,channels,testChannelId}:Props){
  const router=useRouter(),[refreshing,setRefreshing]=useState(false);
  const sections=useMemo(()=>[{key:'active',title:'Active Polls',items:dashboard.active},{key:'upcoming',title:'Upcoming Polls',items:dashboard.upcoming},{key:'history',title:'Poll History',items:dashboard.history}], [dashboard]);
  function refresh(){if(document.visibilityState!=="visible")return;setRefreshing(true);router.refresh();window.setTimeout(()=>setRefreshing(false),750);}
  useEffect(()=>{if(!dashboard.active.length)return;const timer=window.setInterval(refresh,15000);window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);return()=>{window.clearInterval(timer);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh);};},[dashboard.active.length,router]);
  return <section id="polls" className="section-block poll-view"><div className="section-title-row"><div><p className="eyebrow">FC Voting</p><h2>Polls</h2><p>Vote on Free Company plans and decisions. Active ballots refresh automatically when Discord votes change.</p></div><div className="section-title-actions"><button className="button secondary" type="button" onClick={refresh} disabled={refreshing}>{refreshing?'Refreshing…':'Refresh Polls'}</button>{actor.isOfficer?<PollWizard channels={channels} testChannelId={testChannelId}/>:null}</div></div><div className="giveaway-summary"><div><span>Active</span><strong>{dashboard.active.length}</strong></div><div><span>Upcoming</span><strong>{dashboard.upcoming.length}</strong></div><div><span>Completed</span><strong>{dashboard.history.filter(item=>item.status==='closed').length}</strong></div></div>{sections.map(section=><section className="giveaway-section" key={section.key}><h3>{section.title}</h3>{section.items.length?<div className="giveaway-list">{section.items.map(poll=><PollCard key={poll.id} poll={poll} actor={actor} channels={channels}/>)}</div>:<div className="empty-state"><p>No {section.title.toLowerCase()}.</p></div>}</section>)}{actor.isOfficer&&dashboard.tests.length?<section className="giveaway-section"><h3>Disposable Tests</h3><div className="giveaway-list">{dashboard.tests.map(poll=><PollCard key={poll.id} poll={poll} actor={actor} channels={channels}/>)}</div></section>:null}{actor.isOfficer?<details className="panel poll-audit"><summary>Poll Administration History</summary>{dashboard.audit.map(entry=><div key={entry.id}><strong>{label(entry.actionType)}</strong><span>{entry.pollQuestion||'Poll service'} · {entry.actorLabel||'Automation'}</span><small>{fmt(entry.createdAt)}</small></div>)}</details>:null}</section>}
