import {ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,MessageFlags,ModalBuilder,StringSelectMenuBuilder,TextInputBuilder,TextInputStyle} from "discord.js";
import { analyzeTreasureMapImage, hashTreasureMapImage, treasureHashConfidence, treasureHashDistance } from "./treasure-map-image.mjs";
import { bootstrapTreasureMapCatalog, readBundledTreasureTypes } from "./treasure-map-catalog.mjs";
import { readTreasureMapLabels } from "./treasure-map-ocr.mjs";

const TYPES=await readBundledTreasureTypes();
const row=(...items)=>new ActionRowBuilder().addComponents(...items),type=value=>TYPES.find(item=>item.value===value),short=(value,n=280)=>String(value||"").slice(0,n);
let ready;

export function addTreasureMapCommand(command){return command.addSubcommand(sub=>sub.setName("map").setDescription("Privately identify a treasure-map screenshot.").addAttachmentOption(option=>option.setName("image").setDescription("Treasure-map screenshot").setRequired(true)));}
export async function ensureTreasureMapSchema(pool){
  if(!ready)ready=pool.query(`
    create table if not exists portal_treasure_map_scans(id bigserial primary key,source_kind text not null,requester_discord_id text not null,source_channel_id text,source_message_id text,response_message_id text,image_mime text not null,image_data bytea,image_hash text not null,matched_reference_id bigint,confidence numeric(5,4),created_at timestamptz not null default now(),expires_at timestamptz not null default(now()+interval '15 minutes'));
    create table if not exists portal_treasure_map_references(id bigserial primary key,map_type text not null,zone_name text not null,coordinate_x numeric(5,1) not null,coordinate_y numeric(5,1) not null,party_size integer not null,image_hash text not null,review_status text not null default 'pending' check(review_status in('pending','approved','rejected')),submitted_by text,reviewed_by text,reviewed_at timestamptz,created_at timestamptz not null default now());
    create index if not exists portal_treasure_map_reference_match_idx on portal_treasure_map_references(review_status,map_type,zone_name);
    create table if not exists portal_treasure_map_corrections(id bigserial primary key,scan_id bigint not null references portal_treasure_map_scans(id) on delete cascade,reference_id bigint references portal_treasure_map_references(id) on delete set null,map_type text not null,zone_name text not null,coordinate_x numeric(5,1) not null,coordinate_y numeric(5,1) not null,submitted_by text not null,review_status text not null default 'pending' check(review_status in('pending','approved','rejected')),reviewed_by text,reviewed_at timestamptz,created_at timestamptz not null default now());
    create index if not exists portal_treasure_map_scan_expiry_idx on portal_treasure_map_scans(expires_at) where image_data is not null;
    alter table portal_treasure_map_scans add column if not exists detected_zone_name text;
    alter table portal_treasure_map_scans add column if not exists detected_party_size integer;
    alter table portal_treasure_map_scans add column if not exists detected_zone_confidence numeric(5,4);
    alter table portal_treasure_map_scans add column if not exists selected_map_type text;
  `).catch(error=>{ready=null;throw error;});return ready;
}
async function download(attachment){const mime=String(attachment?.contentType||"").toLowerCase();if(!mime.startsWith("image/"))throw new Error("Attach a PNG, JPG, or WebP treasure-map screenshot.");if(Number(attachment.size||0)>15*1024*1024)throw new Error("The image must be 15 MB or smaller.");const response=await fetch(attachment.url);if(!response.ok)throw new Error(`Discord could not provide the image (${response.status}).`);const buffer=Buffer.from(await response.arrayBuffer());if(!buffer.length||buffer.length>15*1024*1024)throw new Error("The image must be 15 MB or smaller.");const analysis=await analyzeTreasureMapImage(buffer);if(!analysis.isMap){const error=new Error("That image does not look like a deciphered treasure map.");error.code="NOT_TREASURE_MAP";throw error;}return {buffer,mime,card:analysis.card,hash:await hashTreasureMapImage(buffer)};}
async function matches(pool,hash,{zoneName=null,partySize=null}={}){
  if(!zoneName||![1,4,8].includes(Number(partySize)))return [];
  const found=await pool.query(`select * from portal_treasure_map_references where review_status='approved' and zone_name=$1 and party_size=$2`,[zoneName,partySize]);
  const ranked=found.rows.map(item=>{const difference=treasureHashDistance(hash,item.image_hash);return {...item,difference,confidence:treasureHashConfidence(hash,item.image_hash)};}).filter(item=>Number.isFinite(item.difference)).sort((a,b)=>(a.difference-b.difference)||(Number(b.reference_kind==="exact")-Number(a.reference_kind==="exact")));
  const unique=[];
  for(const item of ranked){const key=`${item.zone_name}:${Number(item.coordinate_x).toFixed(1)}:${Number(item.coordinate_y).toFixed(1)}`;if(unique.some(entry=>entry.locationKey===key))continue;unique.push({...item,locationKey:key});if(unique.length===4)break;}
  return unique;
}
function embed(match,alternatives=[],detected={}){
  if(!match){
    const filters=detected.zoneName||detected.partySize?`\n\n**Read from image:** ${detected.zoneName||"zone unclear"} · ${detected.partySize?`${detected.partySize} player${detected.partySize===1?"":"s"}`:"player count unclear"}`:"";
    const candidates=alternatives.length?`**Closest known locations**\n${alternatives.map((item,index)=>`${index+1}. **X ${Number(item.coordinate_x).toFixed(1)}, Y ${Number(item.coordinate_y).toFixed(1)}** — ${Math.round(item.confidence*100)}%`).join("\n")}`:"No approved reference matches both the detected zone and player count yet.";
    return new EmbedBuilder().setColor(0xf59e0b).setTitle("[MAP NEEDS CONFIRMATION]").setDescription(`I recognized the treasure-map card but could not make a safe location match yet.${filters}\n\n${candidates}\n\nUse **Confirm / Choose Location** to select from every known coordinate. Use **Correct Filters / Rescan** only when the player count, map family, or zone is wrong.`).setFooter({text:"Member-submitted corrections require officer approval before training. Raw image cache expires after 15 minutes. FFXIV materials © SQUARE ENIX"});
  }
  return new EmbedBuilder().setColor(0x8b5cf6).setTitle("[MAP MATCHED]").setDescription(`**Treasure map location**\n**Zone:** ${match.zone_name}\n**Coordinates:** X ${Number(match.coordinate_x).toFixed(1)}, Y ${Number(match.coordinate_y).toFixed(1)}\n**Recommended party:** ${match.party_size} player${Number(match.party_size)===1?"":"s"}\n**Confidence:** ${Math.round(match.confidence*100)}%`).setFooter({text:"Use Confirm / Change Location if this is not correct. Raw image cache expires after 15 minutes. FFXIV materials © SQUARE ENIX"});
}
function components(scanId,portalUrl,needsConfirmation=false){const buttons=[new ButtonBuilder().setCustomId(`map:locations:${scanId}`).setStyle(ButtonStyle.Primary).setLabel(needsConfirmation?"Confirm / Choose Location":"Confirm / Change Location"),new ButtonBuilder().setCustomId(`map:correct:${scanId}`).setStyle(ButtonStyle.Secondary).setLabel("Correct Filters / Rescan")];if(portalUrl)buttons.push(new ButtonBuilder().setStyle(ButtonStyle.Link).setLabel("Open Map Guide").setURL(new URL("?view=guides&guide=treasure-map-identification#guides",portalUrl).toString()));return [row(...buttons)];}
async function scan({pool,attachment,sourceKind,userId,channelId,messageId}){
  await ensureTreasureMapSchema(pool);
  await bootstrapTreasureMapCatalog(pool);
  await pool.query(`update portal_treasure_map_scans set image_data=null where image_data is not null and expires_at<=now()`);
  const image=await download(attachment);
  const zones=(await pool.query(`select distinct zone_name from portal_treasure_map_references where review_status='approved' order by zone_name`)).rows.map(item=>item.zone_name);
  let detected=await readTreasureMapLabels(image.card,zones);
  if(!detected.zoneName||!detected.partySize){const fallback=await readTreasureMapLabels(image.buffer,zones);detected={zoneName:detected.zoneName||fallback.zoneName,zoneConfidence:detected.zoneName?detected.zoneConfidence:fallback.zoneConfidence,partySize:detected.partySize||fallback.partySize,rawZone:detected.rawZone||fallback.rawZone};}
  const possible=await matches(pool,image.hash,detected);
  const top=possible[0],runnerUp=possible[1],threshold=top?.reference_kind==="generated"?.62:.73;
  const match=top?.confidence>=threshold&&(!runnerUp||top.confidence-runnerUp.confidence>=.02)?top:null;
  const saved=await pool.query(`insert into portal_treasure_map_scans(source_kind,requester_discord_id,source_channel_id,source_message_id,image_mime,image_data,image_hash,matched_reference_id,confidence,detected_zone_name,detected_party_size,detected_zone_confidence,expires_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now()+interval '15 minutes') returning id`,[sourceKind,userId,channelId||null,messageId||null,image.mime,image.buffer,image.hash,match?.id||null,top?.confidence||null,detected.zoneName,detected.partySize,detected.zoneConfidence]);
  return {id:saved.rows[0].id,match,possible,detected};
}
export async function handleTreasureMapCommand(interaction,pool,{portalUrl=""}={}){await interaction.deferReply({flags:MessageFlags.Ephemeral});try{const result=await scan({pool,attachment:interaction.options.getAttachment("image",true),sourceKind:"slash",userId:interaction.user.id,channelId:interaction.channelId});await interaction.editReply({embeds:[embed(result.match,result.possible,result.detected)],components:components(result.id,portalUrl,!result.match)});}catch(error){await interaction.editReply({content:`I could not read that map image: ${short(error?.message||error)}`,embeds:[],components:[]});}}
export async function handleTreasureMapContextCommand(interaction,pool,{portalUrl=""}={}){await interaction.deferReply({flags:MessageFlags.Ephemeral});try{const attachment=interaction.targetMessage?.attachments?.find(item=>String(item.contentType||"").startsWith("image/"));if(!attachment)throw new Error("The selected message does not contain an image attachment.");const result=await scan({pool,attachment,sourceKind:"context",userId:interaction.user.id,channelId:interaction.channelId,messageId:interaction.targetMessage.id});await interaction.editReply({embeds:[embed(result.match,result.possible,result.detected)],components:components(result.id,portalUrl,!result.match)});}catch(error){await interaction.editReply({content:`I could not read that map image: ${short(error?.message||error)}`,embeds:[],components:[]});}}
export async function handleTreasureMapChannelMessage(message,pool,settings,{portalUrl=""}={}){if(!settings.treasure_map_channel_id||!settings.treasure_map_auto_enabled||message.channelId!==settings.treasure_map_channel_id||message.author?.bot)return false;const attachment=message.attachments.find(item=>String(item.contentType||"").startsWith("image/"));if(!attachment)return false;try{const result=await scan({pool,attachment,sourceKind:"channel",userId:message.author.id,channelId:message.channelId,messageId:message.id});const reply=await message.reply({embeds:[embed(result.match,result.possible,result.detected)],components:components(result.id,portalUrl,!result.match),allowedMentions:{repliedUser:false}});await pool.query(`update portal_treasure_map_scans set response_message_id=$2 where id=$1`,[result.id,reply.id]);}catch(error){if(error?.code==="NOT_TREASURE_MAP")return false;await message.reply({content:`I could not read that treasure map: ${short(error?.message||error,240)}`,allowedMentions:{repliedUser:false}}).catch(()=>null);}return true;}
async function ownedScan(pool,id,userId,officer){const scan=(await pool.query(`select * from portal_treasure_map_scans where id=$1`,[id])).rows[0];if(!scan)throw new Error("That map result is no longer available.");if(!officer&&scan.requester_discord_id!==userId)throw new Error("Only the map uploader or an officer can correct this result.");return scan;}
function coordinateModal(id,chosen,zone){return new ModalBuilder().setCustomId(`map:coordinates:${id}:${chosen.value}`).setTitle("Confirm treasure location").addComponents(row(new TextInputBuilder().setCustomId("zone").setLabel("Zone").setValue(zone).setStyle(TextInputStyle.Short).setRequired(true)),row(new TextInputBuilder().setCustomId("x").setLabel("X coordinate").setPlaceholder("Example: 14.0").setStyle(TextInputStyle.Short).setRequired(true)),row(new TextInputBuilder().setCustomId("y").setLabel("Y coordinate").setPlaceholder("Example: 27.0").setStyle(TextInputStyle.Short).setRequired(true)));}
async function knownLocations(pool,source,chosen,zone){const party=chosen?.party||Number(source.detected_party_size),found=chosen?await pool.query(`select * from portal_treasure_map_references where review_status='approved' and map_type=$1 and zone_name=$2 and party_size=$3`,[chosen.value,zone,party]):await pool.query(`select * from portal_treasure_map_references where review_status='approved' and zone_name=$1 and party_size=$2`,[zone,party]);const ranked=found.rows.map(item=>({...item,confidence:treasureHashConfidence(source.image_hash,item.image_hash)})).sort((a,b)=>b.confidence-a.confidence),unique=[];for(const item of ranked){const key=`${Number(item.coordinate_x).toFixed(1)}:${Number(item.coordinate_y).toFixed(1)}`;if(unique.some(entry=>entry.key===key))continue;unique.push({...item,key});}return unique;}
function locationPicker(id,locations,mapType="any"){return new StringSelectMenuBuilder().setCustomId(`map:location:${id}:${mapType}`).setPlaceholder("Confirm the marked location").addOptions(locations.slice(0,25).map((item,index)=>({label:`${index+1}. X ${Number(item.coordinate_x).toFixed(1)}, Y ${Number(item.coordinate_y).toFixed(1)}`,value:String(item.id),description:`${index<4?"Displayed guess":"Other known location"} · ${Math.round(item.confidence*100)}% similarity`})));}
function rankedLocationSummary(locations){return `**Ranked location guesses**\n${locations.slice(0,4).map((item,index)=>`${index+1}. **X ${Number(item.coordinate_x).toFixed(1)}, Y ${Number(item.coordinate_y).toFixed(1)}** — ${Math.round(item.confidence*100)}%`).join("\n")}\n\nThe menu includes ${locations.length>4?`these four plus ${locations.length-4} other known coordinate${locations.length-4===1?"":"s"}`:"every known coordinate"}.`;}
async function submitCorrection({interaction,pool,source,chosen,zone,x,y,portalUrl,officerLogChannelId,officer=false}){
  const reviewStatus=officer?"approved":"pending",reviewedBy=officer?interaction.user.id:null;
  const reference=await pool.query(
    `insert into portal_treasure_map_references
       (map_type,zone_name,coordinate_x,coordinate_y,party_size,image_hash,submitted_by,review_status,reviewed_by,reviewed_at)
     values($1,$2,$3,$4,$5,$6,$7,$8,$9,case when $8='approved' then now() end)
     returning id`,
    [chosen.value,zone,x,y,chosen.party,source.image_hash,interaction.user.id,reviewStatus,reviewedBy]
  );
  const correction=await pool.query(
    `insert into portal_treasure_map_corrections
       (scan_id,reference_id,map_type,zone_name,coordinate_x,coordinate_y,submitted_by,review_status,reviewed_by,reviewed_at)
     values($1,$2,$3,$4,$5,$6,$7,$8,$9,case when $8='approved' then now() end)
     returning id`,
    [source.id,reference.rows[0].id,chosen.value,zone,x,y,interaction.user.id,reviewStatus,reviewedBy]
  );
  const corrected={map_type:chosen.value,zone_name:zone,coordinate_x:x,coordinate_y:y,party_size:chosen.party,confidence:1};
  if(source.response_message_id&&source.source_channel_id){
    const channel=await interaction.client.channels.fetch(source.source_channel_id).catch(()=>null),message=channel?.isTextBased()?await channel.messages.fetch(source.response_message_id).catch(()=>null):null;
    if(message)await message.edit({embeds:[embed(corrected)],components:components(source.id,portalUrl)});
  }
  if(officerLogChannelId){
    const channel=await interaction.client.channels.fetch(officerLogChannelId).catch(()=>null);
    if(channel?.isTextBased()){
      const payload=officer
        ? {content:`**Treasure-map training approved**\nConfirmed and approved by <@${interaction.user.id}>\n${chosen.label} · ${zone} · X ${x.toFixed(1)}, Y ${y.toFixed(1)}`}
        : {content:`**Treasure-map training review**\nSubmitted by <@${interaction.user.id}>\n${chosen.label} · ${zone} · X ${x.toFixed(1)}, Y ${y.toFixed(1)}\nApprove only if the public correction is accurate.`,components:[row(new ButtonBuilder().setCustomId(`map:approve:${correction.rows[0].id}`).setStyle(ButtonStyle.Success).setLabel("Approve Training Match"),new ButtonBuilder().setCustomId(`map:reject:${correction.rows[0].id}`).setStyle(ButtonStyle.Danger).setLabel("Reject"))]};
      await channel.send(payload).catch(()=>null);
    }
  }
  const content=officer
    ? `Location set to **${zone} — X ${x.toFixed(1)}, Y ${y.toFixed(1)}**. Your administrator confirmation was approved immediately and can train future matches.`
    : `Location set to **${zone} — X ${x.toFixed(1)}, Y ${y.toFixed(1)}**. An officer must approve this screenshot fingerprint before it trains future matches.`;
  if(interaction.isStringSelectMenu())await interaction.update({content,components:[]});else await interaction.reply({content,flags:MessageFlags.Ephemeral});
}
export async function handleTreasureMapComponent(interaction,pool,{portalUrl="",officerLogChannelId="",isOfficer=async()=>false}={}){if(!interaction.customId?.startsWith("map:"))return false;await ensureTreasureMapSchema(pool);const [,action,id,extra]=interaction.customId.split(":"),officer=await isOfficer(interaction);try{
  if(action==="approve"||action==="reject"){if(!officer)throw new Error("Only an officer can review map training data.");const correction=(await pool.query(`select * from portal_treasure_map_corrections where id=$1`,[id])).rows[0];if(!correction||correction.review_status!=="pending")throw new Error("This correction has already been reviewed.");const status=action==="approve"?"approved":"rejected";await pool.query(`update portal_treasure_map_corrections set review_status=$2,reviewed_by=$3,reviewed_at=now() where id=$1`,[id,status,interaction.user.id]);await pool.query(`update portal_treasure_map_references set review_status=$2,reviewed_by=$3,reviewed_at=now() where id=$1`,[correction.reference_id,status,interaction.user.id]);await interaction.update({content:`${status==="approved"?"Approved":"Rejected"} by <@${interaction.user.id}>.`,components:[]});return true;}
  const source=await ownedScan(pool,id,interaction.user.id,officer);
  if(action==="locations"){if(!source.detected_zone_name||![1,8].includes(Number(source.detected_party_size)))throw new Error("The zone or player count is unclear. Use Correct Filters / Rescan first.");const chosen=source.selected_map_type?type(source.selected_map_type):null,locations=await knownLocations(pool,source,chosen,source.detected_zone_name);if(!locations.length)throw new Error("No known coordinates match those filters. Use Correct Filters / Rescan to select the map family and zone.");await interaction.reply({content:`**${source.detected_zone_name} · ${source.detected_party_size} player${Number(source.detected_party_size)===1?"":"s"}${chosen?` · ${chosen.label}`:""}**\n${rankedLocationSummary(locations)}\nChoose the correct coordinate to ${officer?"confirm and approve it immediately":"submit it for officer review"}.`,components:[row(locationPicker(id,locations,chosen?.value||"any"))],flags:MessageFlags.Ephemeral});return true;}
  if(action==="correct"){const menu=new StringSelectMenuBuilder().setCustomId(`map:party:${id}`).setPlaceholder("Choose the player count shown").addOptions([{label:"1 player",value:"1",description:"Solo treasure map"},{label:"8 players",value:"8",description:"Full-party treasure map"}]);await interaction.reply({content:"Choose the player count first. You will then select the map family and zone before the image is reranked.",components:[row(menu)],flags:MessageFlags.Ephemeral});return true;}
  if(action==="party"&&interaction.isStringSelectMenu()){const party=Number(interaction.values[0]);if(![1,8].includes(party))throw new Error("Choose either 1 or 8 players.");const choices=TYPES.filter(item=>item.party===party).slice(0,25),menu=new StringSelectMenuBuilder().setCustomId(`map:type:${id}:${party}`).setPlaceholder("Choose the treasure-map type").addOptions(choices.map(item=>({label:item.label,value:item.value,description:`${item.zones.length} possible zone${item.zones.length===1?"":"s"}`})));await interaction.update({content:`**${party} player${party===1?"":"s"}** selected. Now choose the treasure-map family.`,components:[row(menu)]});return true;}
  if(action==="type"&&interaction.isStringSelectMenu()){const chosen=type(interaction.values[0]),party=Number(extra);if(!chosen||chosen.party!==party)throw new Error("That map type does not match the selected player count.");const menu=new StringSelectMenuBuilder().setCustomId(`map:zone:${id}:${chosen.value}`).setPlaceholder("Choose the zone shown on the map").addOptions(chosen.zones.slice(0,25).map(zone=>({label:zone,value:zone})));await interaction.update({content:`**${chosen.label} · ${party} player${party===1?"":"s"}** selected. Now choose the zone.`,components:[row(menu)]});return true;}
  if(action==="zone"&&interaction.isStringSelectMenu()){const chosen=type(extra),zone=interaction.values[0];if(!chosen||!chosen.zones.includes(zone))throw new Error("That zone is not valid for this map type.");await pool.query(`update portal_treasure_map_scans set selected_map_type=$2,detected_zone_name=$3,detected_party_size=$4 where id=$1`,[id,chosen.value,zone,chosen.party]);const locations=await knownLocations(pool,source,chosen,zone);if(!locations.length){await interaction.showModal(coordinateModal(id,chosen,zone));return true;}await interaction.update({content:`**Rescan filters: ${chosen.label} · ${zone} · ${chosen.party} player${chosen.party===1?"":"s"}**\n${rankedLocationSummary(locations)}\nChoose the correct coordinate to ${officer?"confirm and approve it immediately":"submit it for officer review"}.`,components:[row(locationPicker(id,locations,chosen.value))]});return true;}
  if(action==="location"&&interaction.isStringSelectMenu()){let chosen=extra==="any"?null:type(extra);const selected=interaction.values[0];if(extra!=="any"&&!chosen)throw new Error("That map type is unavailable.");if(selected.startsWith("manual|")){const zone=selected.slice(7);if(!chosen||!chosen.zones.includes(zone))throw new Error("That zone is not valid for this map type.");await interaction.showModal(coordinateModal(id,chosen,zone));return true;}const reference=(await pool.query(`select * from portal_treasure_map_references where id=$1 and review_status='approved'`,[selected])).rows[0];if(!reference)throw new Error("That known location is no longer available.");if(reference.zone_name!==source.detected_zone_name||Number(reference.party_size)!==Number(source.detected_party_size)||(chosen&&reference.map_type!==chosen.value))throw new Error("That location does not match the active map filters.");chosen=chosen||type(reference.map_type)||{value:reference.map_type,label:"Treasure map",party:Number(reference.party_size),zones:[reference.zone_name]};await submitCorrection({interaction,pool,source,chosen,zone:reference.zone_name,x:Number(reference.coordinate_x),y:Number(reference.coordinate_y),portalUrl,officerLogChannelId,officer});return true;}
  if(action==="coordinates"&&interaction.isModalSubmit()){const chosen=type(extra),zone=interaction.fields.getTextInputValue("zone").trim(),x=Number(interaction.fields.getTextInputValue("x")),y=Number(interaction.fields.getTextInputValue("y"));if(!chosen||!chosen.zones.includes(zone)||!Number.isFinite(x)||!Number.isFinite(y)||x<0||y<0||x>50||y>50)throw new Error("Enter a listed zone and coordinates between 0 and 50.");await submitCorrection({interaction,pool,source,chosen,zone,x,y,portalUrl,officerLogChannelId,officer});return true;}
 }catch(error){const payload={content:short(error?.message||error),components:[],flags:MessageFlags.Ephemeral};if(interaction.deferred||interaction.replied)await interaction.followUp(payload).catch(()=>null);else await interaction.reply(payload).catch(()=>null);return true;}return false;}
export function startTreasureMapCleanup(pool){const clean=()=>ensureTreasureMapSchema(pool).then(()=>pool.query(`update portal_treasure_map_scans set image_data=null where image_data is not null and expires_at<=now()`)).catch(error=>console.warn("[treasure-maps] Cache cleanup failed:",error?.message||error));setTimeout(clean,30000);return setInterval(clean,300000);}
